### ISSUE TITLE
invoke packit via context manager

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1009]
context: https://github.com/packit/packit/pull/1129#discussion_r584568817

Since sandcastle requires cleanup after it's done after we merge https://github.com/packit/packit/pull/1129, we should start invoking packit via a context manager to be sure the cleanup actually happens.

**Comment by lachmanfrantisek** [comment]
Still nice to have. Looks like some nice Python work for Friday.

**Comment by TomasTomecek** [comment]
I am going to close this one since we haven't done this yet.

Please reopen or create a new issue with more detailed steps how to improve the current situation. I don't have bandwidth to own such a change.
