### ISSUE TITLE
Make the rpm package naming configurable

### ISSUE THREAD

**Issue by psss** [packit/packit-service#1010]
Currently the default package names are a little big too long:

    tmt-1.3.1-1.20210303080959311990.master.11.g319a243.fc33.noarch

It would be nice to allow users to choose their preferred format, for example date only:

    tmt-1.3.1-1.20210303.master.11.g319a243.fc33.noarch

Or omit the timestamp completely:

    tmt-1.3.1-1.master.11.g319a243.fc33.noarch

Btw, why is the default timestamp string so long? Number of commits above master together with the commit hash seems to provide quite unique identification.

**Comment by TomasTomecek** [comment]
We have worked with the OAMG team to define it - I don't recall details any more.

Makes perfect sense to me to make it configurable.

**Comment by lachmanfrantisek** [comment]
I am tjust hinking how important this will be once we have #642 and can provide a list of name-version-release of the build packages? (The functionality is now waiting for the release on the Copr side.)

**Comment by TomasTomecek** [comment]
There was a similar request from OAMG team to have the version/release parts configurable.

I think it would be nice to have but doesn't seem to be critical.

**Comment by psss** [comment]
Still would be nice... :)

**Comment by TomasTomecek** [comment]
This is now fully configurable: https://packit.dev/docs/configuration/#release_suffix
