### ISSUE TITLE
URL to Testing Farm results in 404 while tests are running

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1011]
reported by @martinpitt @marusak

Would it be possible to provide live logs or at least some status saying the tests are in progress and logs would be available after the run is complete.

Another, similar, requirement would be if users were able to tell if the job is stuck or just queued - some sort of dashboard would be mind-blowing.

@thrix

**Comment by thrix** [comment]
What we can do quickly is this:

http://artifacts.dev.testing-farm.io/eaed0960-5afe-4e82-87fc-62271fbaa9cc/

Dashboard and progress is coming, but it will take some time.

**Comment by thrix** [comment]
Jobs should not get stuck, timeout on every job is currently set to 4h.

**Comment by thrix** [comment]
Preview: [
![Selection_001](https://user-images.githubusercontent.com/633969/109963662-f9341c00-7cec-11eb-9c73-ca2f94562678.png)
](url)

**Comment by marusak** [comment]
> Jobs should not get stuck, timeout on every job is currently set to 4h.

Triggered ~6 hours ago in https://github.com/cockpit-project/cockpit-podman/pull/687 and still waiting

**Comment by thrix** [comment]
@marusak my bad, the will timeout soon sorry :) Podman test suite is hanging in CI, not sure if related, need to provide a test machine to esm finally ....

**Comment by thrix** [comment]
anywya, I am looking why this is there running for 6 hours ...

**Comment by thrix** [comment]
@marusak sorry to say, but I cannot find even out what happened here, rerunning ....

**Comment by TomasTomecek** [comment]
Thank Miro for the updates! I'd say the "In progress" page is better than 404 - not sure if the results directory is being constructed along the way and could provide some info while the tests are running.

**Comment by thrix** [comment]
Yep, it is coming, I filled https://gitlab.com/testing-farm/general/-/issues/13

**Comment by lachmanfrantisek** [comment]
I think we don't need to track this here -- Testing Farm now shows a static page instead of `404` and has an [issue for progress](https://gitlab.com/testing-farm/general/-/issues/13). And on our side, we use the dashboard and don't link TF directly.

If you have any suggestion for improvement on the packit-service side, let us know.
