### ISSUE TITLE
Reply containing "/packit copr-build" triggers new build

### ISSUE THREAD

**Issue by clebergnu** [packit/packit-service#1025]
As can be seen [here](https://github.com/avocado-framework/avocado/pull/4468#issuecomment-802808629), a reply was made to a "/packit copr-build" line, and even with it being quoted, it triggered another unintentional build.

IMO, only explicit "/packit copr-build" lines should trigger new builds.

**Comment by lachmanfrantisek** [comment]
@clebergnu thanks for letting us know! Good catch! Sorry about that.

You are right, our rule should be to parse command on a single line of the comment, so this is valid:

```
>
/packit copr-build
```

But not this:
```
> /packit copr-build
```

----

For our team, the task here is to:
- [ ] Fix the comment parsing not to parse quoted command.
- [ ] Introduce a new test-case.

**Comment by lachmanfrantisek** [comment]
Related code:

https://github.com/packit/packit-service/blob/58b18d2efe73a8bc53f6f153bb8bb5b86d651e4c/packit_service/worker/jobs.py#L128-L152

and tests:

https://github.com/packit/packit-service/blob/58b18d2efe73a8bc53f6f153bb8bb5b86d651e4c/tests/integration/test_pr_comment.py#L308-L324

https://github.com/packit/packit-service/blob/58b18d2efe73a8bc53f6f153bb8bb5b86d651e4c/tests/integration/test_pr_comment.py#L327-L342

From the tests, it looks like the original intention was to accept packit command anywhere, e.g. `"Should be fixed now, lets /packit build it."`. What behaviour do we want? Do we want to skip quotes or accept packit only on a single line?

**Comment by clebergnu** [comment]
Hi @lachmanfrantisek , I believe matching a single line (possibly stripped of while spaces) is the way to go. Thanks!

**Comment by TomasTomecek** [comment]
this would indeed be awesome! I often get irritated when I need to post 2 comments in a PR
