### ISSUE TITLE
Switch link for results of build/tests to dashboard

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1033]
- [x] Switch links in commit statuses from service page to dashboard
   affects:
   - SRPM builds
   - COPR builds
   - Koji builds
   - Testing Farm results
- [x] Forward requests from old commit statuses to dashboard
   - [x] Drop current content of build result page
   - [x] When requesting results on service, redirect to dashboard (needs smaller adjustments: domain, dashboard uses plural (e.g. `copr-build ~> copr-builds`), also has prefix `/results`)
- [ ] Disable redirecting after some time

---
ideally to be planned with: #982, packit/dashboard#86

**Comment by mfocko** [comment]
I just noticed, it is open; to clarify the state of the issue: it is done, **but** we still redirect requests to service to dashboard, because of a backward compatibility with already set commit statuses. This issue can be finished and closed by removing the redirection after 1-2 times it gets marked as `stale` which should be enough time to replace all of the statuses with new links.

**Comment by lachmanfrantisek** [comment]
> after 1-2 times it gets marked as stale which should be enough time to replace all of the statuses with new links.

:one:

**Comment by lachmanfrantisek** [comment]
:two: I think it's the time..;)

**Comment by mfocko** [comment]
Dropping in favor of #1034
