### ISSUE TITLE
Drop code for build and test results in packit-service and have it only in the dashboard

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1034]
To be done at least 1 month after #1033 

- [x] Disable redirection to dashboard
- [x] Remove results from service completely
- [x] Serve results only on dashboard

**Comment by lachmanfrantisek** [comment]
I think we are good to go.

**Comment by TomasTomecek** [comment]
Yup, let's do this :))

**Comment by TomasTomecek** [comment]
time to delete some code :)

**Comment by mfocko** [comment]
> time to delete some code :)
> 
> edit: changed the title because I got confused about the former one

yep, I think we have two of them (issues)…
