### ISSUE TITLE
Service sometimes does not react to /packit test

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1036]
@psss has encountered multiple times that the service did nothing after he put `/packit test` comment. (Adding another comment helped.)

Example PRs:
* https://github.com/psss/tmt/pull/676
* https://github.com/psss/fmf/pull/124

TODO:
* [ ] Try reproducing the same behaviour.
* [ ] Check the content of the database.
* [ ] Check the logs/sentry.
* [ ] Find and fix the problem.

**Comment by lachmanfrantisek** [comment]
Note that there is only one build for PR 124 and it failed on SRPM (because of the quota).

**Comment by lbarcziova** [comment]
> Note that there is only one build for PR 124 and it failed on SRPM (because of the quota).

That may explain the failure of the task (Sentry issue says that it wasn't successful). I haven't found relevant logs, but assuming from the info in issue, it probably failed because there is [no latest copr build](https://github.com/packit/packit-service/blob/92d9a6f80cc44216c8c3c11dfa968e78e46124e7/packit_service/worker/testing_farm.py#L214), in that case (when tests are triggered by comment), we do not run the needed build for tests (but I'm not sure whether this is the expected behaviour)

**Comment by lachmanfrantisek** [comment]
> (when tests are triggered by comment), we do not run the needed build for tests (but I'm not sure whether this is the expected behaviour)

That's a good question. When the build is only some internal step to run the test (=only the test is defined), the build should be retriggered I would say.

I am not sure about the other variant (=test and build is defined). On one side, they will lose results from the previous build, on the other side, rerunning the build is the only thing that can help. (Otherwise, they need to push new changes.)

@psss What do you think about that?

**Comment by psss** [comment]
> When the build is only some internal step to run the test (=only the test is defined), the build should be retriggered I would say.

Make sense to me.

**Comment by lachmanfrantisek** [comment]
So to conlcude this:

- [ ] The task here is to make sure that we run the build for `/packit test` when there is no build for HEAD commit or there is no successful target for the last build of the HEAD commit.

@lbarcziova @psss Does it make sense?

**Comment by psss** [comment]
Yeah, sounds good.

**Comment by mmuzila** [comment]
> So to conlcude this:
> 
>     * [ ]  The task here is to make sure that we run the build for `/packit test` when there is no build for HEAD commit or there is no successful target for the last build of the HEAD commit.

This  means that [`TestingFarmHandler`](https://github.com/packit/packit-service/blob/02e5bca838472bf7eeb71c1c4058b5a3ee66d032/packit_service/worker/handlers/testing_farm_handlers.py#L44) should check if there is a build for HEAD commit with successful targets. Am I right?

If I'm right, what should do the [`TestingFarmHandler`](https://github.com/packit/packit-service/blob/02e5bca838472bf7eeb71c1c4058b5a3ee66d032/packit_service/worker/handlers/testing_farm_handlers.py#L44) if there is no usable build? It could fire new copr build, but what should be returned by [`TestingFarmHandler.run()`](https://github.com/packit/packit-service/blob/02e5bca838472bf7eeb71c1c4058b5a3ee66d032/packit_service/worker/handlers/testing_farm_handlers.py#L81) then?

**Comment by lachmanfrantisek** [comment]
@mmuzila Sorry for my delay (please, ping me next time).

> This means that TestingFarmHandler should check if there is a build for HEAD commit with successful targets. Am I right?

:+1: Yes, sounds good.

> If I'm right, what should do the [`TestingFarmHandler`](https://github.com/packit/packit-service/blob/02e5bca838472bf7eeb71c1c4058b5a3ee66d032/packit_service/worker/handlers/testing_farm_handlers.py#L44) if there is no usable build? It could fire new copr build, but what should be returned by [`TestingFarmHandler.run()`](https://github.com/packit/packit-service/blob/02e5bca838472bf7eeb71c1c4058b5a3ee66d032/packit_service/worker/handlers/testing_farm_handlers.py#L81) then?

Good point, I think we can trigger a new build by adding a new task to the celery queue and return a successful result with message like "build required, triggering the build" -- I don't think we process that information.
