### ISSUE TITLE
Name of the Copr project for release contains version tag

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1044]
It looks like we currently use the version in the default Copr project name for release builds so each release has a separate Copr project what is probably not what we want.

e.g.:
* https://copr.fedorainfracloud.org/coprs/packit/packit-requre-0.6.1/
* https://copr.fedorainfracloud.org/coprs/packit/packit-requre-0.7.0/

What about using `{namespace}-{project}-releases` name for the Copr project?

(We already had something like this in the past I think.)

**Comment by lachmanfrantisek** [comment]
We can't decide within the team if this is what we want. What do others think? @jscotka @psss @thrix @jkonecny12 @bocekm @packit/the-packit-team Can you please vote (:+1: / :-1: ) on the top comment so we know your opinion? Thanks in advance!!

My reasoning why we might want this:
* For branch builds, we share the project as well.
* Branch/release builds look more user-targeted to me.
* Having a Copr repo with the released code without a need to provide own project looks like a nice feature to me.

**Comment by bocekm** [comment]
In convert2rhel we use our [own copr repo](https://github.com/oamg/convert2rhel/blob/main/.packit.yaml#L10), so this does not affect us, but before switching I observed this behaviour and back then I would vote for 👍 just to have one known copr repo URL I can go to to find the latest built convert2rhel development packages.

**Comment by jkonecny12** [comment]
I don't have strong opinion on this but I'm more inclined to :+1: . Mainly because it would be much easier to look on the history to compare builds or to give someone a link for the release builds.

**Comment by TomasTomecek** [comment]
If the use case here is to "share project releases with the users", then the proposal makes sense.

On the other hand, if it's meant to be CI for the release process then the current default sounds better.

In the end, it seems that no one is actually using or relying on this feature so we should be good with changing this to what we feel like is a better default.

@jkonecny12 @bocekm thank you for your feedback!

**Comment by psss** [comment]
From the user point of view I would prefer to have just a single repo with all releases so that once we bump version users do not have to do another `dnf copr enable` command. But we also use custom copr namespace so this change does not affect us.

**Comment by lachmanfrantisek** [comment]
Thanks all of you for your opinion, looks like we can have one project for all the releases.
