### ISSUE TITLE
Enable users identify installed RPMs during testing in TF

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1045]
We've just a request from the kdump maintainer so they can identify what are the exact RPMs that were installed in the test environment so they can manipulate them. There are two unsolved problems here:
1. Since the builds are being picked from COPR, users also need to know the copr project name
2. One SRPM can easily produce multiple binary RPMs - we especially need to track those for this use case

I'm wondering if the easiest solution here is to download the binary RPMs, place them in a pre-defined path and document this.

**Comment by psss** [comment]
> I'm wondering if the easiest solution here is to download the binary RPMs, place them in a pre-defined path and document this.

Just note to @thrix that this approach would nicely work with `tmt run prepare --how install --directory /path/with/rpms`. But I know there's some extra magic `tft` is doing when installing the packages. Perhaps could be combined also with the new `--exclude` option. Just brainstorming as this seems to be slightly related...

**Comment by lachmanfrantisek** [comment]
Some update --we can finally get this info from Copr (since the next release).

**Comment by lachmanfrantisek** [comment]
I hope we just need to provide two new env. variables in TF environment:
* copr project name
* list of NVRs: (=list divided by spaces so it's easily usable as is, e.g. as a `dnf install` argument)

Something like this:
```
cockpit-system-263-1.20220224091012431332.pr16135.41.gd32250011.fc37.noarch cockpit-doc-263-1.20220224091012431332.pr16135.41.gd32250011.fc37.noarch cockpit-debuginfo-263-1.20220224091012431332.pr16135.41.gd32250011.fc37.i686 cockpit-tests-263-1.20220224091012431332.pr16135.41.gd32250011.fc37.i686 cockpit-pcp-263-1.20220224091012431332.pr16135.41.gd32250011.fc37.i686
```

**Comment by lachmanfrantisek** [comment]
Implementation note:
* Here are the similar PRs to get inspired: #1467, #1382
