### ISSUE TITLE
Clean up the sandcastle session properly when an SRPM build fails

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1047]
> So the cleanup is not run when an SRPM build fails?

Yes, that's what I've deduced from the logs. There was no `Pod/PVC deletion status ...` in logs after the crash.

_Originally posted by @jpopelka in https://github.com/packit/sandcastle/issues/114#issuecomment-814938858_

**Comment by jpopelka** [comment]
1. Succesful build
Logs:
```
reporting.py      DEBUG  Setting status 'pending' for check 'xyz': Starting RPM build...
abstract.py       INFO   Cleaning up the mess.
...
abstract.py       DEBUG  Job finished!
Deleting sandcastle pod.
PVC deletion status = ...
```
I'm wondering where/how do we actually call the sandcastle cleanup. I'd expect it in [JobHandler.run_job()](https://github.com/packit/packit-service/blob/7ddfb45f936c0c3cfadad85c6fc34ded33c40d3f/packit_service/worker/handlers/abstract.py#L324) -> [JobHandler.run_n_clean()](https://github.com/packit/packit-service/blob/7ddfb45f936c0c3cfadad85c6fc34ded33c40d3f/packit_service/worker/handlers/abstract.py#L233) -> [JobHandler.clean()](https://github.com/packit/packit-service/blob/7ddfb45f936c0c3cfadad85c6fc34ded33c40d3f/packit_service/worker/handlers/abstract.py#L274) -> [PackitApi.clean()](https://github.com/packit/packit/blob/e7b6dbf22dd9f2e9d9ea38e24cf6c5d4921437cb/packit/api.py#L891) -> [SandcastleCommandHandler.clean()](https://github.com/packit/packit/blob/e7b6dbf22dd9f2e9d9ea38e24cf6c5d4921437cb/packit/command_handler.py#L176), but in that case would the `Deleting sandcastle pod.` be in logs before the `Job finished!`, not after it.


2. Failed SRPM build, i.e lingering pod & pvc left behind
Logs:
```
reporting.py      DEBUG  Setting status 'failure' for check 'xyz': SRPM build failed, check the logs for details.
abstract.py       INFO   Cleaning up the mess.
...
abstract.py       DEBUG  Job finished!
abstract.py       ERROR  SRPM build failed, check the logs for details.
Task TaskName.copr_build[abc] succeeded in 1526s:
```

**Comment by TomasTomecek** [comment]
That's my expectation as well.

Sadly I won't have time to work on this today, wanna finish some other work.

**Comment by lachmanfrantisek** [comment]
With the repository-cache volumes in the deployment, this is now a real problem.

When we leave the pod without clean-up, the old pod has the repository-cache volume mounted what blocks the creation of a new pod.

Here are some examples:
* Two failed SRPM builds:
    * https://dashboard.packit.dev/results/srpm-builds/31105
    * https://dashboard.packit.dev/results/srpm-builds/31115
* And pod can't be created in the next one:
  * https://dashboard.packit.dev/results/srpm-builds/31116
