### ISSUE TITLE
API: /api/projects/{forge}/{namespace}/{repo_name}/prs is broken

### ISSUE THREAD

**Issue by IceWreck** [packit/packit-service#1053]
Ex: https://prod.packit.dev/api/projects/github.com/abrt/retrace-server/prs?page=1&per_page=10 this is dead

**Comment by lachmanfrantisek** [comment]
The API structure looks good, maybe some memory problem?

**Comment by TomasTomecek** [comment]
yeah, doesn't work for me either :/ that's a bummer, I wonder what's wrong

**Comment by lbarcziova** [comment]
The problem was in the incorrect database query when getting info about builds and tests for the PR which was causing memory overload.

This should be resolved now by packit-service#1114, see in staging e.g. https://stg.packit.dev/api/projects/github.com/psss/tmt/prs?page=1&per_page=10

**Comment by lachmanfrantisek** [comment]
Works well also on the dashboard: https://dashboard.stg.packit.dev/projects/github.com/packit/packit
