### ISSUE TITLE
Filtering issues

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1071]
Filtering of issues in case we want only one issue regarding configuration shared across multiple runs of p-s.

Current solution: filtering by the title of the issue
Tried solution: filtering by the author of the issue

Tried solution is not possible, since we use Tokman that provides unique tokens **per** repository and therefore service itself does not have any PyGithub object, that could return login of the currently authenticated "user".

1. We cannot guess the name, since:
   - GitHub: `app/packit-as-a-service`
   - GitLab: `packit-as-a-service`
2. We cannot directly touch `GitProject`'s pygithub instance, not compatible with GitLab
3. Extending `GitProject`'s interface with `get_username` and whatnot, does not make sense...
4. Extending `Tokman`'s interface, again... Does not relate, would not be compatible with GitLab

Possible solution: Tag our issues with `packit` label, but that requires users to have that label set up...

**Comment by lachmanfrantisek** [comment]
> Possible solution: Tag our issues with `packit` label, but that requires users to have that label set up...

Can't we do that for them?

**Comment by mfocko** [comment]
> Can't we do that for them?

We have a write access, so it should be possible to label the newly-created issue. Apparently we can create them too, but not sure how _nice_ it is to create label in someone's repository :thinking:

**Comment by lachmanfrantisek** [comment]
Good point. What do the others do? Stale-bot/...

**Comment by TomasTomecek** [comment]
We can also store the issue ID in our database.

**Comment by mfocko** [comment]
> We can also store the issue ID in our database.

Yeah, I was thinking about that... IMO it requires some maintenance on our side (cleaning up closed issues), on the other hand we could probably do that before checking against the DB and creating new issue if necessary, but still results in "leftover" data in DB.

I like the label idea, but it seems a bit invasive :shrugs:

**Comment by mfocko** [comment]
Still needed, so... let's be invasive? 😏 😂

**Comment by lachmanfrantisek** [comment]
Can't we use this? https://github.com/packit/ogr/pull/655

**Comment by mfocko** [comment]
> Can't we use this? [packit/ogr#655](https://github.com/packit/ogr/pull/655)

This issue is about the issues (pun intended) whereas the linked PR allows getting app that posted the check run.

The major issue here is that we cannot filter based on the user / service account, because in each service it has a different login (github: `app/packit-as-a-service`, gitlab: `packit-as-a-service`; diplomatically I'm leaving out filtering on Pagure…).

The most ideal way is label, since it allows filtering directly via forge API and also we do not need to pollute database with, yet another, set of entries that need to be tracked for state changes.

**Comment by lachmanfrantisek** [comment]
Thinking about that now, I have a few ideas:
* I like that we currently use `[packit]` prefix of the title, but use `title in issue.title`. What about matching the full name, or using just issues with the prefix,...
* We should use a different prefix for the stage instance.
* If the author is really needed, can we try to have a configured list of possible options? (Cover the GitHub/GitLab difference.)
* We have mentioned using a database in #1427 , but how much it can help us?
* I am not against the label, but still feel like the prefix can be ok for us -- in the worse case, we will comment on a bad issue, but is this a problem?
* Do we want to reopen closed issues? (Currently, we list only opened ones.)
