### ISSUE TITLE
Explicitly link the ref and file when opening issues for bogus configs

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1076]
Packit Service opens issues when [deprecated configuration keys are processed](https://github.com/packit/packit-service/blob/07c06973a9430cf0f9841986be70c17bc8d4fcc5/packit_service/config.py#L295) or a [package configuration is found that fails validation](https://github.com/packit/packit-service/blob/07c06973a9430cf0f9841986be70c17bc8d4fcc5/packit_service/config.py#L314).

Update the text of these issues to explicitly link the file and commit for which the issue is filed. Put it in other way: we should provide the permalink to the package config we open the issue for, so that users don't have to second guess the branch or commit for which the issue was opened.

**Comment by lachmanfrantisek** [comment]
Good point.

How do we want to behave when the issue has already been created? A new comment with the updated occurrence? Or nothing? Or, create an issue only when the problem is on the main branch and comment on PR otherwise?

**Comment by csomh** [comment]
Create an issue, when the problem is on some branch, comment on the PR otherwise.

If the commit changes and there is already an issue for a branch, add a new comment on that issue, mentioning the new commit hash.

**Comment by mfocko** [comment]
still needed
