### ISSUE TITLE
Enable running tests on repos which only contain FMF-based tests

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1078]
the use case here is that a project ( https://github.com/RedHat-SP-Security/tests ) contains tests for multiple components and the team would love to run TF tests on every PR: the expectation is that RPMs would come directly from a compose or basically "the latest released versions". This workflow would serve as a way to add new tests and run them during the development.

The tasks for us are:
* allow empty specfile_path
* skip the build phase completely
* submit a new TF job which would installed selected components from the official repos and run FMF tests defined in the repo

**Comment by lachmanfrantisek** [comment]
I think we've already discussed this usage of testing-farm some time ago but without any clear conclusion.

@thrix @psss Are you ok with using testing-farm as a "pure" test environment? (No Copr build, just TMT tests from upstream.)

**Comment by thrix** [comment]
@lachmanfrantisek yep, we actually run such a test today on Testing Farm - installability test from OSCI. So :+1: from me.

> submit a new TF job which would installed selected components from the official repos and run FMF tests defined in the repo

The selected components installation should be (or can be) already part of the TMT definitions, so I believe no special action needed here from us, it is the responsibility of the TMT test creator.

**Comment by lachmanfrantisek** [comment]
@thrix Thanks for the response. I wanted to be sure you don't find this as a misuse..;)

**Comment by sopos** [comment]
@TomasTomecek Is there any progress? Do you have any ETA?

**Comment by TomasTomecek** [comment]
@sopos no progress so far :/

As for ETA, we have groomed the associated jira card https://issues.redhat.com/browse/PACKIT-1351 - we expect it would take someone from us ~2 weeks to implement, verify and deploy this change to production (=big task).

We have received many other requests recently of this magnitude and are trying to figure out which should we prioritize for the upcoming sprints. If you think this feature could be utilized by more QE teams, that would be a great reason to bump priority here :)

If this is something which you need as soon as possible, we can figure out a short-term workaround. I can imagine we could create a dummy specfile in your repo which would pull in the needed packages in the testing phase. In that case we'd be wasting copr's resources a bit though it would unblock you. I can try to set that up if you're interested.

**Comment by sopos** [comment]
> @sopos no progress so far :/
> 
> We have received many other requests recently of this magnitude and are trying to figure out which should we prioritize for the upcoming sprints. If you think this feature could be utilized by more QE teams, that would be a great reason to bump priority here :)

I expect this to be usefule for more teams but I do not know what teams use github for their public tests so I'm not able to actually get the list of those.

> 
> If this is something which you need as soon as possible, we can figure out a short-term workaround. I can imagine we could create a dummy specfile in your repo which would pull in the needed packages in the testing phase. In that case we'd be wasting copr's resources a bit though it would unblock you. I can try to set that up if you're interested.

I already tried this workaround but it was failing for me and I was not able to identify the root cause. If you could take a look at https://github.com/RedHat-SP-Security/tests/pull/30 to see if you can identify the problem I would appreciate it.

**Comment by lachmanfrantisek** [comment]
@sopos Have you managed to use the workaround? Can we help with anything? I am just thinking what is the priority of this. (If there is a doable workaround, we don't need to hurry with the implementation...)

**Comment by sopos** [comment]
@lachmanfrantisek We use the dummy package workaround so there's no need to hurry. However, it unnecessarily eats resources of the build systems.

**Comment by psss** [comment]
Thanks for implementing this. So the minimal config then should look like this?

```yaml
jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-rawhide
    - epel-all
```

Would it make sense to explicitly document this use case?

**Comment by lbarcziova** [comment]
The minimal config for skipping the build phase will be:
```yaml
jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-rawhide
    - epel-all
    skip_build: true
```

>  Would it make sense to explicitly document this use case?

Definitely, as mentioned [here](https://github.com/packit/packit-service/pull/1256#issuecomment-963941042), after testing this using staging instance, this functionality will be properly documented (also, this change is currently only in staging, not in the production app).
