### ISSUE TITLE
Provide real-time logs

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1080]
We need to find a way how we can show the logs in real-time.

Some notes about implementation:
* Ideally, logs will be incorporated into the dashboard.
* Can we do this with the current workflow (data for the dashboard are transformed via packit's REST API)?
* Jobs run in workers and use sandcastle pods for running sandboxed commands.
* Do we need logs of all (external/subprocess/sandboxed) commands to be real-time (line by line), or provide all logs for each command after the command ends?

*This is a part of our UX effort to provide more information to users about the process of ongoing packit-service jobs.*

**Comment by TomasTomecek** [comment]
This absolutely needs some research - we need to find out how other projects are doing this (e.g. zuul).

For me the most natural way would be to use [websockets](https://websockets.readthedocs.io/en/stable/intro.html).

**Comment by lachmanfrantisek** [comment]
This epic is a bit outdated, there wasn't any demand for the real-time logs and we have other epics with higher priority. I am closing this and we can easily reopen if requested/needed.
