### ISSUE TITLE
Give :+1: on comment commands

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1081]
When reacting to the comment command, give a :+1: reaction to the comment to provide some clarity that we:
* have processed the comment
* are working on it.

*This is a part of our UX effort to provide more information to users about the process of ongoing packit-service jobs.*

**Comment by nikromen** [comment]
Is a good idea to implement `give +1 on comment` method in `ogr` for github and gitlab and then use its abstraction in packit-service?
