### ISSUE TITLE
Error during provisioning

### ISSUE THREAD

**Issue by yarda** [packit/packit-service#1095]
Maybe it's not packit, but I don't know where to report:
http://artifacts.dev.testing-farm.io/3daf3cd7-f9ef-49f6-b802-1e7f18d1d3c4/

It was from this run:
https://dashboard.packit.dev/results/testing-farm/23445

**Comment by lachmanfrantisek** [comment]
Hi @yarda !

Thanks for creating the issue. This is probably better to report directly to the testing farm.

> Test "/ci" failed.
>
> Found a bug? Please open an issue in the issue tracker: https://gitlab.com/testing-farm/general/-/issues

@thrix Can you please take a look? Was it some flake?

**Comment by lachmanfrantisek** [comment]
When looking at the output, isn't this a problem with the repo-query?

```
Error: 
 Problem: problem with installed package tuned-profiles-spectrumscale-v2.15.0-1.20210514080120084082.pr347.21.g510ea93.el8.noarch
  - package tuned-profiles-spectrumscale-v2.15.0-1.20210514080120084082.pr347.21.g510ea93.el8.noarch requires tuned = v2.15.0, but none of the providers can be installed
  - package tuned-profiles-spectrumscale-v2.15.0-1.20210513080354077748.pr347.21.g22dc940.el8.noarch requires tuned = v2.15.0, but none of the providers can be installed
  - cannot install both tuned-2.14.0-3.el8_3.1.noarch and tuned-v2.15.0-1.20210514080120084082.pr347.21.g510ea93.el8.noarch
  - cannot install both tuned-v2.15.0-1.20210513080354077748.pr347.21.g22dc940.el8.noarch and tuned-2.14.0-3.el8_3.1.noarch
  - cannot install both tuned-v2.15.0-1.20210514080120084082.pr347.21.g510ea93.el8.noarch and tuned-2.14.0-3.el8_3.1.noarch
  - cannot install the best candidate for the job
```

**Comment by lachmanfrantisek** [comment]
And this looks like a deprecated tmt executor:

```
    warn: The 'beakerlib' execute method has been deprecated.
    warn: Use 'how: tmt' in the execute step instead (L2).
    warn: Set 'framework: beakerlib' in test metadata (L1).
    warn: Support for old methods will be dropped in March 2021.
```

**Comment by yarda** [comment]
> And this looks like a deprecated tmt executor:
> 
> ```
>     warn: The 'beakerlib' execute method has been deprecated.
>     warn: Use 'how: tmt' in the execute step instead (L2).
>     warn: Set 'framework: beakerlib' in test metadata (L1).
>     warn: Support for old methods will be dropped in March 2021.
> ```

This shouldn't be related to this problem, because tests for Fedora provisioned the RPMs OK. Hopefully, we fixed this deprecated syntax by:
https://github.com/redhat-performance/tuned/pull/348

**Comment by yarda** [comment]
It's failing on:
```
packit/testing-farm-centos-stream-8-x86_64 
packit/testing-farm-epel-8-x86_64
```
On Fedora it's passing. See e.g. results of https://github.com/redhat-performance/tuned/pull/348

**Comment by TomasTomecek** [comment]
I can see the tracking TF issue is now closed, I believe we can close this one as well:

https://gitlab.com/testing-farm/general/-/issues/25

@yarda thanks for creating both requests!

**Comment by yarda** [comment]
I think I know where the problem is. It's in the way how packit creates RPMs:
```
tuned-v2.15.0-1.20210513080354077748.pr347.21.g22dc940.el8.noarch
```
Notice the version 'v2.15.0', because it is created from the tag 'v2.15.0', the tags in TuneD project are historically prefixed with 'v'.

But  on the machine there is already installed:
```
tuned-2.14.0-3.el8_3.1.noarch
```
and:
```
tuned-2.14.0-3.el8_3.1.noarch > tuned-v2.15.0-1.20210513080354077748.pr347.21.g22dc940.el8.noarch
```
That's why the package isn't installed/upgraded. With Fedora this problem doesn't happen, because TuneD isn't pre-installed there.

I think adding `--allowerasing` to the transaction or stripping the initial 'v' from the version may resolve this problem.

**Comment by lachmanfrantisek** [comment]
@yarda Good catch -- you can try using `upstream_tag_template` option: https://packit.dev/docs/configuration/#upstream_tag_template to avoid this problem.

I am going to close this one and we can create a new issue in case of problems with the versions.
