### ISSUE TITLE
error: failed to push some refs to dist-git

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1107]
dracutdevs/dracut#1524

from logs:
```
About to upload to lookaside cache.
Command: fedpkg new-sources /tmp/packit-dist-git4p65ihm4/dracut-055.tar.xz
Uploading: /tmp/packit-dist-git4p65ihm4/dracut-055.tar.xz
Source upload succeeded. Don't forget to commit the sources file
About to add all & commit.
Pushing changes to remote 'origin' using refspec 'HEAD:main'.
Error lines received while fetching: error: failed to push some refs to 'ssh://pkgs.fedoraproject.org/rpms/dracut'
Push summary: [remote rejected] (pre-receive hook declined)

Push flags: 1040
Local package config found: /tmp/packit-dist-git4p65ihm4/.packit.yml
Local spec files found: [PosixPath('dracut.spec')]. Taking: dracut.spec
Package config:
{
    "upstream_package_name": "dracut",
    "upstream_tag_template": "{version}",
    "upstream_project_url": "https://github.com/dracutdevs/dracut",
    "specfile_path": "pkgbuild/dracut.spec",
    "downstream_package_name": "dracut",
    "dist_git_base_url": "https://src.fedoraproject.org/",
    "synced_files": [
        "dracut.spec",
        ".packit.yaml"
    ],
    "create_pr": false,
    "jobs": [
        {
            "job": "propose_downstream",
            "trigger": "release",
            "metadata": {
                "dist_git_branches": "main"
            }
        },
...
```

**Comment by mfocko** [comment]
only maintainers can push, right?

**Comment by johannbg** [comment]
Presumably permissions errors and the reason most likely being is because we lack this step "Packit user in Fedora is not a proven packager, so you need to grant packit user the ability to push." from the onboarding guide and the reason for us missing that step is because there is no explanation in how to do that in other words the onboarding guides lacks all the steps necessary on the fedora site.

**Comment by jpopelka** [comment]
> only maintainers can push, right?

yes, but propose-downstream should just create PRs, for which you don't need that, do you?

**Comment by mfocko** [comment]
> > only maintainers can push, right?
> 
> yes, but propose-downstream should just create PRs, for which you don't need that, do you?

from config:
```
...
    "create_pr": false,
...
```

**Comment by jpopelka** [comment]
ok, I was looking into the jobs list and didn't spot it above.

**Comment by jpopelka** [comment]
Ok, then it's just the incomplete documentation I think, i.e. packit/packit.dev#287
