### ISSUE TITLE
Packit can build and test 2 PRs in the same environment

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1108]
As an upstream developer, I can work on 2 PRs on 2 different projects in parallel (which use packit) and make builds and tests happen in the same environment.

(this is a big ask and needs a proper UX design backed by an implementation proposal)

asked from: leapp team, dnf team

**Comment by TomasTomecek** [comment]
Related research: https://github.com/packit/research/pull/155

**Comment by TomasTomecek** [comment]
We already have in place testing of 2 PRs in the same testing environment: https://packit.dev/docs/testing-farm/#running-tests-with-builds-from-another-pull-request

As for building: one can always create a custom Copr project and build all projects in it. Hence I'd propose to close this epic.

**Comment by lbarcziova** [comment]
For the reasons Tomas mentioned above, I am closing this now.
