### ISSUE TITLE
[FR] Support dynamic build deps

### ISSUE THREAD

**Issue by webknjaz** [packit/packit-service#1121]
Hi, I have a package that instead of hardcoding the build deps just extracts them via `rpmbuild -br` using `pyproject-rpm-macros`.

So in order for the project to be successfully built with packit, it'd need to perform something like this:
```sh
while :
do
  set +e
  rpmbuild -br rpm.spec
  [ "$?" -ne 11 ] && break
  set -e
  dnf builddep --assumeyes \
    $HOME/rpmbuild/SRPMS/<pkg_name>-<pkg_ver>-1.fc34.buildreqs.nosrc.rpm
done
```

A series of `rpmbuild -br` invocations exit with a return code 11 and produce a `buildreqs.nosrc` RPM. That artifact contains all the known-and-resolved dependencies so far. For as long as the return code is 11, that artifact may be used to install more deps and the next iteration may add more indirect deps. The last invocation of `rpmbuild -br` returns 0, meaning that all the deps have been resolved and are installed in the system. Instead of producing a new `buildreqs.nosrc` artifact, the last iteration creates a normal `src` RPM with all of the dynamically generated deps included.

**Comment by TomasTomecek** [comment]
Gotta say the `-br` workflow is a bit bizarre.

    the last iteration creates a normal src RPM with all of the dynamically generated deps included.

To me this workflow sounds too expensive: keep on installing dependencies just for sake of generating an SRPM? How many iterations do you usually go through? Could you please share with us an example for your package?

Nevertheless, we don't have an infrastructure right now to make this happen. None of our workers has root access so installing packages is not possible. I hope this would be resolved sometime in future. We have also done some research on building SRPMs in copr and this would be a great candidate to do such a thing.

**Comment by TomasTomecek** [comment]
> > To me this workflow sounds too expensive: keep on installing dependencies just for sake of generating an SRPM?
> 
> Well, if the deps are already pre-installed, it would produce an SRPM right away. But I guess this defeats the purpose of the automation.

We could preinstall them right now so it would work for you - this is what we are doing for other projects which require additional packages.

> > How many iterations do you usually go through?
> 
> I think it's 1-3.

That's decent - I feared for a bigger number, like 8 :D

**Comment by TomasTomecek** [comment]
Okay, there was a bit of misunderstanding here (on my side, sorry about that) how the `-br` feature of rpmbuild actually functions. Thanks to @praiskup and his mighty knowledge of rpm packaging, he pointed out that creating an SRPM does **not** require installing any dependencies. Producing a binary RPM does. This means we don't need to do any changes on packit's side to support this. Pavel also confirmed that handling a SRPM to COPR which utilizes dynamic BRs is just fine and copr (read [mock](https://github.com/rpm-software-management/mock)) can handle it just fine.

I verified this by cloning [ansible/pylibssh](https://github.com/ansible/pylibssh), creating sdist and running `rpmbuild -bs` to produce a SRPM without the need to install any (python) build dependencies. Doing a binary RPM build afterwards resulted in mock installing all the BRs correctly.

@webknjaz thank you so much for bringing this fascinating feature of rpmbuild to us. Let us know if we can help in any way.

**Comment by webknjaz** [comment]
@TomasTomecek could you check why this didn't work in the earlier invocations, then? Did Packit get updated meanwhile?

**Comment by webknjaz** [comment]
The failing PR is https://github.com/ansible/pylibssh/pull/227. I recall *I assumed* it was because of `-br` but maybe I'm wrong...

**Comment by TomasTomecek** [comment]
Now that we transitioned towards building SRPMs in Copr (VMs), this can be easily achieved since the environment is now a fully-featured VM and not a locked-down OpenShift pod.
