### ISSUE TITLE
Failure of Anaconda SRPM creation

### ISSUE THREAD

**Issue by jkonecny12** [packit/packit-service#1131]
Hi, I've got this failure on one PR today it doesn't look it's caused on our side. Could you please take look what went wrong here?

https://dashboard.packit.dev/results/srpm-builds/27159
PR: https://github.com/rhinstaller/anaconda/pull/3460

Thanks!

**Comment by lachmanfrantisek** [comment]
@jkonecny12 Thanks for creating the issue.

We've done some refactoring that as a result requires specfile to be present sooner than it used to be.

To fix this, you can move the action commands that generate the spec-file to the `post-upstream-clone` action.

We need to discuss with the team what we want to do here -- at least document this requirement.

**Comment by jkonecny12** [comment]
Thanks for advice. Issue is now fixed by https://github.com/rhinstaller/anaconda/pull/3465 .

**Comment by TomasTomecek** [comment]
I recall now: we bundled all those commands into a single action due to packit having time in path within the sandbox which caused random build failures - that is now fixed in packit so your change is actually correct way of using packit

let's close, thanks for solving this so quickly!
