### ISSUE TITLE
Status from COPR build is not reported correctly in the service dashboard and Github PR

### ISSUE THREAD

**Issue by thozza** [packit/packit-service#1142]
We have the Packit service enabled on [osbuild](https://github.com/osbuild/osbuild) repository. For [PR#696](https://github.com/osbuild/osbuild/pull/696), Packit reports that the COPR build on s390x (`rpm-build-fedora-rawhide-s390x`) is still pending, while it finished successfully almost a day ago.

The service dashboard reports the build as pending:
![Screenshot 2021-06-30 at 8 51 44](https://user-images.githubusercontent.com/3659736/123915576-f2f33b00-d980-11eb-8442-b8d91b649641.png)

However when I click on the [detail](https://dashboard.packit.dev/results/copr-builds/124866) of the build, it has "Build Finish Time" set. Also the [COPR Job](https://copr.fedorainfracloud.org/coprs/packit/osbuild-osbuild-696/build/2307507/) has all builds marked as finished.

**Comment by jpopelka** [comment]
Thanks Tome,
we somehow missed the event from COPR. It happens from time to time and we have #1005 to mitigate it.

**Comment by TomasTomecek** [comment]
As Jirka pointed out, this happens more often than it should - some network requests against github's api fail with 5xx, timeouts, 4xx, "No route to host", etc. Tome, I wouldn't be surprised if yours would fit that bucket as well.

I checked sentry and there were indeed many network issues around the time you created this issue.

It's true we want to solve this via #1005 for as many jobs and statuses as possible. We also have a global epic where we track UX issues like this: https://github.com/packit/packit-service/issues/1158

I'm going to keep this one open even though we can hardly do anything about it specifically - once #1005 is fixed, this should be resolved as well.

**Comment by mfocko** [comment]
@TomasTomecek it's really weird, cause as @thozza says, timestamp of «build finished» is set and it should be «row per target», so we got the the event and we definitely processed it, because of the timestamp being set…

checked prod DB, we got 232 Copr builds that are `pending`, but timestamp of finishing build is set…

**Comment by TomasTomecek** [comment]
This should be resolved now: we now have a mechanism to consistently "babysit" builds and continuously check (until they finish) their status. Please let us know if this doesn't work as expected for you.
