### ISSUE TITLE
Network enabled/disabled not consistent

### ISSUE THREAD

**Issue by clebergnu** [packit/packit-service#1152]
On https://github.com/avocado-framework/avocado/pull/4764 , I was expecting the network behavior to be consistent across build chroots.  On that specific PR, there's one build failure (which is actually correct) and two builds that succeeded (but shouldn't, because they attempt to download requirements via PIP).

I did not find a way to control networking during the builds, and even so, found them to not be consistent across chroots.

**Comment by mfocko** [comment]
Hi, there is an open issue for configuring network access for COPR builds on our side (related issue: #1031), but we are not aware of any inconsistencies between chroots.

I looked through the builds from the linked PR and they all seem to have the network access enabled (from logs):
```
Warning: Permanently added '2620:52:3:1:dead:beef:cafe:c148' (ECDSA) to the list of known hosts.
Running: /usr/bin/copr-rpmbuild --verbose --drop-resultdir --build-id 2316307 --chroot fedora-rawhide-x86_64 --detached
Version: 0.52
Task:
{'appstream': True,
 'background': False,
 'build_id': 2316307,
 'buildroot_pkgs': [],
 'chroot': 'fedora-rawhide-x86_64',
 'enable_net': True,
```
(applies to both successful builds and the failed one)

**Comment by clebergnu** [comment]
@mfocko you are right, network is enabled consistently on all of them.  I mixed two different issues happening on the rawhide builds.

On the other hand, I honestly assumed that the default behavior on packit builds would be similar to mock/koji and **not** have networking enabled by default.

Anyway, I've made this same point in #1031, so I'm closing this issue.  Thanks!
