### ISSUE TITLE
Allowlisting projects

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1160]
Refactor internal script for allowlisting projects, reflect changes made to the allowlisting:

1. URL without protocol, e.g. `github.com/packit` or `github.com/packit/packit.git`
2. highlight specific use-case for URL provided to the script, examples follow
   - if given URL without `.git` suffix, make sure it is intended to allowlist *namespace*
   - if given URL with `.git` suffix, make sure it is intended to allowlist *repository*
3. optionally provide stripping of protocol, if provided, i.e. if given `https://github.com/packit`, automatically transform it to `github.com/packit`
4. in case of `waiting` provide interactive interface that
   - allows choosing specific item from waiting list
   - allows to choose between allowlisting repository or namespace

can be done interactively, since the current implementation itself uses `click`

**Comment by TomasTomecek** [comment]
please make sure that people who haven't done allowlisting for some time would have a good experience and the script would verify the inputs are sane
