### ISSUE TITLE
Support for {centos,oracle}-{7,8} distros for internal tft

### ISSUE THREAD

**Issue by ZhukovGreen** [packit/packit-service#1164]
Because packit sends all the tests to be executed for each built rpm, we adjusting the relevancy of the test with help of distro context:
```diff
summary: kmods tests
tag+:
  - centos7
  - centos8
  - oracle7
  - oracle8
  - inhibit-if-kmods-is-not-supported
+ adjust:
+  enabled: false
+  when: >
+   distro != centos-7 and
+   distro != centos-8 and
+   distro != oracle-7 and
+   distro != oracle-8
test: |
  pytest -svv
```
I'd like to ensure that packit properly maps these distros to the right tft composes for the internal tft.

expected mapping is:
```python
PACKIT_DISTRO_2_INTERNAL_TFT_COMPOSES = {
    "centos-7": "CentOS-7",
    "centos-8": "CentOS-8",
    "oracle-7": "Oracle-Linux-7.9",
    "oracle-8": "Oracle-Linux-8.3",
}
```

**Comment by lachmanfrantisek** [comment]
@thrix Can you please provide the correct compose names for `Oracle`?

**Comment by ZhukovGreen** [comment]
currently only Oracle-Linux-7 and Oracle-Linux-8.3 are available, so I updated the ticket descritption

**Comment by TomasTomecek** [comment]
Is this only about testing? or should copr provide oraclelinux as a build env as well?

I can see mock has configs for oracle linux:
```
/etc/mock/oraclelinux-7-aarch64.cfg  /etc/mock/oraclelinux-7-x86_64.cfg  /etc/mock/oraclelinux-8-aarch64.cfg  /etc/mock/oraclelinux-8-x86_64.cfg
```

**Comment by ZhukovGreen** [comment]
@TomasTomecek no, just testing. tft should provision oracle linux. We're using the same rpm for centos-X and oracle-X

**Comment by lachmanfrantisek** [comment]
> @TomasTomecek no, just testing. tft should provision oracle linux. We're using the same rpm for centos-X and oracle-X

But this is not easy to do then. When reacting on the finished Copr build, we map one Copr chroot to one TF chroot, but you want to trigger two -- how do we know if for `centos-7` we need to run `centos-7` or both `centos-7` and `oracle-7`? One option is to set it in the packit config, but this will break some internal flows like checking if we have a build for this chroot. We will need to manually add a condition with `oracle` to multiple places.

If possible, I would try to use `oracle` in Copr. This will easy the work for us a lot.

**Comment by ZhukovGreen** [comment]
@bocekm Michal, what do you think? Is it possible to have a dedicated chroot or Oracle Linux?

**Comment by bocekm** [comment]
In the Fedora Copr, we are currently using the epel 6/7/8 chroots. There's no chroot for CentOS Linux or Oracle Linux.

**Comment by lachmanfrantisek** [comment]
We've discussed that we would try to ask for adding the missing chroots to Copr and if it is not possible, we can have a configuration for mapping allowing to set multiple composes for one chroot.

**Comment by praiskup** [comment]
> we can have a configuration for mapping allowing to set multiple composes for one chroot.

Long term, it would be useful anyways - there are other RHEL forks we could use this feature for
(instead of re-building the very same package against all the forks over again).

Is this anyhow complicated for implementing?  We will enable Oracle Linux in Copr this week,
though we'd like to admit that it is rather a temporary solution to help the team @oamg team
when doing CI - so there will be no surprises once we disabled them in the future.

**Comment by TomasTomecek** [comment]
@lachmanfrantisek told me today it was already discussed last week, what you mention - @praiskup , that TF and packit would be capable of matching builds and tests across different targets (chroots).

**Comment by lachmanfrantisek** [comment]
The long-term solution is already tracked in #1123 and the mapping of the Oracle chroots (this issue) is being added in #1186
