### ISSUE TITLE
koji stg builds: dashboard info is half empty and commit status is not updated

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1168]
2 issues:

1. The link to logs in https://dashboard.stg.packit.dev/results/koji-builds/1 is non-existent and build start/end times are empty

2. Even though the build above is finished, the commit status still says pending (this works in prod)

Does it mean we're just not catching some message or even the message is not sent to the message bus?

**Comment by lbarcziova** [comment]
> Does it mean we're just not catching some message or even the message is not sent to the message bus?

Yes, we should specify fedmsg topic `org.fedoraproject.stg.buildsys.task.state.change` instead of the `org.fedoraproject.prod.buildsys.task.state.change` in the fedora-messaging configuration file for stg.

**Comment by TomasTomecek** [comment]
can't see any stg messages in datagrepper :/

https://pagure.io/fedora-infrastructure/issue/10116
