### ISSUE TITLE
Incorrect Copr build after retriggering tests via `/packit test`

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1174]
Steps to reproduce:
1. Run pipeline for PR
2. Have one failing Copr build for chroot X
3. Retrigger tests via `/packit test`

Outcome:
Tests are run from the latest successful Copr build, even if the build isn't from the same PR.

Expected outcome:
If chroot has a failing Copr build, rerun the build.

**Comment by TomasTomecek** [comment]
whaaaaat, this is nasty! thanks for tracking this down

**Comment by mfocko** [comment]
aaaa, this looks like another refactor, cause the logic from building one chroot leaks to method for building all… Eh, it would still require refactor, if we want to support re-triggering specific builds/tests.

ok, it's not leaking, Copr gets triggered via one call…

https://github.com/packit/packit-service/blob/2fd5e3496ef0abe780ce76af947337471d10f618/packit_service/worker/build/copr_build.py#L282

I guess I will have a look, since I _deep dived_

**Comment by lbarcziova** [comment]
I tried to reproduce this and the tests were run from the latest Copr build, but even when it was unsuccessful, so we later got an error response from Testing farm, [example](https://github.com/packit/hello-world/pull/426/checks?check_run_id=3238411179). This is improved in #1188.
