### ISSUE TITLE
Do not run jobs that can touch the local repo from the short-running worker

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1184]
Benefit: We can make the `short-running` worker more lightweight and does not need to attach the repository-cache volume to it.

The task is:
* [ ] check the jobs attached to the `short-running` queue and move out the ones that touch the git repo or can run any action in the sandbox.
* [ ] document this distinction in the deployment or in the packit-service code.

Optionally: How busy is the current short-running worker? What about scaling it up and/or reducing the resource limits for it.

**Comment by lbarcziova** [comment]
Just some notes (@lachmanfrantisek correct me please if I got something wrong):
- sandcastle is used for executing code in actions, actions should be used only for `propose-downstream` and creating SRPM, so the tasks: copr_build, koji_build, propose_downstream
- worker repository cache is used whenever we clone the repo (=using LocalProject), so the tasks which do some operations with local repo, these should be: copr_build, koji_build, propose_downstream, distgit_commit
- but from checking the worker logs, I found `Cloning repo ...  -> /sandcastle using repository cache at /repository-cache` also in copr_build_end task (even if it probably isn't really needed), the BaseBuildJobHelper has the local_project property so I need to check its usages
- maybe it would be safer to only remove the pvc for sandcastle which is used by short-running worker for the beginning?

**Comment by lachmanfrantisek** [comment]
> * sandcastle is used for executing code in actions, actions should be used only for `propose-downstream` and creating SRPM, so the tasks: copr_build, koji_build, propose_downstream

:+1: I would say so

> * worker repository cache is used whenever we clone the repo (=using LocalProject), the tasks which I think really do some operations with local repo, should be: copr_build, koji_build, propose_downstream, distgit_commit

:+1:

> * but from checking the worker logs, I found `Cloning repo ...  -> /sandcastle using repository cache at /repository-cache` also in copr_build_end task (even if it probably isn't really needed) and also some other tasks, since the BaseBuildJobHelper (which is used in lot of tasks) has the `api` property and when this is called, the `local_project` [is passed and initialized ](https://github.com/packit/packit-service/blob/14e7a86977b8298df2583434e939ea1cde922d2d/packit_service/worker/build/build_helper.py#L134). It doesn't make sense to send all these tasks to long-running queue since most of them don't really need the cloned repo, this could be maybe somehow refactored so that the `local_project` is called really only if needed.

Probably some lazy evaluation. It would be nice to avoid this. I agree that it does not make sense to clone in those tasks. We can use `offline=False` or `refresh=False` arguments. or as you wrote, evaluate `local_project` only when needed.

> * maybe it would be safer and make more sense to move only propose_downstream task and remove only the pvc for sandcastle which is used by short-running worker for the beginning?

I am not sure if I get you right. We want to:
* avoid evaluating cloning and actions in short-running worker
* remove the PVC for cache from deployment
  * the ones in the worker namespace that are attached to the worker (OK, is this what do you want to postpone? So, solve the cloning in workers later?)
  https://github.com/packit/deployment/blob/98323d82323e66d9192c78dcecfbad3b97e8afb9/openshift/packit-worker.yml.j2#L50-L59 (Some condition/variable needed to make this optional.)
  * the ones in the sandcastle namespace that are attached to the sandcastle pods
  https://github.com/packit/deployment/blob/98323d82323e66d9192c78dcecfbad3b97e8afb9/playbooks/deploy.yml#L189-L199

**Comment by lbarcziova** [comment]
>I am not sure if I get you right. We want to:
>* avoid evaluating cloning and actions in short-running worker
>* remove the PVC for cache from deployment
>    * the ones in the worker namespace that are attached to the worker (OK, is this what do you want to postpone? So, solve the cloning in workers later?)
  https://github.com/packit/deployment/blob/98323d82323e66d9192c78dcecfbad3b97e8afb9/openshift/packit-worker.yml.j2#L50-L59 (Some condition/variable needed to make this optional.)
 >   * the ones in the sandcastle namespace that are attached to the sandcastle pods
  https://github.com/packit/deployment/blob/98323d82323e66d9192c78dcecfbad3b97e8afb9/playbooks/deploy.yml#L189-L199

Yes, this is true. My point was, that we can do this in steps since the 1. is trivial and we can get rid of at least one PVC fast but 2. may take more time:
1.  move only propose-downstream task and remove PVC in the sandcastle namespace.
2.  find out whether/how it is possible to make attaching PVCs to workers optional, implement mentioned laziness, check whether some of the other tasks then really don't need cloning, move distgit_commit and if found any other task which clones repos and after that implement not attaching PVC to short-running workers

**Comment by lachmanfrantisek** [comment]
I agree, but I still think that the second point is not so hard to do..;)

Maybe just a note for the first one -- we need to avoid mounting the sandcastle volumes:
* somehow in the packit-service code
* do not set the env.var. value and check in the code for emptiness
* have a different config for short running workers (do not add the part about mounting the volumes)

**Comment by lachmanfrantisek** [comment]
@lbarcziova What's actually missing here? Isn't it already solved?

**Comment by lbarcziova** [comment]
Yes, all of the work should be done now, closing.
