### ISSUE TITLE
Link pipelines/jobs dashboard view in the check run description

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1214]
Especially for the `The task was accepted.` state, it might be worth linking this page so users can check the current state of the service.

Ideally, add some real-time statistics about the queue to the dashboard/status page, but that's a different story.

**Comment by csomh** [comment]
This would be extremely important as without this it's not really possible to find out what happened with tasks, which have "The task was accepted." state but are stuck in that state.
