### ISSUE TITLE
Mismatch between application code and executed tests

### ISSUE THREAD

**Issue by psss** [packit/packit-service#1224]
After the recent change in packit/packit/pull/1344 (merge pull request into the target branch before building the srpm) there is a mismatch between the features built in the package and tests executed in the testing farm. This appeared in the recent pull request here:

 * https://github.com/psss/tmt/pull/892

A new feature introduced in the default branch causes tests to unexpectedly fail because test code has been modified in `master` as well. Packit should request Testing Farm to execute tests from the corresponding branch instead.

**Comment by psss** [comment]
@FrNecas, @thrix, fyi.

**Comment by thrix** [comment]
oh well, if the merged to target branch is not exposed in the repo (and connot be), we will need to implement this merging on our side. I do not like it much. Seems we have a mtg today, let's discuss there.

**Comment by TomasTomecek** [comment]
Let us know if we should participate in that discussion.

I'd say this race condition is gonna be hard to solve properly since the merge would need to happen twice: once on our side and the second time on your.

Should we also specify commit SHA of the contributor's branch?

**Comment by psss** [comment]
Using the `refs/pull/892/merge` is not an option here?

**Comment by mfocko** [comment]
> Using the `refs/pull/892/merge` is not an option here?

If you mean the test merge commit that GitHub or GitLab (on request) provide, the problem with them is that they're quite unpredictable (from outdated to having already different revisions that are problematic to track), by local merging when building SRPM we log the heads of branches we merge, so it's easier to both debug and track what the SRPM contains.

**Comment by lachmanfrantisek** [comment]
We just agreed on the following:
* We will add support to make the merge configurable: #1228 
* Testing Farm will implement the support on their side.

**Comment by mfocko** [comment]
We provide `PACKIT_TARGET_SHA` to the testing farm, should be deployed to prod on Tuesday.

**Comment by TomasTomecek** [comment]
shall we close this one?

**Comment by mfocko** [comment]
not done on TF side afaik

**Comment by thrix** [comment]
indeed :( https://issues.redhat.com/browse/TFT-756 :(

**Comment by thrix** [comment]
@TomasTomecek @mfocko did we discuss why for Testing Farm it would be not enough to use `refs/pull/<number>/merge` ? That might would be so much cleaner for us ....

**Comment by mfocko** [comment]
@thrix mainly inconsistency (IIRC cockpit team was trying to use GitHub merges too, see discussion packit/packit-service#245).

Till the job gets to Testing Farm I could push to GitHub, which would make you run tests with different commit than the RPM is built from. Overall:

1. GitHub merges automatically, BUT can be delayed
2. GitLab merges on request, again, waiting in queue
3. Pagure doesn't support it at all

Providing you with commit SHA allows us to:
- offload specifics of git forge from Testing Farm
- skip waiting/(requesting and waiting) for merge
- be 100% sure about sources used for build and tests

**Comment by psss** [comment]
Yes, we still need this.

**Comment by mfocko** [comment]
Note to @mfocko, there was a change in the TFT API to support the merge SHA being specified explicitly in the API

The change has not been reflected on our side… my bad…

Related to MR https://gitlab.com/testing-farm/api/-/merge_requests/30/diffs

**Comment by psss** [comment]
I see the pull request has been merged, so on the `packit` side everything should be ready?

**Comment by lachmanfrantisek** [comment]
🎉 The Testing Farm newly supports that 🎉

**Comment by mfocko** [comment]
@mfocko to check that it really works :D

**Comment by mfocko** [comment]
If there are no issues, it will be deployed to production on Tuesday's morning
