### ISSUE TITLE
Use fasjson for automatic allowlisting 

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1257]
FAS2 (which we use [here](https://github.com/packit/packit-service/blob/f5f321f2a663bd797868d0ef17559309c9c7816c/packit_service/worker/allowlist.py#L8)) [is being retired](https://pagure.io/fedora-infrastructure/issue/10254) and doesn't provide up to date info about users , from what I read we can use [fasjson client](https://fasjson-client.readthedocs.io/en/latest/migration.html#people). 

TODO:
- [ ] use [fasjson client](https://fasjson-client.readthedocs.io/en/latest/usage.html) for the code of checking the FAS account
- [ ] implement the automatic check of Github/Gitlab username from the FAS account via fasjson API and check if is the same as the one who triggered the installation
- [ ] if the check is successful, store the FAS account in the allowlist in DB (check how it was done in the past in the git histoy) and don't create issue in notifications repo

**Comment by lachmanfrantisek** [comment]
Relates to #997

**Comment by csomh** [comment]
FAS2 seems to have stopped working for good.
