### ISSUE TITLE
Improve generating migration scripts for the DB

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1277]
The [documentation](https://github.com/packit/packit-service/blob/f49f7de97a9db27f194faa080e86ef40ce11b64c/CONTRIBUTING.md?plain=1#L98) to generate migrations with `alembic` has several issues:

- [x] `podman-compose up` does not support bringing up only the selected services.
- [x] The service pod would fail to start with UID `123123`, which is currently set in `docker-compose.yaml`.
- [x] `alembic` is unable to write the migration file as the `alembic/versions` directory is owned by `root`, while the `service` container is run with a non-root user (Apache requires to be run as a non-root user).
- [x] The `podman cp` command shouldn't be necessary if the `alembic` directory is mounted as a volume.

Fix things, so that it's easy to generate migration files using `docker-compose`, without the need to install additional tooling locally.
A new make-target called `make migration` would be the best :sparkles: :sparkles: :sparkles:
Update the docs accordingly.

**Comment by lachmanfrantisek** [comment]
@csomh Is this issue still valid? I see, we have made some changes to this recently.

**Comment by csomh** [comment]
I'm not sure, I haven't tried it lately. I would say this is still valid: there is no `make migration` and UIDs in `docker-compose.yaml` are still `123123`.

**Comment by csomh** [comment]
And @nikromen just mentioned on stand-up that it's not working as described :smiley:

**Comment by jpopelka** [comment]
Do we still need to support podman-compose when you can [run docker-compose with podman](https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/)? (as already mentioned in [CONTRIBUTING.md](https://github.com/packit/packit-service/blob/main/CONTRIBUTING.md#database))

> UIDs in `docker-compose.yaml` are still `123123`

It AFAIK works with podman, that's why I didn't remove them in #1331

**Comment by jpopelka** [comment]
> ERROR: for redis  Cannot start service redis: lchown /home/

oh, now I remember seeing this as well and I've been running `sudo docker-compose` since then.
Your #1360 looks good anyway, acked, thanks!
I just need to read the article again to see how to run it with rootless podman since I'm getting `'Permission denied'`.

**Comment by jpopelka** [comment]
> Please let me know if it's also working for you or not.

Works OK with rootless podman. Thanks again.

I've updated the description a bit so that it reflects the current status.

**Comment by nikromen** [comment]
so is this issue still valid? since we have make migration #1386

**Comment by csomh** [comment]
Let me check.

**Comment by csomh** [comment]
Yep, `make migrate-db` worked like a charm. Thank you @nikromen, @majamassarini, @jpopelka for working on this! :medal_sports:
