### ISSUE TITLE
Update of chroots of Copr Project owned by Packit rises an error

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1283]
If someone creates the PR with a set of chroots and change it later on, there is a ~~permission~~ problem.

See this example: https://github.com/RedHat-SP-Security/keylime-tests/pull/13#issuecomment-967206007

**Comment by mfocko** [comment]
It's not, the issue you cannot update targets while there is a running build (for that target you want to remove? ← might not be true)

**Comment by lachmanfrantisek** [comment]
@mfocko what can we do here?

* Check for the real cause (#1118 ) and provide a better comment.
* Retrigger or suggest to retrigger once the build is finished. Or, can we cancel the build?

**Comment by mfocko** [comment]
> • Retrigger or suggest to retrigger once the build is finished. Or, can we cancel the build?

that's probably related to an even older issue #5

**Comment by lachmanfrantisek** [comment]
So, let's start with getting a better comment. The situation is not so common and asking for some human interaction looks ok to me in this case.

**Comment by TomasTomecek** [comment]
We now produce a better error message: https://github.com/packit/packit-service/pull/1397

Since this is a limitation of Copr, I'm not sure if there is anything we can do our side. We could possibly cancel the build or work with Copr to implement this on their side.
