### ISSUE TITLE
Provide cleaner output to user when `/packit` command is triggered without config file

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1288]
If user will trigger `/packit` command without config file in repo, this will cause error msg to user. 
Current example:

Failed to load packit config file:
```
No config file found in packit/hello-world on ref '0eb6b2b578c2d6d9be87f9a022eba1a9bcb74dca'
```
For more info, please check out the documentation: https://packit.dev/docs/packit-service or contact us - [Packit team](https://github.com/orgs/packit/teams/the-packit-team)

But as we discussed with @lachmanfrantisek [here](https://github.com/packit/hello-world/pull/545#issuecomment-974007092) the format is a bit messy.
So expected output may look like:

No config file for packit (e.g. `packit.yaml`) found in `packit/hello-world` on commit [`0eb6b2b`](https://github.com/packit/hello-world/commit/0eb6b2b578c2d6d9be87f9a022eba1a9bcb74dca)

For more info, please check out the documentation: https://packit.dev/docs/packit-service or contact us - [Packit team](https://github.com/orgs/packit/teams/the-packit-team)<br/><br/>
Tasks:
- [ ] differentiate between bad config and missing config (print raw text only when bad config occurs to make the commit clickable)
- [ ] update current message about failing on missing config file

**Comment by lachmanfrantisek** [comment]
If we have a separate message, we can even remove the first sentence (`Failed to load packit  config file:`) to make it shorter.
