### ISSUE TITLE
Save the progress of propose-downstream in database and make it available via API

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1292]
To be able to show the progress of the `propose-downstream` job, we need to save it to the database and provide it via service API to show it on our dashboard (packit/dashboard#155).

Tasks:
- [ ] Suggest a change of the database schema (with the info we want to save), discuss with the team, update models and prepare migration.
- [ ] Save the progress during the process of `propose-downstream` (there can be multiple states we want to track).
- [ ] Provide an API endpoint for the `propose-downstream` jobs.

**Comment by nikromen** [comment]
How dare you stale-bot!
