### ISSUE TITLE
`babysit_pending_copr_builds` not working as expected

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1294]
Every hour `babysit_pending_copr_builds` is periodically executed, it ends up with an error: `AttributeError: 'NoneType' object has no attribute 'project'`
It crashes because [trigger_db is None](https://github.com/packit/packit-service/blob/main/packit_service/worker/events/copr.py#L38).
The issue is that [`CoprBuildModel.runs`](https://github.com/packit/packit-service/blob/main/packit_service/models.py#L196) is also `None` but I can't figure out why.

**Comment by nikromen** [comment]
This error is no more occuring. It seems like the problem wasn't on our side.
Closing

**Comment by TomasTomecek** [comment]
Now production deployment happened on Tue morning which fixed the problem :)
