### ISSUE TITLE
Inform Fedora users about koji builds when new commits land in a dist-git repo

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1310]
I just merged my dist-git PRs which packit created. As a Fedora packager, I had to open builds in koji for my package to see if packit started respective builds. I'd like to be informed that the builds were started (ideally in respective PRs).

**Comment by lachmanfrantisek** [comment]
To be precise, dist-git shows in the UI:
e.g.: https://src.fedoraproject.org/rpms/packit/pull-request/253
![Screenshot from 2021-12-08 17-08-22](https://user-images.githubusercontent.com/20214043/145242419-b9ed36d6-c842-4dfe-a416-763c4eef3af8.png)

But it looks like the maintainers are not notified about the build -- that's what we need to do.

**Comment by TomasTomecek** [comment]
LGTM, let's just document this
