### ISSUE TITLE
Conflicting packages & the Testing Farm

### ISSUE THREAD

**Issue by mrc0mmand** [packit/packit-service#1323]
Hey!

I'm here, again, with the good ol' issue. Given this has been discussed in _many_ places, I completely lost track of the current state and cannot find any relevant (and open) issues, thus apologies in advance if this issue is misfiled.

Long story short, we (systemd) still can't use Packit + Testing Farm, because the resulting Copr build contains conflicting packages (systemd vs systemd-standalone-{tmpfiles,sysusers}), and the install task tries to install all packages from the build. After some long back & forth discussion in https://pagure.io/fedora-ci/general/issue/184 whether the issue is in Packit or in Testing Farm, it suddenly died and I don't know if the issue has been resolved or there's still some work to do. Given that the test job still fails - https://github.com/systemd-ci-incubator/systemd/pull/11 - I'd say the latter.

Now there's been some work in Packit (https://github.com/packit/packit-service/issues/642, https://github.com/packit/packit-service/pull/1212) regarding this stuff, but as mentioned in the ticket, it doesn't seem to be enough?

Recently, there's been an interesting discussion on the Fedora CI list (https://lists.fedorahosted.org/archives/list/ci@lists.fedoraproject.org/thread/BXFWLOFR4A4WK55ZIN6ORMNMWIUITMBU/) which reminded me of this issue in the first place (and which suggests there might be other projects hitting the same issue, even though not strictly Packit related).

**Comment by lachmanfrantisek** [comment]
@mrc0mmand Thanks for taking a look into this and bringing this up!

I've synced with @thrix and he has created an issue for that: https://issues.redhat.com/browse/TFT-977

Since we send the needed info, I hope we don't need to do anything on Packit's side and need to get this fix in the Testing Farm.

I am going to close this issue but we can reopen it or create a new one if the solution will not work and some enhancement will be needed on our side.

**Comment by thrix** [comment]
Yes, this is a leftover, we should support that, tracking in this downstream issue: TFT-977, set for this quarter.

As for the linked issue, that is something else: TFT-978 - that way the CI system can tell Testing Farm to no install certain builds from a bodhi update (now we install all)

**Comment by lachmanfrantisek** [comment]
@thrix, just to clarify this:
* Sending explicit NVRs (as we do) should be ok for @mrc0mmand and will be fixed in `TFT-977`.
* Since we send an explicit list of NVRs, for us the `TFT-978` does not make sense to utilise or make configurable. Or can this be anyhow useful?
