### ISSUE TITLE
Database: project reference model

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1328]
Follow-up for: packit/research#128

The current situation with project/trigger/commit-related models:

* Project for trigger not effective to get for multiple entries.
* `JobTriggerModel` is more a git reference than a trigger.
* Commit is spread across the models (in build/test models and release).

Let's transform `JobTriggerModel` into something better-named and better-connected. We would like to use it as a project/git reference.

* [x] @lachmanfrantisek promise to explain this task and showcase it via the diagram
* [x] Pick a better name for `JobTriggerModel` (something like `ProjectReference` or `CommitModel`).
* [x] Add a new column for commit hash (e.g. `commit`/`commit_hash`/ `commit_sha`).
* [ ] Connect the model directly to the  `ProjectModel`.  Each commit occurrence (e.g. pr x branch push) will have a different model -- so, no change in the behaviour...;)
  * [ ] With this, we can simplify a lot of queries that try to get a project model throught the pr/branch/release/issue model. Either fix it (if you think it's simple) or create a follow-up card to do it. 
* [x] Create migration steps that add the newly introduced connections/values also for the already present data.
* [x] Regenerate the database diagram

**Comment by majamassarini** [comment]
I re-open it, since just one step has been done.
