### ISSUE TITLE
Move out the webhook API

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1344]
The task is to move out the API responsible for incoming events from the service code/image so it behaves like our other listeners.

This is to improve the overall service architecture and also to make the service API (used for dashboard) and webhook API (used for events received from GitHub/GitLab) independent (e.g. when speaking about resources).

*This is an outcome of the HackFest we had last week.*

**Comment by TomasTomecek** [comment]
This made sense when the webhook API was mega-important and the REST API wasn't used that much.

That's no longer the case: the dashboard and the webhook API now have almost the same importance.

Let's not complicate our deployment setup for almost no benefit.
