### ISSUE TITLE
Suggest solution when propose-downstream fail on non-existent branch

### ISSUE THREAD

**Issue by johannbg** [packit/packit-service#1361]
***Edited by @lachmanfrantisek***:

User hits a `We were unable to push to dist-git: [remote rejected] (pre-receive hook declined)` error for propose-downstream when the dist-git branch doesn't exist.
So the solution is to check if that branch exists and if it's not, provide a meaningful error saying that one needs to request it with Fedora rel-eng.''

Example of the issue created because of this:
https://github.com/dracutdevs/dracut/issues/1713

***Original description***

Seriously can I get something to work with instead of a fracking bot that creates an issue in which it proposes to run '/packit propose-downstream' then gives me a thumbs up when in reality packit fails again o_O and that fracking bot creates a new issue proposing the exact same thing o_O

What's fubar in the process here upstream,packit, RH infra what? What needs to be done to actually resolve this issue???

**Comment by TomasTomecek** [comment]
So the solution is to check if that branch exists and if it's not, provide a meaningful error saying that one needs to request it with Fedora rel-eng?

**Comment by johannbg** [comment]
Well to me these are four seperated issues to look at being solved. 

First of all the bot should not be giving thumbs up when given commands  ( /packit propose-downstream ) I interpreted that as the command was successful but presumably you implemented that as command recieved by the bot.

Secondly the bot should not be creating new issue when being unsuccessful for the second ( or more ) time but comment that it was unsuccessful again on the existing issue he had already created. 

Thirdly the bot should not be proposing the exact same action that had already failed ( now twice ) again

Forthly the message provide by the bot should always be something actionanable by upstream not some cryptic error message that literaly means nothing to upstreams.

**Comment by johannbg** [comment]
> So the solution is to check if that branch exists and if it's not, provide a meaningful error saying that one needs to request it with Fedora rel-eng?

Have the bot create the issue and request it since packit is already adding enough to the cost of developement to upstreams for literally no benefits.

Take this issue here for example, It costs an hour ( including the cost of distraction ) for upstreams to look at any issues related to packit, it has costed the packit team 2 hours ( one from each team member assuming that only two that commented here looked at this issue ), it will cost me more to file additional issue with fedora releng, and releng atleast one hour for someone there to look at this totaling ca 5 hours just to solve this failure. 

That's expensive on people paid ( for example one hour of my time costs 170 euros assuming everyone would get paid the same, it amounts to 850 euros ) or free time of their lifetime ( which people will never get back ). 

packit needs to come at zero cost to upstream since it's already a loose/win solution ( all the benefits of using packit lies with Redhat, there is no win for upstream using it )

**Comment by johannbg** [comment]
> You still get feedback from the downstream distribution for changes you are working on, I think that's beneficial for you. Better than getting issues reported or questions asked after a release was already done.

You need to clarify how that feedback is supposed to be conveyed and how it's is conveyed in better manner since the feedback upstream gets from downstream distribution is conveyed through issue trackers, PR, and dialogs on mailinglists or something more 21 century, like discussions on github.  

Using packit does not change that and even if it did, it would only change that for a *single* distribution out of what ca 500. 

Now what packit can be used for is to elimate the role of the downstream package maintainer ( thou probably not intented for that purpose ) by moving that role and responsibility entirely upstream and have it managed there and thus free some time for the upstream RH employee that's been enslaved to maintain the component in the RHEL ecosystem, to do some other more valuable things than playing downstream distribution package maintainer and the bureaucracy and the time wasting politics that role is subjected to.

**Comment by TomasTomecek** [comment]
> Now what packit can be used for is to elimate the role of the downstream package maintainer

That would be awesome to achieve, we actually have goals for this year to streamline downstream packaging a lot.

On the other hand, it can never be done 100%. Every downstream distribution packaging is immensely complex. I hope that one day we could start generating downstream packages from upstream and lift the responsibility completely from upstream and downstream maintainers. Folks already work on this: [here](http://frostyx.cz/posts/rebuilding-the-entire-rubygems-in-copr) and [here](https://pretalx.com/packagingcon-2021/talk/K7LDFB/).

Jóhann, thank you for your honest feedback. It's a long way to go for packaging to become easy, we can get there :)

**Comment by johannbg** [comment]
> On the other hand, it can never be done 100%. Every downstream distribution packaging is immensely complex

s/complex/political/

For fedora the backend/rawhide would need to be stabilized and RH employees stop poking the component dowstream, usually the pokes are justified ( backports ) after things are merged upstream which arguably is our fault for not releasing fast enough ( which we could address upstream by releasing on monthly bases or something ) but in other cases it seemingly is being poked for no good reason ( some misunderstanding resulting from issues in bz.rh ).

For upstream to maintain the component upstream it's quite clear for that to work it means handsoff from downstream and that might prove quite difficult for people to adapt to such workflow.

**Comment by johannbg** [comment]
btw the :+1: should be change to a :rocket: which people should interpet as a "launch" that is if using a simple text that simply says "running" is not better.

**Comment by johannbg** [comment]
Hmm we are talking about the bot recieving the command and execute it and currently it gives a thumbs up when doing so, then it opens a new issue which literally makes no sense. Not sure :eyes: fit that purpose. How about just using a text "executing" that should be clear to everyone what that means.

**Comment by lachmanfrantisek** [comment]
I'll try to explain that a bit -- currently, when we get an event about commit command (e.g. `/packit build`, `/packit propose-downstream`, `/packit retest-failed`, etc.), we put a reaction on that comment to give a user info that we received that command and will work on it (so, user can use the command and it is a valid command).

The other info about the state should be covered by the commit status (for PRs, branch pushes, ...)

With propose-downstream, we are hitting a different problem -- the progress is not visible. We have an epic (https://github.com/packit/packit-service/issues/1082) to help with this and we have already started working on this, specifically, we are speaking about:
* #1292 (#1337)
* packit/dashboard#155
* #1293 
* and maybe #1348

So you can see some improvements for `propose-downstream` job in the following weeks.

And regarding the issue duplicates, that's a bug I am sorry about. We should check for the duplicates so we might have a problem in that code.

**Comment by johannbg** [comment]
> I'll try to explain that a bit -- currently, when we get an event about commit command (e.g. `/packit build`, `/packit propose-downstream`, `/packit retest-failed`, etc.), we put a reaction on that comment to give a user info that we received that command and will work on it (so, user can use the command and it is a valid command).

Yeah I had already figured that much but I perceive thumbs up as command successful not command received hence my proposal to change that to :rocket: 

The only feedback upstream should be receiving from the bot is. `Command recieved` :rocket: , followed by either `Command successful` :+1:  or `command failed` :-1: , there does not need to be any info following a success, just a thumbs up however if the command fails, the failure message needs to contain an *actionable* message for upstream, any other failure message is just noise since it contains non actionable item for upstream thus could easily be replaced with a picture of Fedora/CentOS/RH and :sob: and an issue created with the relevant downstream party automatically.

**Comment by lachmanfrantisek** [comment]
> Well to me these are four seperated issues to look at being solved.

Exactly. Let's resolve the issues one by one:

> First of all the bot should not be giving thumbs up when given commands ( /packit propose-downstream ) I interpreted that as the command was successful but presumably you implemented that as command recieved by the bot.

I hope the :eyes: can help a bit here. (We need to be consistent across all the jobs and it's nice on reactions that it doesn't provide any notification. Sorry, if it isn't what you originally wanted but at least better I think.) I consider this one as fixed.

> Secondly the bot should not be creating new issue when being unsuccessful for the second ( or more ) time but comment that it was unsuccessful again on the existing issue he had already created.

I've created a separate issue for this: #1380

> Thirdly the bot should not be proposing the exact same action that had already failed ( now twice ) again

Since the actions aren't run in an isolated world and are interacting with various other systems I don't think we can be sure it will end with the same result. Two examples:
* Our projects use PyPI to get sources for our Fedora packages. When there is a delay/problem with PyPI release, the propose-downstream fails. But we can fix the PyPI release (wait, do it manually, etc.) and rerun the job. And the second run will proceed.
* Your use-case. The non-existent branch can be fixed elsewhere. And once the new branch is created, the rerun will be successful.

I don't speak about error messages, etc. (For that, we have the next point..;)

> Forthly the message provide by the bot should always be something actionanable by upstream not some cryptic error message that literaly means nothing to upstream.

There are a lot of error states that can occur and we can't prepare for all beforehand. But we can easily provide a better response for a specific case once someone informs us about that -- and that's what you've done. Thanks for that.
So, the task of this issue can be to solve this specific case -- to check that situation and provide information on how to solve that. (I'll update the title/description to make it actionable for our team if you don't mind.)
