### ISSUE TITLE
`/packit retest-failed` and `/packit rebuild-failed` don't work as expected

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1375]
Expected behavior is to restart/rebuild only failed tests/builds.
Currently these commands:
- `rebuild-failed` restarts everything - should restart only failed builds
- `retest-failed` restarts every tests - should restart only failed tests.

everything seems to working fine to [this point](https://github.com/packit/packit-service/blob/main/packit_service/worker/events/comment.py#L88). *_targets_override fills up with correct targets to rebuild/retest. Something after that might be broken. 

TODO:
- [ ] fix retest-failed
- [x] fix rebuild-failed
- [ ] fix - getting models from DB with commit is not enough

**Comment by lachmanfrantisek** [comment]
It looks like it restarts everything for `Retry` button in the Checks UI as well...;(

I hit that here: https://github.com/packit/specfile/pull/25/checks?check_run_id=5656718240

**Comment by nikromen** [comment]
Do you mean the `Re-run` button next to a failed job?
![Screenshot_20220323_224024](https://user-images.githubusercontent.com/70757578/159800439-d2f620f0-4ce4-4011-8d94-718d6c85669c.png)

**Comment by lachmanfrantisek** [comment]
> Do you mean the `Re-run` button next to a failed job?

Yes, sorry about the bad text for that, but I really meant `Re-run` for a single result.

> Also Re-run for individual jobs works correctly... seems like there is something between which overrides the targets_override

I don't think so. Maybe I mixed that with something else but still think it triggered everything...

**Comment by nikromen** [comment]
> I don't think so. Maybe I mixed that with something else (multi-job scenario, identifiers,...) but still think it triggered everything...

Oh you are right... again I tested it only for testing farm... It works... but for builds everything is restarted :/ 
It definitely worked when Laura implemented #1227 so something definitely overrides the `targets_override` :D

**Comment by nikromen** [comment]
closed with #1479
