### ISSUE TITLE
Duplicated issues for propose-downstream

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1380]
It looks like Packit creates a new issue instead of reusing the old one in case of an unsuccessful propose-downstream job.

> ...
>
> Secondly the bot should not be creating new issue when being unsuccessful for the second ( or more ) time but comment that it was unsuccessful again on the existing issue he had already created. 
>
> ...
> 
_Originally posted by @johannbg in https://github.com/packit/packit-service/issues/1361#issuecomment-1050203068_

Here are the related issues:
* https://github.com/dracutdevs/dracut/issues/1713
* https://github.com/dracutdevs/dracut/issues/1723
* https://github.com/dracutdevs/dracut/issues/1733

**Comment by lachmanfrantisek** [comment]
Once we have a commit status with the proper dashboard view and `re-run` button, might not need to use issues for re-triggering anymore.

**Comment by TomasTomecek** [comment]
> Is it ok to add a new column to the propose_downstream_runs table (ProposeDownstreamModel) to solve this issue?
> 
> If an issue is created it will be saved in the table and then reused for every later failure. New failures will create new comments to the same issue.

I like that! We can also then display it in the dashboard.

**Comment by lachmanfrantisek** [comment]
@majamassarini When working on #1409 I found this piece of code that can be used to help with that:

https://github.com/packit/packit-service/blob/8a7e2f60f55c3c8b2e13e59c45756102b143f58a/packit_service/config.py#L273-L285

I slightly enhanced that here: https://github.com/packit/packit-service/pull/1421/commits/38b46236cb0af10971de8720b7a8abe02e4287f2

I would use that static method and if we want to do some improvements, do that in that static method to fix that for all usages. (At least move it to some better place because I am not sure if it fits the class.)
