### ISSUE TITLE
SRPM build logs: change url from copr-be to download.copr

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1387]
We are using this build logs host:
https://copr-be.cloud.fedoraproject.org/results/@oamg/leapp/srpm-builds/03635385/builder-live.log.gz

Instead, we should use this:
https://download.copr.fedorainfracloud.org/results/@oamg/leapp/srpm-builds/03635385/builder-live.log

As copr-be is 404 and only contains the logs after the build is done; download.copr has them right away

**Comment by lbarcziova** [comment]
The hardcoded URL is set [here](https://github.com/packit/packit-service/blob/c3571744bead25ebe4177a4166d61523c39a6d4d/packit_service/worker/events/copr.py#L151) both for SRPM and RPM builds.
