### ISSUE TITLE
downstream koji builds: notify when something's wrong

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1409]
We need a mechanism to notify our users when something's wrong when Packit automatically submits a dist-git build into koji.

Ideally we'd have a view for this in the dashboard.

Acceptance Criteria: user is notified when a koji build fails or fails to be submitted.

**Comment by lachmanfrantisek** [comment]
It looks like we can hit a non-packit exception. The known issues should be covered by some `PackitException` and a commit comment should be created:

https://github.com/packit/packit-service/blob/4d67f8e9a06243a6b0dc60e4ad05c2d45edaa238/packit_service/worker/handlers/distgit.py#L358-L374

**Comment by lachmanfrantisek** [comment]
> Ideally we'd have a view for this in the dashboard.

Regarding the build results, we agreed in #1310 that we'll leave it to Fedora notifications...

But I agree we should cover the failed submissions somehow.

**Comment by lachmanfrantisek** [comment]
Oh, and `Commit comments are not supported on Pagure.`....;(

https://sentry.io/organizations/red-hat-0p/issues/3122397893/?environment=prod&project=1767823&query=is%3Aunresolved

**Comment by lachmanfrantisek** [comment]
As a team, we agreed on adding a new config option to set up a project that will be used for creating issues.

* Project on any git forge supported by Packit can be used. (Pagure, GitHub and GitLab where packit has an identity.)
* By default, nothing is used to not spam our users.
* Like other config options, you can set it on the top level but (re)define on job level.
* Optionally, we can apply this for other use-cases where we create issues (e.g. failed propose-downstream).
