### ISSUE TITLE
Sentry on API endpoints

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1430]
### Description

When trying to reproduce #1429, I wasn't able to find any related exceptions in Sentry, even though I got `500 Internal Server Error` as a response. I could see the exception directly in logs in the OpenShift

### Steps to reproduce

1. Query `https://prod.packit.dev/api/runs/267442`
2. Check OpenShift logs for `packit-service`
3. Check Sentry

### Currently

You can see exception in logs, but not in Sentry.

### Expected

Both in logs and in Sentry.

---

Could it be related to switch to `mod_wsgi`?

**Comment by mfocko** [comment]
It apparently popped up in the Sentry with a „bigger“ delay. However when I was trying it out on Thursday/Friday it didn't and also I cannot find it in Sentry if I specify «all» issues from those 2 days. Weird.

**Comment by TomasTomecek** [comment]
could sentry had an outage? :o
