### ISSUE TITLE
Run mypy without --no-strict-optional

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1433]
1. remove [`--no-strict-optional` from pre-commit-config](https://github.com/packit/packit-service/blob/e7f94129079e9bf1684366a634fdefe943a35fd4/.pre-commit-config.yaml#L49)
2. run `pre-commit run --all-files`
3. fix all errors

https://mypy.readthedocs.io/en/stable/kinds_of_types.html#no-strict-optional

See also packit/ogr#696 & packit/packit#1548

**Comment by FrNecas** [comment]
I will try to fix this since I almost got burnt today by the presence of this option :)

**Comment by TomasTomecek** [comment]
`--no-strict-optional` that's probably the most confusing option name I ever saw in my life

---

I finally get it! It's `typing.Optional`, not as "optional" in the actual sense

**Comment by TomasTomecek** [comment]
Based on @FrNecas's recent comments, this would be an immense effort & not worth the time. Closing then.
