### ISSUE TITLE
Steve needs love

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1439]
Currently, our code in `jobs.py` is not so well decomposed and it is really hard to know what are we doing - there are long statements and extra long methods/functions - and one can spend a long time figuring out what's going on. 
It would be nice to decompose/refactor long methods/functions/statements.

Mainly speaking of these methods and statements in them:

- [x] `get_handlers_for_event` 
- [ ] `SteveJobs.process_jobs`
- [ ] `SteveJobs.process_message`

**Comment by TomasTomecek** [comment]
that friday label :D

Sounds like a great hackfest task to do

big +1
