### ISSUE TITLE
Test only jobs are not grouped in a pipeline

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1442]
In case a job configuration requires only running some tests (without triggering a build first), it seems, that these tests are going to end up being created in separate pipelines.

![image](https://user-images.githubusercontent.com/11816497/162446067-bbd2603c-f085-40df-b8e6-d3cbdd90d099.png)

A *possible* (just an assumption) side effect of this is, that `/packit retest-failed' is not able to correctly tell which targets had failed tests in the last run, and might re-run test which passed the last time, but failed before that.

**Comment by lbarcziova** [comment]
> In case a job configuration requires only running some tests (without triggering a build first), it seems, that these tests are going to end up being created in separate pipelines.

Yes, this happens for tests with an enabled `skip_build` option, since as opposed to the tests requiring builds, we don't have any explicit item (srpm/copr build) to group the tests into a pipeline. We discussed this and the decision was to wait for #1327 to be implemented.

> A possible (just an assumption) side effect of this is, that `/packit retest-failed' is not able to correctly tell which targets had failed tests in the last run, and might re-run test which passed the last time, but failed before that.

Currently, the failed targets are determined via `commit_sha` (I already discussed with @nikromen that this is probably not correct in case the build/test was already retriggered before running `retest-failed`/`rebuild-failed`) so it shouldn't be influenced by this.

**Comment by csomh** [comment]
> > In case a job configuration requires only running some tests (without triggering a build first), it seems, that these tests are going to end up being created in separate pipelines.
> 
> Yes, this happens for tests with an enabled `skip_build` option, since as opposed to the tests requiring builds, we don't have any explicit item (srpm/copr build) to group the tests into a pipeline. We discussed this and the decision was to wait for #1327 to be implemented.

:+1: I didn't know that. Thanks!

> 
> > A possible (just an assumption) side effect of this is, that `/packit retest-failed' is not able to correctly tell which targets had failed tests in the last run, and might re-run test which passed the last time, but failed before that.
> 
> Currently, the failed targets are determined via `commit_sha` (I already discussed with @nikromen that this is probably not correct in case the build/test was already retriggered before running `retest-failed`/`rebuild-failed`) so it shouldn't be influenced by this.

Is this check done on the states we have saved in the database or on the check states that are set in GitHub?

**Comment by lbarcziova** [comment]
> Is this check done on the states we have saved in the database or on the check states that are set in GitHub?

Currently it is being checked in the database.

**Comment by csomh** [comment]
I'm wondering if it would make sense, to check the status in GitHub instead. I'm thinking that this might help with getting around a cluster of issues which can cause the state saved in the DB being out of sync.

**Comment by lbarcziova** [comment]
It came across my mind as well, I think it should work and mainly resolves the problem with currently using only `commit_sha`. I consider the solution using DB cleaner, but until we don't have the group models, I am not sure it can work correctly.
