### ISSUE TITLE
[RFE] Export PR number through PACKIT environment variable

### ISSUE THREAD

**Issue by kkaarreell** [packit/packit-service#1444]
Currently Packit/TFT exports various environment variables, however not the PR number itself.
This is needed e.g. for an integration with codecov.io service which require PR number in order to do a proper matching.

https://docs.codecov.com/docs/codecov-uploader#uploader-command-line-arguments

**Comment by lachmanfrantisek** [comment]
This is really easy to do. Does anyone want to take a look?
