### ISSUE TITLE
Ignored "shared" action

### ISSUE THREAD

**Issue by bocekm** [packit/packit-service#1450]
It seems that the `get-current-version` action @lachmanfrantisek [moved to make it shared](https://github.com/oamg/convert2rhel/commit/ea07315c91641fe4aae704c688aa2e7a76b539b8) is ignored/not executed.

You can see it by looking at https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/builds/. The pull request builds have version `0.25` (coming from the shared `get-current-version` action, as expected), but the `main` branch builds have version `v0.25` (likely coming from `git describe` - the packit default - unexpectedly).

I wonder why is the `get-current-version` action not executed even for the `main` branch builds. My suspicion is that the `main` branch build has a job-specific action and it overrides the shared action. I haven't found in the docs https://packit.dev/docs/actions/ whether this behavior is to be expected.

**Comment by lachmanfrantisek** [comment]
Hi Michal @bocekm!

You are right. The problem is in the partially overwritten `actions` key.
Our overriding workflow works for all the keys in the same way and the values are handled as one unit independently of the type -- so, if you set the `actions` key in the job, everything from the top level is ignored.


Is this behaviour ok, if we make this really clear in the docs? Or, should we try to do the overwriting/inheritance single-action-specific => make a union of the top-level and job-level actions.

**Comment by bocekm** [comment]
I'm for the option _"make a union of the top-level and job-level actions"_. Our packit config is an example of why it can be useful - two jobs sharing a single action to avoid duplication and one of the jobs requiring one action on top of that.

However I'm leaving it up to you. Duplicating the actions on a job-level is also an option - that's what I'll do now. I can revert it back if you decide for the "union".

**Comment by bocekm** [comment]
For some reason, making the previously shared action per-job again did not help. Or better to say, the behavior is now switched:
- the PR builds have version v0.25, e.g.
  - PR https://github.com/oamg/convert2rhel/pull/458, copr build https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/4293648/
- the main branch builds have version 0.25
  - e.g. copr build https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/4221844/

So now what seems to be ignored is the `get-current-version` defined under the job triggered by `pull_request`: https://github.com/bocekm/convert2rhel/blob/d320550cef86be0a8c7e9c1db275e160b018bfa8/.packit.yaml#L22.

**Comment by lachmanfrantisek** [comment]
@bocekm Sorry for the late response. I was on a PTO...

Thanks for the detailed investigation. Sadly, you hit an issue with the first job picked for SRPM build in Copr. Laura is fixing that here: https://github.com/packit/packit/pull/1564

You can change the order of the jobs to make it work in the meantime -- Use the `tests` one as the first one to not be affected by that.
Sorry about that. As usual, the fix should be on the production instance on Monday if it is ok for you.

**Comment by bocekm** [comment]
It works now as expected. Thanks!
