### ISSUE TITLE
Update info in GitHub Marketplace

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1466]
Looking at the public page of our GitHub application, some of the texts need to be updated: https://github.com/marketplace/packit-as-a-service

Also, we now have more features that can be marketed as well.

The task of this issue is to go through the [settings](https://github.com/organizations/packit/settings/apps/packit-as-a-service/) and [marketplace listings](https://github.com/marketplace/packit-as-a-service/edit) and update the various texts and images where needed. 

Don't forget to:
* [ ] ask someone to get access to the settings
* [ ] make sure the text corresponds to the reality (get inspired by packit.dev)
* [ ] mention all the key features we can provide
* [ ] check the links

**Comment by majamassarini** [comment]
I forgot to close it but it is already done.
