### ISSUE TITLE
Redirect new users to the notification issue

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1481]
Follow-up to https://github.com/packit/packit-service/issues/1476

After a user installs our app, they should be redirected to the notification issue created for them so they can get access ASAP without discovering the issue from their personal notifications.

There are multiple ways how to do this, please propose a solution:
https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app

TODO:
- [ ] design
- [ ] implement
- [ ] verify
- [ ] update docs

**Comment by lachmanfrantisek** [comment]
This is really hard to do since GitHub’s app configuration is static - we cannot change the callback URL per installation.

I am going to close this -- we are going to improve onboarding (packit/packit.dev#499) and link the issue in the status (#1506).
