### ISSUE TITLE
False-positive issue comments for Bodhi updates

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1482]
As you can see in https://github.com/packit/ogr/issues/713, there are two issue comments for each chroots stating that the update creation failed, but in the end, it was created successfully. We shouldn't place the error comment when we are doing another try. 

@lbarcziova Can this be related to the default task-retry mechanism?

**Comment by lbarcziova** [comment]
I think it very likely is related to the retries, but haven't seen the logs so can't tell for sure.

**Comment by lachmanfrantisek** [comment]
Verified on stage and works just fine.
