### ISSUE TITLE
Do not leave commit status checks as running indefinitely

### ISSUE THREAD

**Issue by FrNecas** [packit/packit-service#1489]
This is a follow-up to: https://github.com/packit/packit/issues/1567

Currently, if an error occurs, a status check may be kept in its pending/running state, see https://github.com/packit/ogr/runs/6209093398 . There is probably some other state that we should switch to to avoid confusion

**Comment by TomasTomecek** [comment]
We have the babysit tasks for this - would that solve the problem here?

**Comment by FrNecas** [comment]
Still valid

**Comment by TomasTomecek** [comment]
How relevant is this issue?

**Comment by FrNecas** [comment]
Still somewhat relevant, even though we have the babysit tasks, it is not used for the propose-downstream check. On the other hand, I am not completely sure if it is worth spending the time to do something about this -- the status checks as pending forever was a consequence of another bug and I don't recall a similar issue occurring since then.

**Comment by lbarcziova** [comment]
We decided to close this as there are multiple babysit tasks in place for TF and Copr builds, and for propose downstream we haven't bumped into this issue for a longer time.
