### ISSUE TITLE
More specific message for not allowlisted accounts

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1506]
Until the user is allowlisted for our service, he/she gets neutral statuses `Namespace is not allowed!` for the configured jobs requiring allowlisted user. This could be more specific e.g. `github.com/<namespace> needs to be approved before building.` ([initially proposed here](https://github.com/packit/packit.dev/pull/453#discussion_r867980148)) - specify which namespace is being handled with and maybe what the allowlisting is needed for (`building` here).

TODO:

- [ ] mention specific namespace in the status description
- [ ] find the related issue and provide it as a status URL
- [ ] update documentation (examples, wording, ...)

*edited by @lachmanfrantisek*

**Comment by lachmanfrantisek** [comment]
Currently, the instructions are present:
https://github.com/packit/packit-service/blob/307974f7bba1f349d5b0f9d0c0d3eaa6e988d2b4/packit_service/constants.py#L45-L52

There will be a link to the relevant issue -- covered by #1481

So the last bit is the namespace in the status.

**Comment by lachmanfrantisek** [comment]
Update:

* Redirecting after the installation is not easy to do (this should be covered by #1481)
* Here, we can provide the link when trying to use Packit -- as a team, we agreed on a search through the existing issue. (Filtering can be done both in this repo or added to OGR.)

I've updated the TODOs in the description...
