### ISSUE TITLE
Allow selecting a tmt plan for Testing Farm

### ISSUE THREAD

**Issue by FrNecas** [packit/packit-service#1507]
During our discussion, @psss mentioned that in some cases it may be handy to specify which tmt plan is run in a test job inside Testing Farm. TF's API supports this using the `name` key under `fmf` (it is a regexp passed to `tmt plan ls`).

The implementation should be fairly simple:
1) add a new key to our config, e.g. `tmt_plan`
2) pass it to TF inside the payload

**Comment by FrNecas** [comment]
I'd also like to take a look into fixing this once I am done with my current card :-)

**Comment by psss** [comment]
Yes, this would be very useful. A tangible config example outlined in teemtee/upgrade/pull/3.

**Comment by mfocko** [comment]
@psss Could you please clarify to what extend can this feature request be solved by packit/packit#1619 (specifically `tmt_plan_regex`)?

**Comment by psss** [comment]
It seems to cover the feature just fine. Maybe a naming question: Does it have to include the `_regex` suffix? I'd say that the shorter name `tmt_plan` would be better for the config if the docs mention that regular expressions can be provided as well.

**Comment by r0x0d** [comment]
Hey, @psss. I used the `tmt_plan_regex` because  I was following this [workflow](https://github.com/oamg/leapp/blob/835a3d27b52fe44cbca6ed5307e6801981df24d8/.github/workflows/tmt-tests.yml#L167) from Leapp. 

I can change it to use just `tmt_plan`, if it sounds more reasonable.

**Comment by psss** [comment]
> Hey, @psss. I used the `tmt_plan_regex` because I was following this [workflow](https://github.com/oamg/leapp/blob/835a3d27b52fe44cbca6ed5307e6801981df24d8/.github/workflows/tmt-tests.yml#L167) from Leapp.

Ok, I see.

> I can change it to use just `tmt_plan`, if it sounds more reasonable.

I'd vote for the shorter name.

**Comment by mfocko** [comment]
IIRC we use `upstream_ref` in the same sense (it supports globbing).

**Comment by r0x0d** [comment]
Thinking about the name now, does it make sense to use `tf_name` for it? Instead of `tmt_name`.

**Comment by psss** [comment]
I'd say `tmt_plan` is more specific and better describes what we are selecting, `name` is too much generic. @thrix, any suggestions here?

**Comment by FrNecas** [comment]
Fixed in https://github.com/packit/packit-service/pull/1547
