### ISSUE TITLE
Be able to retrigger the downstream jobs

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1510]
Since we now have multiple downstream jobs, we need to find a way to (re)trigger the jobs ad-hoc.

TODO:
- [x] #1536 
- [x] #1537

**Comment by lbarcziova** [comment]
Options:  
1. Issue comment in the issue created for errors once there is an `issue_repository` configured
     - this would be consistent with propose_downstream retries and therefore could be most reasonable and should be also easy to implement
     - we need to be notified about the comments and e.g.in Github if the repository specified in `issue_repository` doesn't have Packit enabled, we won't get the events
     
2. Having a central Github repository (similar to `packit/notifications`) where people could open issues to retrigger jobs
     - not convenient, messy
     - solves the problem about not getting events - we can enable Packit on this repo
     - the format would need to enable specifying the dist-git repo 
     
3. Dist-git pull-request comment related to a commit
    - not each commit is related to PR (direct pushes)
    - (the ideal option would be utilizing commit comments, but these are not supported in Pagure)
    
4. Dist-git issue/issue-comment
    - requires issue tracker to be enabled for dist-git repo, some users may not want to enable the tracker for this usage
    - otherwise sounds ok
    

I realised that the key problem here is that we need to be notified (get the webhook/message) about the event that should retrigger the downstream jobs, therefore if I am not mistaken, we are not able to handle any events defined in `issue_repository` if that repo doesn't have Packit enabled. Another thing we need to solve is who will be able to retrigger the downstream jobs and how to ensure it (configuration, people with write access to dist-git repo - in case of utilizing other place than dist-git for retries, we wouldn't be easily able to map the accounts, ...)?

**Comment by lachmanfrantisek** [comment]
Regarding the lack of GitHub application for `issue_repository`, we can state that requirement in docs and in the created issue. If people want to use this, they need to install the GitHub app or configure a GitLab webhook. I don't think it's a problem. With Dist-git/Pagure, we can use fedmsg to get that info but some filtering needs to be in place. Similarly, I don't see an issue to enable the issue tracker in dist-git...

**Comment by lbarcziova** [comment]
Yes, I know that we can make it a requirement, I am just not sure how flexible this could be for users if they otherwise don't want to use the upstream functionality.

**Comment by TomasTomecek** [comment]
I am checking [Fedora Packager Dashboard](https://packager-dashboard.fedoraproject.org/dashboard) and it only seems to aggregate data from other sources so probably can't be used to communicate problems.

I'm wondering if it makes sense to implement two: dist-git PR and issue_repository, as a way to talk to maintainers.

**Comment by lbarcziova** [comment]
> I'm wondering if it makes sense to implement two: dist-git PR and issue_repository, as a way to talk to maintainers.

@TomasTomecek  Do you mean the option 1. and 3.?

**Comment by lbarcziova** [comment]
this is in progress (some parts are already done)

**Comment by lbarcziova** [comment]
The subtasks are implemented, closing.
