### ISSUE TITLE
Log requests (with payload), received by `webhooks/gitlab`

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1512]
**Where?**
Probably to `/var/log/packit-service/*.log`. We don't need to log to stdout, to not pollute the container logs. Nor do we need to store them permanently in the db.

**Why?**
For easier debugging.
The requests payloads that Gitlab sends to webhooks are not completely consistent - or I just don't understand why sometimes some fields are missing ([1](https://gitlab.com/packit-service/src/open-vm-tools/-/merge_requests/18#note_950894435), [2](https://github.com/packit/hardly/issues/68)). We don't log what we receive so one has to go to Gitlab and dig in settings to see what was actually sent and that's difficult to impossible (see below).

When a webhook is set up directly in a Gitlab repo, one can go and see in [the settings of the webhook what requests were sent](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#troubleshoot-webhooks) to our API.
But in the case of [Group Hooks](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#group-webhooks), there is no history of sent requests, so there's no way how to see what exactly was sent to/received by our API endpoint.

Also, in the current setup of [repos for staging stream](https://gitlab.com/packit-service/src/) bot, the webhooks (for Pipeline events) are added to forks in [packit-as-a-service-stg namespace](https://gitlab.com/packit-as-a-service-stg), because that's where a detached merge-request pipeline runs. So when one wants to see what was sent, one needs to log in as `packit-as-a-service-stg` user to get into the settings.

**Comment by jpopelka** [comment]
Let's review once we implement #1740

**Comment by TomasTomecek** [comment]
Closing per @jpopelka's recent comment. We can always reopen.
