### ISSUE TITLE
bodhi update is missing changelog

### ISSUE THREAD

**Issue by martinpitt** [packit/packit-service#1518]
We just used packit for the first time to release [cockpit](https://github.com/cockpit-project/cockpit/blob/8f48c4740593e4eb08e1f40ffd98dbeb09f5c14a/packit.yaml). This went quite fine -- dist-git PRs, koji builds, and it also created bodhi updates. But they look wrong.

E.g. the [f35 koji build](https://koji.fedoraproject.org/koji/buildinfo?buildID=1969916) has a correct changelog:

![image](https://user-images.githubusercontent.com/200109/170067276-ed6c2433-6ab3-479e-a9db-91663e7b4050.png)

but the [bodhi release](https://bodhi.fedoraproject.org/updates/FEDORA-2022-ed88e19a91) looks like this:

![image](https://user-images.githubusercontent.com/200109/170067427-8ee3613a-9dad-4e3e-94da-002759e2546f.png)

I.e. it looks like it considered the *second*-latest version instead of the topmost one, or possibly the topmost one in dist-git *before* the current build/commit?

Fortunately I can edit the bodhi descriptions, so I am going to fix it now. I captured the screenshots for that reason.

**Comment by martinpitt** [comment]
[F36 release](https://bodhi.fedoraproject.org/updates/FEDORA-2022-d1b9fc4e30) is the same, so this is not just an one-off glitch.

**Comment by mfocko** [comment]
Version should be taken from the specfile

**Comment by lachmanfrantisek** [comment]
@martinpitt, this is just about the wrong version number, isn't it?

(I was thinking about a way how to tweak/provide the description or show there the whole changelog...)

**Comment by martinpitt** [comment]
@lachmanfrantisek : The wrong version number, and the absence of the description (from the changelog). E.g. the two recent automatically generated rawhide updates for [275](https://bodhi.fedoraproject.org/updates/FEDORA-2022-02684cba89) and [276](https://bodhi.fedoraproject.org/updates/FEDORA-2022-40973f0a9b) include the changelog. But the packit-generated ones for [275](https://bodhi.fedoraproject.org/updates/FEDORA-2022-532efa8791) and [276](https://bodhi.fedoraproject.org/updates/FEDORA-2022-e7a8ddd646) just say "New upstream release". At least the version number seems to be correct now, so I'll retitle this issue.

**Comment by mfocko** [comment]
Use changelog of the release as the Bodhi description (the same way as it is done automatically in Rawhide)
