### ISSUE TITLE
restrict building in custom Copr projects

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1523]
https://dashboard.packit.dev/results/copr-builds/346798

Miro pushed into his fork, master branch, which triggered a build in psss/fmf Copr project (trigger commit, branch master, project psss/fmf). That's a problem, only psss should control who can build in his Copr project.

The problem is even more complicated for Copr projects owned by a group.

We need to figure out some access control on our side.

TODO: https://github.com/packit/packit-service/issues/1523#issuecomment-1200793352

**Comment by lachmanfrantisek** [comment]
What about saving the mapping `GitHub project -> custom Copr project` on the first use and allowing builds just from this GitHub project later on. If multiple GitHub projects need to be allowed, we can manage that manually on request.

**Comment by TomasTomecek** [comment]
yeah, we should come up with some automated + manual solution

I was also thinking about a static mapping, b/c in the end we need an M:N mapping b/w github namespaces and Copr namespaces who can build where :)

**Comment by lbarcziova** [comment]
another, more explicit and safe solution would be to request the Copr project owners to include some "Packit metadata" directly in the project where they could define which Github projects can use the particular Copr project, but currently, I cannot see an ideal place to have this - description could be not considered the place where owners want to have such a data. What do you think about this type of solution? In other solutions I am missing the part about some verification - anyone could use any not yet used Copr project.

**Comment by TomasTomecek** [comment]
This could be a good time to ask Copr devs where and how such info could be stored. I like how this information would be stored inside Copr and not our database so it would be public and well accessible.

**Comment by praiskup** [comment]
Since the conclusion is "implement the forge project allowlist" on Copr side, I guess :-) we have two ways to implement this from the API perspective.  Either

**a)** we'll just add a new field like `forge_projects_allowed` into the following output output (`project_proxy.get()`):
```
$ curl "https://copr.fedorainfracloud.org/api_3/project?projectname=copr-dev&ownername=@copr" | jq
{
  ...
  "bootstrap": "default",
  "chroot_repos": {
    "epel-7-x86_64": "https://download.copr.fedorainfracloud.org/results/@copr/copr-dev/epel-7-x86_64/",
    ...
  },
  "contact": null,
  "description": "copr development repository with updated dnf-plugins-core to support copr-prune-repo.py",
  ...
  "unlisted_on_hp": false,
  "forge_projects_allowed": [
    "github.com/fedora-copr/copr"
  ]
}

```
and you will check the for the `forge_project_allowlist` first, before submitting the build.  Or we

**b)** will implement a new option in [build options](copr.readthedocs.io/en/latest/client_v3/build_options.html), something like `forge_project="github.com/fedora-copr/copr"`.

If we only had b), you could trigger unnecessary copr build failures (when user misconfigures, you wouldn't know the failure until the source RPM is uploaded).  Going with just a) seems like TOCTOU.  So a) + b), right?

These new `forge_project*` options will be hard to document, so it is questionable if we shouldn't go just with `packit_forge_project*` prefix.  Thoughts?

**Comment by lbarcziova** [comment]
Just for the record, I created a private ticket in Copr issue tracker https://pagure.io/copr/copr/issue/2216.

So my initial idea was something like **a)**, I haven't considered the TOCTOU problem, not sure how big a problem it could be if we would check this right before submitting the build.

Regarding **b)** it is true that if we didn't have the information right away, it would not be ideal UX.

So, for me it is **a)** and if needed additionally **b)**, but I would like to hear also other opinions, @packit/the-packit-team?

Regarding the naming of the options, I think the `packit` prefix makes sense. Thank you Pavel for these suggestions!

**Comment by TomasTomecek** [comment]
I think the information could also serve users ( = consumers) of the Copr project: it would point them to source code for packages in the given Copr project.

**Comment by csomh** [comment]
I also think, this should be a) and b).

**Comment by FrostyX** [comment]
Looks like there is a consensus on how to implement this, but I wouldn't have a clear conscience if I didn't put in my two cents.

As previously mentioned by @lachmanfrantisek

> When speaking about this today, we also mentioned using Copr project permissions instead because we now know the mapping between FAS and GitHub accounts.

When a person creates a PR or pushes some commits directly, I suppose in both cases Packit receives some JSON representation of the event, containing a GitHub username of the author. Packit then knows how to map the GitHub username to a FAS username. 

In Copr, we have a function `User.can_build_in(self, copr)`, that returns `True` if a user can submit builds for a given project (it considers permissions given by the project admin in the project settings as well as group memberships).

To me, it seems that the most straightforward and easy fix to this issue would be if Copr provided an API endpoint for the function in question, and Packit called it before submitting a build and verified the user permissions.

It sounds almost too easy, so I guess there is some shortcoming that I don't realize?

**Comment by lbarcziova** [comment]
> Packit then knows how to map the GitHub username to a FAS username.

Sure, that would be really the most straightforward solution, but unfortunately, we can't map any GitHub username to a FAS username, we store the mapping only for accounts that enabled our app (e.g. for a whole organization).

**Comment by lbarcziova** [comment]
What needs to be done here once the [Copr implementation](https://pagure.io/copr/copr/pull-request/2262) is in production:
- [ ] replace the [current check](https://github.com/packit/packit-service/blob/55f80823f6e5474212c9ca1c1747eb70a64e3e9c/packit_service/worker/helpers/build/copr_build.py#L334) whether the forge project can build in Copr project by checking the `packit_forge_projects_allowed` obtained from `project_proxy.get()`
- [ ] update the instructions on how to configure the Copr project with link to the Copr project settings
- [ ] when submitting Copr build, pass the forge project (e.g. github.com/packit/ogr) in the `build_options["packit_forge_project"]`
- [ ] catch the exc from Copr if forge project can't build in Copr and notify the user the same way as in the first point
- [ ] remove the currently used project's mapping from the service config (also from the schema, this can be done gradually)
- [ ] update the documentation
