### ISSUE TITLE
Create a Privacy Policy for Packit as a Service

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#1527]
The Github Marketplace requires a Privacy Policy for the Packit Service.

- [ ] write the policy
- [ ] link it to the marketplace: https://github.com/marketplace/packit-as-a-service

### Suggestions from @csomh 

- We should probably have something like: https://fedoraproject.org/wiki/Legal:PrivacyPolicy, though the scope (data) we operated with would be much more restricted.

- It's mostly just usernames and whatever other personal information users share on otherwise public repositories.
*Probably limiting how long old pipelines are retained would solve some issues on this area too.*

- Try asking to [legal@fedoraproject.org](mailto:legal@fedoraproject.org)

**Comment by TomasTomecek** [comment]
I believe we can close this one too :)

**Comment by majamassarini** [comment]
Orla suggested us to point the Fedora license, which seems to fit our needs, so that we are always update with new license versions. The effort to update new license for other minor projects is too high.
For this reason now in the marketplace we are pointing to https://fedoraproject.org/wiki/Legal:PrivacyPolicy.
