### ISSUE TITLE
Pass all copr bulids from the copr repository to Testing Farm

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#1532]
While testing a pre-release of fmf, we found out that Packit does not pass additional builds to Testing Farm.

For this copr project:
https://copr.fedorainfracloud.org/coprs/packit/teemtee-tmt-1202/packages/

The `fmf` build is not passed to Testing Farm (only `tmt` is):

https://api.dev.testing-farm.io/v0.1/requests/3235673b-93e4-4962-8dd4-0c817a1a4f38

**Comment by mfocko** [comment]
Hi, it does not, we pass the »built« RPMs rather than all packages present in the Copr repository.

OTOH, I guess you wanted to build and test `tmt` with the not-yet-released version of `fmf` with feature on which the `tmt` depends, right?

**Comment by TomasTomecek** [comment]
So the expectation here is to get all builds available in the Copr project and pass it to TF. I'm wondering what would be a good workflow to do that and how would this be configured.

**Comment by TomasTomecek** [comment]
Miro, we would need to figure out some kind of "composing" mechanism and probably pick latest builds of packages.

Example: OAMG team builds *everything* in their custom Copr project: https://copr.fedorainfracloud.org/coprs/g/oamg/leapp/

When I access a yum repo generated from the project, all builds are in there.

I guess this solution could be to provide latest builds of all packages in a Copr project: would that work?

**Comment by thrix** [comment]
Yep, that is what I meant sorry, latest builds for all packages. Another, maybe better solution, would be passing:

* the main copr build (+ subpackages) - what we have now
* the copr repository itself (instead of all latest builds)

**Comment by TomasTomecek** [comment]
This issue is heavily related to #1544

**Comment by lbarcziova** [comment]
From today's architecture: we will pass the URL of the Copr repository, Mirek suggests implementing getting that in the Copr API and then in Packit we would only get that URL via Copr API (and store this in the DB) and pass it to TF.

**Comment by TomasTomecek** [comment]
We have a new issue that covers this use case: https://github.com/packit/packit-service/issues/1972

we're closing this one over the new one, thank you for reporting!
