### ISSUE TITLE
Implement retriggering Bodhi updates via dist-git pull-request comments

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1541]
- [ ] retriggering will be done via dedicated Packit command - e.g `/packit create-update`
- [ ] we need to listen to `org.fedoraproject.prod.pagure.pull-request.comment.added` messages in fedmsg ([example message](https://apps.fedoraproject.org/datagrepper/v2/id?id=85d284e9-fa80-4f7c-8db6-cc0210f40941&is_raw=true&size=extra-large))
- [ ] user who triggers the jobs should have write access to the dist-git repository
- [ ] get the last build for the given branch

**Comment by TomasTomecek** [comment]
I spoke with @thozza yesterday and he said he's looking forward to this functionality :)

**Comment by thozza** [comment]
Yes, this would be awesome for al ofl the Image Builder components 😍 
We are releasing them in upstream by scheduled automation and rely on Packit to handle most of the Fedora workflow.

**Comment by lbarcziova** [comment]
This is in progress.
