### ISSUE TITLE
Triggering testing farm tests with artifacts from another project

### ISSUE THREAD

**Issue by fernflower** [packit/packit-service#1544]
leapp requires 2 copr builds to be passed to testing farm - one of [leapp](https://github.com/oamg/leapp) and another of [leapp-repository](https://github.com/oamg/leapp-repository) .
In simple cases you can get away with the-copr-build-from-the-pr and master version of another project, but for certain cases it is essential that we use the-copr-build-from-the-user-specified-pr-of-that-other-project instead of master.

For example:
A '/rerun 4242' comment is issued by a developer under some upstream leapp PR. Our [current copr copr-build workflow](https://github.com/oamg/leapp/blob/master/.github/workflows/reuse-copr-build.yml#L31) will create both leapp PR's copr build, leapp-repository\*PR4242\* copr build, and pass both artifacts to the [tmt-tests workflows](https://github.com/oamg/leapp/blob/master/.github/workflows/tmt-tests.yml#L18) as copr_artifacts.

We would love to have the same mechanism with packit as well.

**Comment by TomasTomecek** [comment]
If all builds are present in a single Copr project, this shouldn't be hard to do. We would just forward that information to Testing Farm and it would install the correct packages.

**Comment by r0x0d** [comment]
@TomasTomecek or @mfocko could one of you create a more detailed issue to implement this in packit? I would like to assume it after we are done with the previous one.

**Comment by TomasTomecek** [comment]
@mfocko is already busy with learning for his state University exams later this month, I expect he would respond less and less :D

This request needs a thorough design on our side. I can see that you explicitly build both PRs in Copr. With your Packit setup that shouldn't be needed as the other PR is already opened (and hopefully built).

So when you type a command saying `Hey Packit, run tests for this PR together with leapp-repository#1234` and we want to have this functionality generic for anyone, there needs to be some configuration involved:
1. The builds should be in a single Copr project to make it easy for everyone
2. There should be a clear mapping b/w the text of the comment, selected package and precise build identification

I hate regexes but they would come in handy here:

`/packit test leapp-repository.+PR1234`

This command would:
1. Discard all present Testing Farm statuses on the PR
2. Verify that the PR is configured to build in a custom Copr project
3. Enumerate all builds and match the selected regex with a build
4. Set status to failure if the build can't be found
5. If found, append RPMs' NVRs to the payload for Testing Farm
6. Run test in TF

@lachmanfrantisek @lbarcziova what are your thoughts about this?

**Comment by TomasTomecek** [comment]
Since I have received no feedback, we'll discuss it tomorrow with our team at our architecture meeting.

**Comment by TomasTomecek** [comment]
> Sorry for the late reply, I missed the previous notification.

No problem, glad for your reply.

> > 1. The builds should be in a single Copr project to make it easy for everyone
> 
> Maybe I don't get something, but what do you see as a problem of having the builds in different Copr projects? I think people use mainly Copr builds from PRs without configuration of the project -> new Copr repo for each PR.

The only problem for me was that it would be more work for us and the feature would be more complicated. On the other hand, it's true you already wrote a function that obtains built RPMs that we use today for the stable builds.

And it's true that the feature would be much more flexible if Packit would find the build in other Copr projects too.

> Getting of the NVRs for the other PR builds shouldn't be a problem since we store this for each build in DB and we should be able to easily access the most recent build for a PR.

Can we then paste URL of RPMs into the payload for TF - would it consume it correctly?

> Regarding the format, I can see this as a discussion on the architecture :D for me it could make sense also the Github format namespace/repo#pr_id or being explicit `/packit test --pr-id 15 ...`.

+1, both LGTM

> Also as I was thinking about this use case and that this should be triggered only by comments explicitly, would it make sense to have a trigger type to react only to comments?

I'd like to say yes but don't know what my answer implies :D

**Comment by TomasTomecek** [comment]
We've just discussed this and gonna proceed with design & research.

**Comment by TomasTomecek** [comment]
@lbarcziova is mostly done with research for this request, see PR above ^

**Comment by lbarcziova** [comment]
What needs to be done:
- [ ] implement extension for comment command `/packit test` with an argument expressing the PR - the Copr build for the corresponding PR will be used in the tests, follow the research from the PR above:
     - [ ] the format should be `/packit test namespace/repo#pr_id`
     - [ ] we will get the information about the Copr build from the DB and pass the info about additional PR into the TF payload
     - [ ] when parsing the payload from TF, make sure we are handling with the "main" PR and set statuses there
- [ ] properly document this use-case (and the requirement for configured builds, see the research PR)
