### ISSUE TITLE
Document how to generate an ERD of the database

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1552]
It would be really nice to have an ERD of our databse somewhere (in the docs or in the repo?) just so when someone will be dealing with the database she/he can look to the diagram and clearly (in comparison just to looking to the code) see the scheme and/or plan the new changes.

Also: 

- It is possible to somehow generate the diagram? Do we know about some existing tool?
- And can we update the ERD scheme dynamically somehow? (should be possible if the tool exists)

**Comment by csomh** [comment]
We discussed that this kind of document might quickly go out of date. Rather document in the contribution guide how one could generate such a diagram.

**Comment by TomasTomecek** [comment]
Our concern is that even the documentation could get easily outdated. So the best solution here is to find whatever works for you and use it to generate the ERD. Please share your findings if you find that works for you well.
