### ISSUE TITLE
SRPM build in Copr: utilize dnf instead of our logic

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1562]
https://github.com/packit/packit-service/blob/8dfed2e97c05df77541121d5197b49091fa070d3/packit_service/worker/helpers/build/copr_build.py#L374-L400

Since we are reimplementing logic from dnf here, we should instead use yum repos ale let dnf decide what's the latest stable build.

The preferred method for doing this is for Copr's custom_method to support setting additional repositories.

AI:
- [ ] Implement this in Copr
- [ ] Create a followup card for packit-service

Let's discuss on the exact plan & solution.

**Comment by TomasTomecek** [comment]
we sohuld utilize our packit-stable and packit-dev Copr projects as a source when populating the SRPM build chroot

**Comment by TomasTomecek** [comment]
we should discuss this on arch this Thu (Oct 13th)

**Comment by mfocko** [comment]
Related issue: [external repositories are not set up when running custom script](https://pagure.io/copr/copr/issue/530)

**Comment by mfocko** [comment]
Fixed in https://pagure.io/copr/copr/pull-request/2352

**Comment by TomasTomecek** [comment]
Do we need to do some changes on our side to use the new functionality?
