### ISSUE TITLE
[Prometheus] Implement adoption metrics

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1566]
Instrument the adoption metrics so we can later send and gather the data and diplay them in Grafana.

TODO:

- [ ] Go through the definition of [adoption metrics](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md) and implement them so we can later display them in Grafana. We may want to see these:
    - [Newcomers adoption](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md#newcomers-adoption)
    - [Active namespaces](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md#active-namespaces)
    - [Users retention](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md#users-retention) 
    - [Usage of Packit services](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md#usage-of-packit-services)
    - [Most active namespaces](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md#the-following-metrics-will-be-displayed-as-a-histograms)
    - [Real time metrics](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md#real-time-metrics)

If some of the metrics are really hard to implement and they are not so important, discuss within the team if it's OK to skip them.

[This](https://github.com/packit/research/blob/main/adoption-metrics/implementation.md#prometheus) may help you with implementing these - it contains some useful links where to start.

Then continue with #1567

**Comment by bexelbie** [comment]
Seeing this data would be super useful to me - I am commenting in part to see when the chain starts to close :)

**Comment by lachmanfrantisek** [comment]
After working on https://github.com/packit/dashboard/issues/192 resulting in https://dashboard.packit.dev/usage, we agreed on continuing that way instead of implementing the Grafana dashboard. I am going to close this issue.

The [adoption metrics](https://github.com/packit/research/blob/main/adoption-metrics/define_adoption_metrics.md)  and other improvements will be implemented on a dashboard.
