### ISSUE TITLE
Copr builds fail for epel-7 and epel-6

### ISSUE THREAD

**Issue by danmyway** [packit/packit-service#1601]
Since yesterday 2022-08-02, approximately 14:30 packages for epel-6 and epel-7 fail to be build for [Convert2RHEL](https://github.com/oamg/convert2rhel) PR's.
Building packages for epel-8 works fine.
See https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/4698072/
There were no issues with packages being built for `main` at that time
See https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/4698179/

```
Start: buildsrpm
Start: rpmbuild -bs
error: bad date in %changelog: Tue Aug 02 02:31:02 UTC 2022 Packit <hello@packit.dev> - 0.26-1.20220802143102718182.pr451.28.g33894f1
Building target platforms: x86_64
Building for target x86_64
Finish: rpmbuild -bs
INFO: chroot_scan: 3 files copied to /var/lib/copr-rpmbuild/results/chroot_scan
INFO: /var/lib/mock/epel-6-x86_64-1659450720.702706/root/var/log/dnf.rpm.log
/var/lib/mock/epel-6-x86_64-1659450720.702706/root/var/log/dnf.librepo.log
/var/lib/mock/epel-6-x86_64-1659450720.702706/root/var/log/dnf.log
Finish: buildsrpm
ERROR: Exception(/var/lib/copr-rpmbuild/workspace/workdir-6hm9s8u6/convert2rhel/convert2rhel.spec) Config(epel-6-x86_64) 0 minutes 57 seconds
INFO: Results and/or logs in: /var/lib/copr-rpmbuild/results
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
INFO: unmounting tmpfs.
Finish: clean chroot
ERROR: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bs  --target x86_64 --nodeps /builddir/build/SPECS/convert2rhel.spec

Copr build error: Mock build failed
```

@TomasTomecek edit:
Task list for this issue is below: https://github.com/packit/packit-service/issues/1601#issuecomment-1207923372

**Comment by TomasTomecek** [comment]
do I get it correctly that the date is the problem?

```
error: bad date in %changelog: Tue Aug 02 02:31:02 UTC 2022 Packit <hello@packit.dev> - 0.26-1.20220802143102718182.pr451.28.g33894f1
```

**Comment by nforro** [comment]
> do I get it correctly that the date is the problem?

It seems so, it's in the extended format and the version of RPM in EPEL 6 and 7 is most likely not able to parse it.

**Comment by nforro** [comment]
The support was added in https://github.com/rpm-software-management/rpm/commit/57f94a582602f0353cdb17a02dc12c4461d4f32d (so it's in 4.14.0 and up) and RPM version in EPEL 7 is 4.11.3.

**Comment by danmyway** [comment]
It does seem so.
Weird thing is it does not have any problem with parsing for builds after merging to main
```
Start: buildsrpm
Start: rpmbuild -bs
warning: Could not canonicalize hostname: aws-x86-64-normal-prod-01942800-20220802-151250
Building target platforms: x86_64
Building for target x86_64
Wrote: /builddir/build/SRPMS/convert2rhel-0.26-2.20220802152613756774.main.28.g03da14c.el6.src.rpm
Finish: rpmbuild -bs
INFO: chroot_scan: 3 files copied to /var/lib/copr-rpmbuild/results/chroot_scan
INFO: /var/lib/mock/epel-6-x86_64-1659454027.796971/root/var/log/dnf.rpm.log
/var/lib/mock/epel-6-x86_64-1659454027.796971/root/var/log/dnf.librepo.log
/var/lib/mock/epel-6-x86_64-1659454027.796971/root/var/log/dnf.log
Finish: buildsrpm
INFO: Done(/var/lib/copr-rpmbuild/workspace/workdir-mq97lzgj/convert2rhel/convert2rhel.spec) Config(child) 0 minutes 54 seconds
INFO: Results and/or logs in: /var/lib/copr-rpmbuild/results
INFO: Cleaning up build root ('cleanup_on_success=True')
Start: clean chroot
INFO: unmounting tmpfs.
Finish: clean chroot
```

**Comment by TomasTomecek** [comment]
I'm assuming this is something we have changed in Packit that caused the breakage, is that correct? Well actually, is the date coming from the specfile library?

**Comment by nforro** [comment]
> Well actually, is the date coming from the specfile library?

I don't think so, it defaults to the old format: https://github.com/packit/specfile/blob/1ba57311637d41f9fdbe5f85ee2f8bd96abc8618/specfile/specfile.py#L273-L279

**Comment by nforro** [comment]
> Well actually, is the date coming from the specfile library?

Actually, you are right, I just tested it locally with convert2rhel spec and it does generate a new entry with extended timestamp format :frowning_face:

**Comment by nforro** [comment]
I've opened https://github.com/packit/specfile/issues/76.

**Comment by TomasTomecek** [comment]
Wow, that was a fast fix :D now to get it to production

**Comment by TomasTomecek** [comment]
Unfortunately, the fix didn't solve the problem https://github.com/TomasTomecek/convert2rhel/pull/3

@nforro confirmed it works as expected locally, but once we get inside Packit, the problem persists. We don't know right now where the problem is exactly.

My plan right now is to workaround the issue by changing c2r's packit.yaml

**Comment by TomasTomecek** [comment]
Update: we have proposed a workaround that is merged (see above). Hence dropping high-prio

Work on our side to do:

2. [ ] Build ogr and specfile in packit-stable Copr project
3. [ ] Install worker image using that Copr packit-stable repo
4. [ ] Install our stack using the packit-stable Copr repo inside the Copr env for SRPM builds ( https://github.com/packit/packit-service/issues/1562 )
5. [ ] Release specfile

**Comment by lbarcziova** [comment]
Related: packit/specfile#80

**Comment by bocekm** [comment]
I'd like to note that the workaround https://github.com/oamg/convert2rhel/pull/556 solved the issue partially as now the copr builds don't have a distinct NEVRA which is something we're expeting when testing manually. For example instead of `convert2rhel-0.26-1.20220805122400334947.pr554.44.g66a5b9a` describing what PR the build relates to we now have `convert2rhel-0.26-1`.

It's nothing critical yet not ideal. Instead of some automation we have around the package NEVRA, we can go to the GitHub PR, get a link to the specific copr build from the Packit dashboard, copy the copr build rpm URL and paste it to a yum install call.

**Comment by TomasTomecek** [comment]
adding high-prio back as this now affects more teams

we now fully understand scope of this problem, and will refine tasks and prioritize them accordingly

please let us know if you are blocked by this

**Comment by TomasTomecek** [comment]
please provide karma for the fc35 update of python-specfile https://bodhi.fedoraproject.org/updates/?search=python-specfile

once it lands in stable, the update should land in Copr SRPM build chroot thus resolving this problem

**Comment by TomasTomecek** [comment]
I just verified that for the SRPM builds that happen in Copr (you set `srpm_build_deps` in your packit.yaml), the issue is resolved: https://github.com/redhat-performance/tuned/pull/455

For legacy SRPM builds that happen inside Packit infra, the fix will be available Tue morning per our usual production update.

Please reopen if you are still affected by this or found a new case where the changelog is parsed incorrectly. Thank you all for your patience!

**Comment by bocekm** [comment]
We have `srpm_build_deps` in our packit.yaml so reverting https://github.com/oamg/convert2rhel/pull/556 should solve this issue for us, right?

**Comment by TomasTomecek** [comment]
Whoopsie, this one is totally resolved.
