### ISSUE TITLE
Provide a way to pass `pool` to Testing Farm

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#1627]
In some cases, the user would like to route requests to a specific infrastructure pool. We want to use this with `tmt` to run a test job against internal Openstack which has `/dev/kvm` available for a bunch of tests.

It is environments[0].pool in the requests POST API endpoint: https://testing-farm.gitlab.io/api/#operation/requestsPost

@TomasTomecek added TODO:
* [x] Add `extra_tf_params` field to test job definition
* [x] Let content be freeform
* [ ] Update our documentation, point to the TF's API docs above
* [ ] Make a test case & good user experience when user provides some invalid values in there: check TF's response and make sure we provide a sensible error message
* [ ] Resolve #1797

**Comment by lachmanfrantisek** [comment]
Hi @thrix !

So it's about adding a new config option and sending it inside a payload? That won't be hard to do  -- are you or anyone else interested in implementing this (we can help for sure..;)? Otherwise, someone from the team will take a look... (Is there any team that really needs this? Should we hurry up?)

**Comment by TomasTomecek** [comment]
I'm wondering if we should offer a freeform dict that would be passed, as is, to the Testing Farm API so we wouldn't need to implement every single parameter of the REST API endpoint.

WDYT?

**Comment by TomasTomecek** [comment]
adding for refinement so we can solve all the issues "please implement tmt argument xyz" once and for all :)

**Comment by FrNecas** [comment]
I've dropped resolving #1754 from the TODOs. Fixing this issue will only partially help with that one. The task in the linked issue is to provide a way how to pass extra arguments from comments which is a whole new feature and not supported at the moment.
