### ISSUE TITLE
Packit reacts to Fedora dist-git events on repositories which don't Packit configs

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1629]
Packit made [this comment](https://src.fedoraproject.org/rpms/ansible-collection-community-rabbitmq/pull-request/1#comment-113816) on failing to load the config file in dist-git, but the package has no configuration at all.

Based on information in Sentry, it seems that merging the PR, triggered a `org.fedoraproject.prod.pagure.pull-request.comment.added` event. This should have been ignored, as it contains nothing that should trigger Packit, but it wasn't.

Is the package configuration attempted to be loaded even if there is nothing in the comment that should trigger an action?

**Comment by lachmanfrantisek** [comment]
I am confused why there was a parsing error when there is no packit config in the repository.

Someone should take a look to not spam projects not using Packit.

**Comment by lachmanfrantisek** [comment]
Looks like we wrongly parse `500` errors when asking for a Packit config:
```
GET https://src.fedoraproject.org/rpms/ansible-collection-community-rabbitmq/raw/345a07ba5dc90dce8e37892a7633fdbd6eb90155/f/.packit.json [500]

{reason: INTERNAL SERVER ERROR}
```

And we try to parse that error instead of file content.

This is the regular response for nonexisting files:
```
GET https://src.fedoraproject.org/rpms/ansible-collection-community-rabbitmq/raw/345a07ba5dc90dce8e37892a7633fdbd6eb90155/f/.packit.yml [404]

{reason: NOT FOUND}
```
