### ISSUE TITLE
Support for gitlab.freedesktop.org

### ISSUE THREAD

**Issue by ochosi** [packit/packit-service#1655]
It would be very beneficial to projects on gitlab.freedesktop.org to have support for packit on this git forge.
To mention a concrete example, we would like to enable [bolt](https://gitlab.freedesktop.org/bolt/bolt) to use packit to automate its downstream releases. I'm sure there are other packages too that would be interested in using packit.

The workaround is to set up a one-way sync to a GitHub mirror and then use GitHub's packit integration.

**Comment by TomasTomecek** [comment]
@lachmanfrantisek @mfocko would you know what exactly this means on our side?

**Comment by lachmanfrantisek** [comment]
As Maťo mentioned, creating a user (or two -- one for each instance) should be enough. The webhook is then set by the user.

@ochosi, if you are ok with the state not being polished, it would be nice to finalize the work spent on this. (The main reason for this not being polished is that we haven't had any real users on GitLab so far.)

The setup is described here: https://packit.dev/docs/guide/#gitlab

**Comment by ochosi** [comment]
@lachmanfrantisek Sure, I'm more than happy to do be the guinea pig for this :)

So is there something left for you to fix/implement or should I try to go ahead with the webhook? (Note that I don't have admin rights on the repo, at least not yet)

**Comment by lachmanfrantisek** [comment]
> So is there something left for you to fix/implement or should I try to go ahead with the webhook? (Note that I don't have admin rights on the repo, at least not yet)

We need to set up the user accounts first. I've put this task in the `ready-to-refine` column of [our board](https://github.com/orgs/packit/projects/7) so we can resolve this once we are done with the currently planned tasks...

**Comment by csomh** [comment]
(Note: this is one more case to prioritize #1576, and pull releases to dist-git [instead of pushing them *from* whatever forge the upstream hosts its code] would be beneficial.)

**Comment by ochosi** [comment]
> (Note: this is one more case to prioritize #1576, and pull releases to dist-git [instead of pushing them _from_ whatever forge the upstream hosts its code] would be beneficial.)

Yeah, good point. That would indeed make things easier in this case.

**Comment by TomasTomecek** [comment]
I spoke to Vincent Mihalkovic yesterday and he said they'd love to use Packit for polkit. It is also hosted on freedesktop gitlab (what a coincidence :D).

**Comment by mfocko** [comment]
I have created accounts for both prod and stage (credentials and configs are updated in BitWarden and also updated in the deployment).

We need to test building on gitlab.freedesktop.org and also fix a wrong link (hardcoded `gitlab.com`) in the initial issue for setting up webhook on GitLab

**Comment by ochosi** [comment]
Just to clarify, will I need admin access to the gitlab repository in question in order to set up the integration?

**Comment by jrybar-rh** [comment]
Hi,
You probably need a Maintainer role for setting up hooks [1], but I can do
it as an Owner.
We can discuss this in our meeting.

[1] https://gitlab.freedesktop.org/help/user/permissions.md

**Comment by mfocko** [comment]
There was a smallish issue with missing tokens on prod (they »are« present in the latest config in the Vault, not sure what it is about; I updated the config in OpenShift and rescaled everything affected (service, workers)).

Testing MR: https://gitlab.freedesktop.org/mfocko/packit-hello-world/-/merge_requests/2

**Comment by TomasTomecek** [comment]
As @mfocko demonstrated above, Packit can now support Freedesktop Gitlab :) Though we need to manually approve every single project, so please reach out to us directly for that :)
