### ISSUE TITLE
[Feature idea] Get the source artifact from GHA workflows

### ISSUE THREAD

**Issue by webknjaz** [packit/packit-service#1662]
I've got workflows with Python projects where I build an sdist that gets tested, used for building wheels and is subsequently published to PyPI. So one of the first jobs produces it and shares as an artifact with other jobs. This tarball is the source of truth for any other packaging workflows.

Currently, packit.dev forces me to duplicate the sdist creation within it and so I ends up having a situation when there's now 2 sources of truth that may or may not be identical — you never now (but surely hope so!).

I want to propose supporting a mechanism that would allow Packit download that sdist from a GitHub Actions artifact instead of building its equivalent from a Git checkout. Or, alternatively (or additionally), Packit could support fetching SRPMs from GHA artifacts too.

How could this be implemented? Packit could listen for job success events and check if there's an artifact published matching whatever the maintainers would set in `.packit.yml`. Then, it'd auto-download it into the SRPM building env. Or, in case of SRPM, it'd just proceed with the testing jobs.
Instead of listening for the built-in GH events, Packit could alternatively provide an API end-point where GHA could send an HTTP request (with an artifact bundled) that would trigger Packit's processing workflows (this could be facilitated with a small GitHub Action that would also forward the env vars so Packit would "see" the context of the PR).

The current workaround, as I see it, could be polling GH API in a loop from the `create-archive` hook to see if an artifact appeared in the last workflow run, and downloading it there. But it seems suboptimal to me because (1) it's probably a waste of resources and (2) I think it wouldn't handle workflow re-runs well.

WDYT?

**Comment by TomasTomecek** [comment]
Sviato, you're not the only one who would benefit from this workflow.

The cockpit team went the most further and actually implemented it by polling the storage endpoint to collect the archive.

I agree that we should have an event-based mechanism instead in Packit that would allow connecting Packit and Github Actions together.

**Comment by TomasTomecek** [comment]
We can see that GitHub can send a webhook payload once a GHA run is completed: https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

we'd just need to react to that

we also need to check if we need more permissions to get those events

**Comment by webknjaz** [comment]
You may want to looks at `workflow_job` (allowing the users to specify which job to wait for rather than the whole workflow run) or `check_suite` (but that's more about GH Apps, not GHA).

**Comment by lbarcziova** [comment]
Hi! During our triaging session last week, we, unfortunately, decided to drop this issue, as this functionality does not seem to affect many users and does not currently align with [our priorities](https://github.com/orgs/packit/projects/7/views/29). If you feel this should be reconsidered/discussed again, please feel free to reopen!
