### ISSUE TITLE
"Could not find build id '...' for chroot '...'" even when the build succeeded

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1674]
Reported by @martinpitt in https://github.com/cockpit-project/cockpit/pull/17755

> @TomasTomecek, @lachmanfrantisek: packit tests here failed with "Could not find
> copr build id '4868126' for chroot 'fedora-37-x86_64' ". However, the actual
> COPR builds succeeded, e.g. here:
> https://dashboard.packit.dev/results/copr-builds/470175. Infra problem or some
> API impedance mismatch? The same happened in e.g.
> cockpit-project/cockpit-machines#809 , it's not specific to this PR.

Does anyone have a clue if we are already tracking this?

**Comment by mfocko** [comment]
MR: https://gitlab.com/testing-farm/gluetool-modules/-/merge_requests/222

**Comment by lbarcziova** [comment]
There is already an incident on our status page describing this: https://status.packit.dev/issues/2022-09-22-outage/

**Comment by nforro** [comment]
The issue is resolved: https://gitlab.com/testing-farm/gluetool-modules/-/merge_requests/223
