### ISSUE TITLE
Half of SLO 1 error budget depleted in a month

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1677]
SLO 1 is defined as "Changes to GitHub PRs receive a status update within 15 seconds in 99% of cases".

[The error budget for SLO 1 has been decreasing since the beginning of September; now it's about 50%](http://metrics.osci.redhat.com/d/VXwH27XMk/rhel-infrastructure-and-service-health?orgId=1).
It's not been decreasing uniformly; there were 4 more significant drops (about 9% down in several minutes) and about 5 smaller decreases of about 1-2% in several minutes. Most of the time it stayed more or less the same.
I investigated all the big downswings but never realized anything unusual at those time frames; for example, the "number of received webhooks" or "number of tasks executing at worker" was always quite low.
What also doesn't make sense to me is that sometimes the remaining error budget is decreasing overnight when there's almost no traffic (and then is increasing during the day when all the work happens).

It started to happen around the same time when we [deployed the multi-threaded short-running worker instead of several single-processed workers](https://github.com/packit/deployment/pull/372) so it's possibly related, but I have no idea how.

**Comment by csomh** [comment]
> It started to happen around the same time when we [deployed the multi-threaded short-running worker instead of several single-processed workers](https://github.com/packit/deployment/pull/372) so it's possibly related, but I have no idea how.

Could reverting this change and let it run for a week help us decide whether this is the case?

**Comment by jpopelka** [comment]
Yes, I'll do that.

**Comment by jpopelka** [comment]
It's been 12 days since I reverted the change and here's what it looks like.
The first graph shows 12 days before the revert, i.e. 1 multi-threaded short-running worker:
![before](https://user-images.githubusercontent.com/288686/195046005-80c5aab5-d394-4ddf-8d63-4764649f75cb.png)
The second graph shows 12 days after the revert, i.e. 4 single-threaded/processed short-running workers:
![after](https://user-images.githubusercontent.com/288686/195046043-0aa655c9-9760-4a95-bfdd-92004438c4d7.png)
Both contain a few big drops, so it doesn't look related to the change. I know there was the [Github webhooks outage last week](https://status.packit.dev/issues/2022-10-05-github-webhooks-degraded-status/), but that's only one of the drops on the second graph, but there are two more.

**Comment by csomh** [comment]
Hm, so it's gotta be something else. Should we raise priority on this and preemptively start looking into it to better understand what's going on?

**Comment by jpopelka** [comment]
2/3 of the budget is gone so I'd say let's start looking into that sooner rather than "drop everything and fix it ASAP" once the budget is depleted.

**Comment by jpopelka** [comment]
I did more investigation and the most important finding (to me) is that the Error Budget (EB) is calculated from a preceding four-week window so the Remaining EB graph doesn't tell you when exactly a service downgrade/improvement happened.
For that, you need to see the `Packit boards` -> `(Prod/Stg) Accepted status time` graphs.
I've also added one more graph: `Cyborg /RHEL Infrastructure and Service Health` -> `Packit` -> `Statuses set after 15s`
which will tell you a number of initial statuses that took longer than 15s to be set.
You can also grep the short-running worker logs for "Reporting initial status time:".
Hint, use `| search message"Reporting initial status time*"` in Splunk.

So what does the history of `Packit boards` -> `(Prod/Stg) Accepted status time` graphs tell us?
In the whole (1 year) history, the biggest change of trend happened in April and it was clearly caused by the [change of way how we calculate the initial_status_time](https://github.com/packit/packit-service/pull/1446).
Then, since the end of August (Stg) / beginning of September (Prod) the average values went up a bit.
I went through the git history (last week of August) of packit-service and deployment and can't see what could have caused the change of trend.
There were lots of SQLAlchemy-related changes, but I don't think they are related, thou it's possible.
The 4 single-threaded workers vs. 1. multi-threaded might still be related because in the first 2 weeks of October there were again the 4 single-threaded workers running and the trend seems to have changed a bit.
But it's all about how one interprets the data and it needs longer periods of time before one can notice a change of trend.

If the error budget again starts to be consumed and we still have no idea what causes it, then I'd probably try to add another (this time multi-threaded short-running) worker.
Yes, that's what Hunor originally suggested, and I was against it to be sure we don't hit the old https://github.com/packit/packit-service/issues/375 again, but now I think it should be OK, because we have separate workers for long-running tasks and we also have the babysitting tasks as a safety net.
I, however, still think it'd just hide the real cause somewhere else because the one multi-threaded worker usually uses just a few threads at the same time even it has a dozen more slacking.
For example, today I noticed there were a few initial statuses set after more than 20 seconds in the staging instance.
When checking the short-running worker logs I noticed that there was a 17s window after the GitHub PR comment was accepted when the worker was just slacking.

**Comment by jpopelka** [comment]
I've created a [postmortem](https://github.com/packit/status/pull/48) and will keep an eye on the metrics.
Closing this for now.
