### ISSUE TITLE
Remove the hardcoded mapping for custom Copr projects

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1685]
- [ ] remove the usage of `allowed_forge_projects_for_copr_project` in the configs (both stg, prod) and update the files in Bitwarden
- [ ] remove the field from the [config schema](https://github.com/packit/packit-service/blob/caeacf9857dcc641bb9a7f16bca856235bf82302/packit_service/schema.py#L83)
- [ ] remove the related code [here](https://github.com/packit/packit-service/blob/caeacf9857dcc641bb9a7f16bca856235bf82302/packit_service/worker/helpers/build/copr_build.py#L395)
- [ ] remove the documentation [in deployment repo](https://github.com/packit/deployment/blob/main/docs/allow-custom-copr-projects.md)

**Comment by lachmanfrantisek** [comment]
Do we have a time estimate for this? (At the end of the year?)

In the meantime, we can periodically check the projects in the config and remove it if they have the mapping configured.

**Comment by lbarcziova** [comment]
> Since they get the comment, I think they will actually be forced to configure it very quickly...

+1, I think we could plan this in a month
