### ISSUE TITLE
Restricting custom copr build message written multiple times

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#1686]
Service is writing multiple times the same message (on restricting custom copr builds): https://github.com/facebook/netconsd/pull/8

On [this method](https://github.com/majamassarini/packit-service/blob/09744908b931ec384dce845fc1fdd6b8e87f9294/packit_service/worker/helpers/build/copr_build.py#L375) we probably need to read what is already written into the github thread and comment only if the same message is not the last written message.

**Comment by lachmanfrantisek** [comment]
Alternatively, we can use the same workflow we do for downstream issues:
* Create an issue if it doesn't exist.
* If it exists, place a new comment there.

(We have a code for this...)

**Comment by lachmanfrantisek** [comment]
If we want to preserve commenting on the issue, this can be reused for other similar use cases. 
(Don't we have it somewhere? I recall this behaviour for successful build comment -- currently turned off by default.)

We can either check the last comment or limit the commenting to one per "event" (=push, opening the pr,..).

**Comment by lbarcziova** [comment]
> If we want to preserve commenting on the issue, this can be reused for other similar use cases.
(Don't we have it somewhere? I recall this behaviour for successful build comment -- currently turned off by default.)

Yes, somehow similar is [the commenting on successful build](https://github.com/packit/packit-service/blob/d2fe54a117da05849eeef893b4ca20b7cc01d3a9/packit_service/worker/handlers/copr.py#L342), we could definitely factor it out (e.g. directly to StatusReporter) and reuse for more use-cases.
