### ISSUE TITLE
Feedback from Keylime

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1702]
TODO:

* [ ] Gather basic information about the project, team and their usage of Packit before the interview.
* [ ] Ask Karel Srot (RH) if he is willing to participate.
* [ ] Setup a meeting with the relevant people and invite the Packit team as well.
* [ ] Clone the [feedback template](https://docs.google.com/document/d/1EMWfundO0o8yKfJfpfCLJy1LMnBZaTCSlENB5UB7_kY/edit#heading=h.gc63dnsnvg24). (Enhance if needed.)
* [ ] Lead the session and fill the feedback form (or ask someone to help you with that).
* [ ] Make sure the follow-up action items are tracked – create issues or ask the team to do it. Clearly communicate the priorities of the team/project – don't over-promise.
* [ ] Share the feedback form with the Packit team.

**Comment by lbarcziova** [comment]
Closing as Franta is in contact with the team, and we have already done multiple feedback sessions in the past and would like to focus on other epics in Q3 (we may reopen these later).
