### ISSUE TITLE
Do not create bodhi updates for Fedora 38 (rawhide as of Oct 2022)

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1712]
https://sentry.io/organizations/red-hat-it/issues/3670882387/?query=is%3Aunresolved

This is just noise in our sentry.

**Comment by lachmanfrantisek** [comment]
The sentry issue speaks about f37:

```
{"status": "error", "errors": [{"location": "body", "name": "builds", "description": "Cannot find any tags associated with build: cockpit-278-1.fc37"}, {"location": "body", "name": "builds", "description": "Cannot find release associated with build: cockpit-278-1.fc37, tags: []"}]}
```

Hasn't this been merged into another Sentry issue?

Btw, isn't this a configuration issue? (=User should use `fedora-branched` to not create Rawhide updates?)

**Comment by TomasTomecek** [comment]
ah, I assume they are merged now

you're right, it's a configuration issue: I wonder if we should help users or ignore this kind of errors
