### ISSUE TITLE
SRPM build log should point at `builder-live.log`, not `builder-live.log.gz`

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#1714]
I can see this in dashboard:
Copr SRPM build logs: [Logs URL](https://download.copr.fedorainfracloud.org/results/packit/fedora-copr-vcs-diff-lint-3/srpm-builds/04956146/builder-live.log.gz)

The thing is that `builder-live.log.gz` doesn't exist until after the build finishes.  It would be nice to point at just `builder-live.log`.  Copr is able to redirect to `builder-live.log.gz` automatically once the build finishes.

**Comment by TomasTomecek** [comment]
YES! We tried to pick the log that is available soon but clearly, we haven't selected the correct one.
