### ISSUE TITLE
Improve the permission schema for Bodhi updates

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1721]
Currently, Packit needs to ask for commit rights to dist-git to be able to create Bodhi updates.

This issue is to track the discussions/communication with Fedora infra and the Bodhi team.

These are the relevant tickets elsewhere:
* https://github.com/fedora-infra/bodhi/issues/4671
* https://issues.redhat.com/browse/PACKIT-2143
* https://pagure.io/fedora-infrastructure/issue/10763 (general request)
* https://pagure.io/fedora-infrastructure/issue/10959 (ask for a new FAS group to be created)

**Comment by lachmanfrantisek** [comment]
We were given [global Bodhi rights](https://accounts.fedoraproject.org/group/bodhi_update_bots/) so we don't need dist-git commit rights anymore. So, it's on us now to:

* [ ] Check that it really works both for `packit` and `packit-stg`.
* [ ] Improve the code to not ask for that (=remove the unneeded code).
* [ ] Either automatically, or manually get rid of the dist-git rights we've already been given.

**Comment by mfocko** [comment]
It seems that the created group was not added to the Bodhi deployment playbooks

PR with fix: https://pagure.io/fedora-infra/ansible/pull-request/1285
Follow-up: https://pagure.io/fedora-infrastructure/issue/10959#comment-833133
