### ISSUE TITLE
Provide basic info about Packit usage via API

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1724]
Part of packit/dashboard#192, to be used in packit/dashboard#193

* [ ] Create a new API endpoint
* [ ] Provide a few interesting metrics about the adoption of Packit using the data from the database (target audience is our users, management,...)
  * Try to cover the usual questions we are being asked.

**Comment by FrNecas** [comment]
Inspiration for adoption metrics: https://github.com/packit/research/tree/main/adoption-metrics

**Comment by lachmanfrantisek** [comment]
Resolved in  #1823
