### ISSUE TITLE
Packit didn't detect a built Copr rpm

### ISSUE THREAD

**Issue by bocekm** [packit/packit-service#1727]
This is a bug report told mostly through screenshots, sorry :)

On the PR https://github.com/oamg/convert2rhel/pull/469 the Packit jobs for creating Copr builds started. Two and half hours later, the jobs are still incomplete even though it took mere 7 minutes to build the Copr rpms. Packit hasn't detected that.

![Screenshot from 2022-10-27 21-16-02](https://user-images.githubusercontent.com/9884110/198379659-5ae906e7-1c8c-4edf-9a0a-88765113189f.png)
https://github.com/oamg/convert2rhel/pull/469/checks?check_run_id=9146708400
![Screenshot from 2022-10-27 21-18-57](https://user-images.githubusercontent.com/9884110/198379686-75e5777f-957c-47b7-b308-3e7ff9818c03.png)
https://dashboard.packit.dev/results/srpm-builds/95258
![Screenshot from 2022-10-27 21-19-22](https://user-images.githubusercontent.com/9884110/198379712-c986ec69-5085-4046-8c73-b5514988c929.png)
https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/4994067/
![Screenshot from 2022-10-27 21-21-17](https://user-images.githubusercontent.com/9884110/198379860-6eae4f05-3a38-4f27-aa82-fb992cd33841.png)

**Comment by lbarcziova** [comment]
hi, thank you for creating an issue! Just to be sure, this happened only once on the given PR? If we lost the message from Copr, there should be still a babysitting job that would update the status, so it looks something went wrong, I will take a closer look at this.

**Comment by lbarcziova** [comment]
I haven't found the reason why the message from fedmsg was not originally processed, but I found out that we need to fix our babysitting task to handle builds in `waiting_for_srpm` state properly (currently, it handles only `pending` builds), see:
```
2022-10-27T16:56:26.585+0000 | Getting copr build ID 4994067 from DB. 
2022-10-27T16:56:27.008+0000 | The status is 'succeeded'. 
2022-10-27T16:56:27.009+0000 | DB state says <BuildStatus.waiting_for_srpm: 'waiting_for_srpm'>, things were taken care of already, skipping. 
2022-10-27T16:56:27.009+0000 | DB state says <BuildStatus.waiting_for_srpm: 'waiting_for_srpm'>, things were taken care of already, skipping.
2022-10-27T16:56:27.009+0000 | DB state says <BuildStatus.waiting_for_srpm: 'waiting_for_srpm'>, things were taken care of already, skipping. 
```

TODO:
- [ ] update the [method that should update the Copr builds](https://github.com/packit/packit-service/blob/15b3ca9f14b35cf856ada2b9f55f2bcd62106bba/packit_service/worker/helpers/build/babysit.py#L156):
   - [ ] do not skip builds in `waiting_for_srpm` state
   - [ ] currently, we check only `ended_on` field from the Copr API and run the CoprBuildEndHandler if it is not None, but in case the last state in our DB is `waiting_for_srpm`, we could check `started_on` (if `ended_on` is None) and update both `SRPMBuildModel` and `CoprBuildTargetModel`s via running CoprBuildStartHandler if `started_on` is not None
