### ISSUE TITLE
splunk: ingest logs from httpd

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1740]
Just investigated an issue that Packit did not react to a tag-push/release. Splunk logs yielded 0 issues. The problem was that we discarded the event already in httpd.

Let's put those logs into splunk as well.

**Comment by jpopelka** [comment]
Moved to packit-service.
We first need to update it to send logs to syslog. ([the way we do this in worker](https://github.com/packit/packit-service/blob/96a59e7b1ca4ecf2c68633ec64ff4f01a9f5cea0/packit_service/worker/tasks.py#L74))
