### ISSUE TITLE
Pull-request commit status not updated

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#1758]
GH status still appears pending.

![Screenshot_20221114_170402](https://user-images.githubusercontent.com/3277839/201707791-e50b5453-1eaf-42cc-be7b-1107c963e9ae.png)

Example pull request: https://github.com/rpm-software-management/mock/pull/1005
Run: https://github.com/rpm-software-management/mock/pull/1005/checks?check_run_id=9475091496
Points to: https://dashboard.packit.dev/results/copr-builds/524282

That points to Copr build which has been in succeeded state for 2 hours:
https://download.copr.fedorainfracloud.org/results/packit/rpm-software-management-mock-1005-mock-core-configs/fedora-rawhide-x86_64/05035714-mock-core-configs/builder-live.log.gz
https://copr.fedorainfracloud.org/coprs/packit/rpm-software-management-mock-1005-mock-core-configs/build/5035714/

**Comment by lbarcziova** [comment]
Hi, thanks for reporting!

I checked the logs and hopefully, this bug should be fixed by [this commit](https://github.com/packit/packit-service/pull/1731/commits/6ec14091098949b4cd54456aad599b081b17843b) which got into production today. 

Let us know if you bump into this issue again.

**Comment by lbarcziova** [comment]
I hope it is fine now. If this will happen, feel free to re-open this issue.
