### ISSUE TITLE
Remove type-checking workaround from models

### ISSUE THREAD

**Issue by FrNecas** [packit/packit-service#1779]
This [workaround](https://github.com/packit/packit-service/blob/main/packit_service/models.py#L255) should no longer be necessary based on the linked github issue. We just need to import [sqlalchemy-stubs](https://github.com/dropbox/sqlalchemy-stubs/). There will, however, be some extra typing changes necessary (mypy now produces some errors).

**Comment by majamassarini** [comment]
We have lost the pointer to the code snippet.
