### ISSUE TITLE
implement SLO1.2: "1st status set within 15 seconds"

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1782]
definition: 1st "queued"/"accepted" status is set in at most 15s

* [ ] implement (you can get inspired: https://github.com/packit/packit-service/compare/main...TomasTomecek:packit-service:fix1782 )
* [ ] update packit.dev docs
* [ ] visualize in grafana

_Originally posted by @TomasTomecek in https://github.com/packit/packit-service/issues/1728#issuecomment-1327418522_

**Comment by majamassarini** [comment]
See architecture meeting topics in 2023/03/16
