### ISSUE TITLE
Fedora-review can run on Copr builds seamlessly

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1805]
[`fedora-review`](https://pagure.io/FedoraReview) is the tool to run on newly added packages into Fedora Linux.

Though not many folks run it again after the package is part of Fedora. Let's provide `fedora-review` results to Packit users easily.

Details:
http://frostyx.cz/posts/running-fedora-review-after-copr-build
https://pagure.io/FedoraReview/pull-request/463

**Comment by lachmanfrantisek** [comment]
František to think about and probably close it. We don't see much benefit for the sure compared to the required setup.

**Comment by lachmanfrantisek** [comment]
After discussing with Jakub, the number of projects in review is interestingly high and we might help here. František plans to bring relevant people together and try to think about some improvements. We most probably won't have any action items soon. I am closing this issue and will create more specific ones when/if needed.
