### ISSUE TITLE
Allow manual-only job triggering

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1806]
TODO:
- [x] introduce a new bool configuration option `manual`/`manual_trigger` (default False)
   -  add this to the [schema](https://github.com/packit/packit/blob/672eac32fd4f03f53ea5df760c2c48c6086feb7c/packit/schema.py#L434)
   -  add this to the [configuration class](https://github.com/packit/packit/blob/672eac32fd4f03f53ea5df760c2c48c6086feb7c/packit/config/job_config.py#L53)
- [x] filter the events based on the new job configuration option:
   - [here](https://github.com/packit/packit-service/blob/38d6158d1b718a079d4b08c35bbd69caf2e7859b/packit_service/worker/jobs.py#L654) is the code that gets the handlers for the particular events (e.g.comment, push)
     - (we are matching the trigger of the [DB object](https://github.com/packit/packit-service/blob/38d6158d1b718a079d4b08c35bbd69caf2e7859b/packit_service/models.py#L1087) corresponding to the event and the trigger defined in the configuration and then working with the mapping to handlers defined via decorators of the handler classes, [example](https://github.com/packit/packit-service/blob/38d6158d1b718a079d4b08c35bbd69caf2e7859b/packit_service/worker/handlers/testing_farm.py#L70))
- [ ] implement this for the dependant jobs as well (build -> test)

More details: https://docs.google.com/document/d/1UTaOctS-ueJ9KtDrh0C-OY_IpFY4vcsFtONJ4kOd88U/edit

Related-ish: https://github.com/packit/packit-service/issues/1754

**Comment by lachmanfrantisek** [comment]
Maybe a more generic `comment_only`/`manual_trigger`/... flag for all the jobs.

**Comment by evgeni** [comment]
We (@theforeman) would also be interested in this :)

**Comment by lbarcziova** [comment]
Reopening, as I was testing this and found out this would still be an issue for dependant jobs, e.g. build-> test ([example](https://github.com/packit/hello-world/pull/1464)).

When reporting the build end, we automatically trigger the followup tests [here](https://github.com/packit/packit-service/blob/main/packit_service/worker/handlers/copr.py#L394).

Regarding the implementation, we could either not run the tests as a reaction of build ends if the tests have the `manual_trigger` configured. But the UX could be worse, e.g. when running `packit test`,  if some builds would be missing, the user would need to run the command twice.

More complex solution would include storing the information about the type of the event that triggered the action in the DB and then utilise that.

**Comment by lbarcziova** [comment]
We decided we will start with the less complex solution, adding the condition to check the test job for manual trigger option [here](https://github.com/packit/packit-service/blob/ad58a22c36f4609f452b847248b6f5dee2ddb111/packit_service/worker/handlers/copr.py#L400).
