### ISSUE TITLE
Add tmt plans/tests for packit-service

### ISSUE THREAD

**Issue by FrNecas** [packit/packit-service#1819]
When I was working on https://github.com/packit/specfile/pull/164 , I realized that the functionality of packit-service depends on packit, and therefore on specfile. Therefore, running p-s tests during specfile PRs could be useful but we need to provide tmt test definition so that the tests can be imported.

**Comment by TomasTomecek** [comment]
This could be an overkill. Although I'd say we should try this out and see if we can catch more things before merging/deploying.

**Comment by lbarcziova** [comment]
We have agreed to close this as it is probably an overkill and we will not have the capacity to complete this any time soon.
