### ISSUE TITLE
worker-short-running is a memory hog

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1824]
After bumping our base image to F37, the `worker-short-running` leaks memory and is periodically OOMKilled and restarted.

![Screenshot from 2023-01-03 19-05-44](https://user-images.githubusercontent.com/288686/210417752-b7639780-8f71-4fa7-b862-ce6cd4adbb26.png)

The `worker-long-running` is OK so it's just the multi-threaded one.

We can try the other thread pool, i.e. `eventlet` instead of [`gevent`](https://github.com/packit/packit-service/blob/main/files/run_worker.sh#L44).
We can also experiment with [setting some options](https://docs.celeryq.dev/en/stable/userguide/optimizing.html#memory-usage), but they seem to be [supported only by the `prefork` pool](https://docs.celeryq.dev/en/stable/userguide/workers.html#max-tasks-per-child-setting).

Also read through celery/celery#4843 (EDIT: that seems to apply only to `prefork` pool and `RabbitMQ` broker)

**Comment by TomasTomecek** [comment]
thank you for creating this, was about to do the same :D

I stumbled upon [Memory leak in run Celery Django, Gevent strategy with Multi Worker](https://stackoverflow.com/questions/74088690/memory-leak-in-run-celery-django-gevent-strategy-with-multi-worker) but it doesn't seem related: I couldn't find any warning in the celery startup.

**Comment by jpopelka** [comment]
I tried the `eventlet` pool (#1825)  end there were some PostgreSQL issues so that's not a way.

F37 contains celery-5.3.0b1, while F35 had celery-5.2.6 so I built a worker image with [5.2.6 from PyPI](https://github.com/jpopelka/packit-service/commit/166b9bc5eb7796ca2a1d9444cd1509d628e2ed3c) (rpm can't be installed because of dependencies) and I'm now running it on `stg`.
