### ISSUE TITLE
Implement retriggering of pull from upstream

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1829]
To be consistent with other jobs, people should be able to retrigger `pull_from_upstream` job as well.

- [ ] discuss and decide where this should be possible (e.g. via issues in dist-git, issue_repository, see #1536)
- [ ] implement it
- [ ] document it

**Comment by lbarcziova** [comment]
Ideas from the architecture on where to trigger the pull from upstream:
- issue in dist-git repo
  - enabling the issue tracker via web UI doesn't seem to work
- comment in (any) dist-git PR (we already react to these)

Outcome: do it via dist-git comments.

**Comment by ptoscano** [comment]
> Ideas from the architecture on where to trigger the pull from upstream:

A possible another way: running `packit pull-from-upstream` while being in a dist-git clone.

**Comment by nforro** [comment]
> A possible another way: running `packit pull-from-upstream` while being in a dist-git clone.

That wouldn't be so easy to implement, packit CLI is not a client for Packit Service, I guess we would have to implement an (authenticated?) API endpoint in Packit Service for that.

**Comment by lbarcziova** [comment]
@ptoscano but if you would be interested in a CLI command, there is the [packit propose-downstream](https://packit.dev/docs/cli/propose-downstream/) that can be run in the upstream clone (but it requires user's credentials)
