### ISSUE TITLE
Copr build babysit waiting for all chroots to finish

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1836]
As I was checking the new metrics for reporting Copr build end time, I found an occurrence of setting the status after **400** minutes. The metrics are measured by checking the current time (when reporting) and `ended_on` for the particular build chroot ([see](https://github.com/packit/packit-service/blob/fa781e7206edbc0b2abb7a646ee905b7917d9c80/packit_service/worker/handlers/copr.py#L222)).

I checked the logs and realised that in babysit task, we query the build API (whole build, not chroot) and check the `ended_on` for that one ([see](https://github.com/packit/packit-service/blob/fa781e7206edbc0b2abb7a646ee905b7917d9c80/packit_service/worker/helpers/build/babysit.py#L192)). Therefore, in the particular case, we probably missed a fedmsg message for a chroot build that had already ended, but babysit task set the missing statuses after all the build chroots were done (see here the `fedora-36-i386` check time https://github.com/osandov/drgn/runs/10543992388 and logs for that chroot in https://copr.fedorainfracloud.org/coprs/g/meta/drgn/build/5210049/).

**Comment by TomasTomecek** [comment]
How do you suggest resolve this?

**Comment by lbarcziova** [comment]
I firstly wanted to discuss this within the team, but to me, it would make sense in babysit tasks to check the `ended_on`  for the particular build chroot.

**Comment by TomasTomecek** [comment]
agreed, we're indeed more interested in finishing a chroot build instead of knowing that all builds are done; nicely spotted!
