### ISSUE TITLE
No scripts in the deployment

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#1843]
I was going to check ‹propose-downstream› workflow on the GitLab, so to avoid as much _nuisance_ as possible, I went to approve my own namespace _prematurely_, only to find out that we don't have scripts neither in any of the workers or the service pod.

- [x] path to scripts hasn't changed
- [x] Ansible task that takes care of the installing didn't change

TODO:
- [ ] „somehow“ install the scripts again…

Remarks:
- [ ] there's also a `'['` file in the `/usr/bin`, so I guess something (more than likely script) is screwed…
- [x] right now mostly affects the GitLab approvals from our side

**Comment by TomasTomecek** [comment]
```
$ ls -lha -- '/usr/bin/['
-rwxr-xr-x. 1 root root 57K jan  2 13:55 '/usr/bin/['

$ rpm -qf  '/usr/bin/['
coreutils-9.1-7.fc37.x86_64
```
my system :) `[` is a regular binary

you're right that allowlist.py is missing, though I swear it was there last week

**Comment by TomasTomecek** [comment]
```
TASK [Install scripts] *********************************************************
task path: /src/files/recipe-worker.yaml:27
[WARNING]: Unable to find 'scripts' in expected paths (use -vvvvv to see paths)
skipping: [localhost] => {
    "changed": false,
    "skipped_reason": "No items in the list"
}
```
