### ISSUE TITLE
Database improvements: revisit the approach (spike)

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1864]
Let's spend some time going through [the original research](https://github.com/packit/research/pull/128) once a few steps have been implemented and make sure that the original approach is still valid and we can commit to finishing that.

The task of this issue is:
* [x] go through  [the original research](https://github.com/packit/research/pull/128)
* [x] take a look at the current state of the database schema
* [x] if needed, suggest any improvements to the plan (change/create/close issues; you can also update/enhance the original research)
  * #1985 
  * #1986 
  * updated #1773 
* [ ] probably do it as a hands-on session (meeting on Thursday)

**Comment by mfocko** [comment]
Based on this article, I can imagine pipelines being implemented in a similar fashion: https://dev.to/tommydreamer57/how-functions-and-composite-types-changed-the-way-i-use-postgresql-7a2
And sqlalchemy has support for these if I'm not mistaken.

suggested by @csomh
