### ISSUE TITLE
Remove last signs of building SRPMs outside copr

### ISSUE THREAD

**Issue by FrNecas** [packit/packit-service#1866]
I think that now as we switched to SRPMs in Copr, `wait_for_srpm` should be always `True`; we should have removed this already, so we can do a follow-up PR to not add more work to you

_Originally posted by @lbarcziova in https://github.com/packit/packit-service/pull/1787#discussion_r1087676159_

**Comment by csomh** [comment]
Don't we still need the ability to build SRPMs outside of Copr in order to support building in Koji?

**Comment by lbarcziova** [comment]
Yes, but my comment was related only to SRPMs for Copr.
