### ISSUE TITLE
Share the blogpost about pull from upstream

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1869]
The goal of this issue is to share [this blog post](https://packit.dev/posts/pull-from-upstream/) with the relevant audience so that more people get to know this job and can try it.
Think about where we should write and/or discuss with the team.

Suggestions from @TomasTomecek :
- devel@fedoraproject.org
- rhel-devel

**Comment by lachmanfrantisek** [comment]
Please, provide also a TLDR version for the email body.

Mirek will create a follow-up card to prepare a workshop.

**Comment by mfocko** [comment]
Release after packit-service#1879
