### ISSUE TITLE
Workshop about pull-from-upstream

### ISSUE THREAD

**Issue by xsuchy** [packit/packit-service#1878]
As a follow-up of #1869 it would be great if we could have a workshop or even more workshops on how to set up and use pull-from-upstream.
Let's start with core-services team. And maybe record it and share the recording publicly. Or create a demo recording based on the workshop.

**Comment by lachmanfrantisek** [comment]
The offline workshop happened today in the Brno office and was quite successful :rocket:

We still plan to do a new round online and in public, but let's mark this as done and create a separate card for the next one.
