### ISSUE TITLE
Everyone can easily contribute to packit-service

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1880]
Since all sources of Packit GitHub app are open, let's continue towards [open source service](http://stef.thewalter.net/open-source-services.html) concept by making it easier for everyone to contribute.

<details><summary>Old confusing motivation</summary>
Keeping this paragraph for sake of transparency, thanks Hunor for pointing it out.

All our code, deployment recipes, app metadata, documentation is open. The deployment itself (i.e. the cluster) is not for obvious reasons. Metrics are also not open. Hence we meet the criteria for Packit GitHub app to be a truly [open source service](http://stef.thewalter.net/open-source-services.html).</details>

The goal of this issue is to make packit-service more friendly to receive contributions from the public.

We also want to provide info on what exact code (git hash) it is running for all our git repos. One can then navigate and browse sources of code that is running live: both prod and stg.

TODO:

- [ ] The REST API provides info (commit hash, or git tag) of what exact code it's running
- [ ] Check run descriptions have links how anyone can contribute to Packit GitHub app
- [ ] (optional) create follow-up cards or provide additional ideas or proposals what we can improve

**Comment by csomh** [comment]
Do you mean: "Hence, we **do not** meet the criteria..."?

**Comment by TomasTomecek** [comment]
Thanks for the pointer, I am going to reword the first paragraph, agreed it is confusing. The main problem is that we don't have a precise definition of what "open source service" is, the Stef's blog is just a pitch.

**Comment by majamassarini** [comment]
The first point is already done. We should change the others points in a more actionable way. We close this issue for now.

**Comment by lachmanfrantisek** [comment]
Add first point, this was as part of some "Open Source Services" stuff, like the info popup on our dashboard and a semaphore task like: https://packit.dev/development/how-open-is-this-service#-open-assets

![image](https://github.com/user-attachments/assets/35052b1d-e958-45aa-9793-ddc2eb72f6f6)
