### ISSUE TITLE
Add reverse-dep-hardly-tests

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1895]
which would run [hardly tests](https://github.com/packit/hardly/blob/main/files/zuul-tests.yaml) in a similar same way [ogr runs packit tests](https://github.com/packit/ogr/blob/main/.zuul.yaml#L33) and [packit runs packit-service tests](https://github.com/packit/packit/blob/main/.zuul.yaml#L64).

**Comment by mfocko** [comment]
Do you think we could try this with TF?

**Comment by lachmanfrantisek** [comment]
Hardly is currently not a priority for us. If we find source-git important again, we can easily re-open and hopefully, we could use TF as Matěj has suggested.
