### ISSUE TITLE
RFE: `Built only for` in custom copr project's package settings should override default targets

### ISSUE THREAD

**Issue by lsm5** [packit/packit-service#1903]
We have a custom copr project intended for podman and related tools at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/ with default targets set for many arches.

But for noarch packages like `container-selinux`, we have limited the arch to only x86_64 using the `Built only for` field in package settings so that we could reduce the number of packit tasks. See: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/package/container-selinux/ . I'm hoping not to set any targets in .packit.yaml itself to keep it as simple as I can.

But that field currently seems to get ignored as builds are triggered on all arches: https://github.com/containers/container-selinux/pull/204 .

**Comment by lbarcziova** [comment]
hi @lsm5 ! Is this still relevant for you?

**Comment by lsm5** [comment]
No, haven't felt the need since we switched to ephemeral coprs for `trigger: pull_request` . Closing...

**Comment by lbarcziova** [comment]
Thanks for confirming, feel free to reopen if this becomes needed for you!
