### ISSUE TITLE
Check if the repo is private only when the pipeline is started

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1942]
In order to reduce the number of GitHub API calls made during a pipeline run, check [whether the GitHub repository is private](https://github.com/packit/packit-service/blob/1418828a035d98a600bbea8c09051eed24c40919/packit_service/worker/jobs.py#L156) (or enabled for private runs) only once: when the pipeline is created.

See packit/research#171 for more details.

**Comment by lachmanfrantisek** [comment]
Still relevant, but not urgent.
