### ISSUE TITLE
Don't update test flags while builds are still in progress

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1943]
Currently both the flags for the builds and tests are updated with the build status while the builds are running. Save a few GitHub API calls by updating the test flags less often:

- Set a "Waiting for RPMs to be built..." message on the test flags when the Copr builds are started.
- Do not update them as the builds are transitioning throughout the different stages, but only when the tests are submitted.

See packit/research#171 for more context.

**Comment by lbarcziova** [comment]
We have discussed with @lachmanfrantisek that this behaviour could also be configurable, defaulting to the old one to not make the UX worse. With that, only the affected users (by the Github API rate limit) could configure this.
