### ISSUE TITLE
Allow counting the GitHub API calls made from the service

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#1944]
Allow providing a metric collector object as an argument to be passed down from Packit Service, to Packit, to ogr, to PyGithub, and count the number of times the GitHub API is called from the service and the workers. This could be 2 separate Prometheus counters.

This work will impact several repositories, but probably needs to be done at once in order to make sense.

Going through the whole flow:

In packit-service GithubProjects are obtained with
`ServiceConfig.get_project()`. This method (implemented in
`packit.config.config.Config`) will need to be updated to take a
`github_call_counter` object and pass it down to `ogr.get_project()`.

Here `ogr.factory.get_project()` would pass it down to `GithubService` which
then would pass it down to `GithubProject`, which then would pass it down to
the PyGithub `Github` object, so that it can be used as [a new property of the
`Requester`], in order to be able to pass it to the connection, and
incremented every time [a response is received].

Patching PyGithub could be done while building the service and the worker
images. The patches could be also submitted upstream, to get some feedback on
the approach and maybe incorporate them in PyGithub.

See packit/research#171 for the broader context.

**Comment by majamassarini** [comment]
We don't have enough capacity at the moment for this.
