### ISSUE TITLE
Packit is blocked by rust crates.io for download crate tarball

### ISSUE THREAD

**Issue by cathay4t** [packit/packit-service#1948]
In https://github.com/rust-netlink/netlink-sys/runs/11770471551 , we noticed a 403 error when downloading the rpm source tarball from https://crates.io/api/v1/crates/netlink-sys/0.8.5/download#/netlink-sys-0.8.5.crate .

Manually download that URL works well.

According to https://github.com/rust-lang/crates.io/issues/1361 , it seems your bot is retrying to frequent which caused this block.

Any idea.

**Comment by lbarcziova** [comment]
Hi @cathay4t, thanks for reporting!

Firstly, I can see that you had before configured both `pull_from_upstream` and `propose_downstream` jobs. I see now you removed the configuration in GitHub, so just to clarify, they cover the same functionality, the difference is that the `propose_downstream` is configured in GitHub and reacts to the GitHub webhooks about the new release and the `pull_from_upstream` reacts to upstream-release-monitoring messages (which means there is usually some delay) and is configured in the dist-git repo directly so you do not have to touch the GitHub repository.

As for the downloading and retrying: if we are not able to download the source tarball, we retry after 1 minute and then after 2 minutes, these retries are meant for use cases when the source is being uploaded e.g. to some package manager or other place and is not done yet when we receive the GitHub webhook about the new release. With `pull_from_upstream` this is less probable to happen, as there is some delay. This time limit seems quite sensible to me. 
We also utilise some auto-retries that happen in seconds. 

But we could probably bump into this issue again if e.g. processing multiple packages that require downloading sources from crates.io at a time.

I will add this to discuss at our team meeting tomorrow and will provide updates on this.

**Comment by TomasTomecek** [comment]
We discussed this thoroughly and even did a few experiments.

I personally checked how can we obtain the archive without accessing crates.io API, I'm assuming the API endpoint has those strict rules. My assumption was the archives will be on a cold CDN storage. Let's try:
```
$ curl -v https://crates.io/api/v1/crates/aleph/0.0.1/download
...
< HTTP/2 302
< location: https://static.crates.io/crates/aleph/aleph-0.0.1.crate
...
* Issue another request to this URL: 'https://static.crates.io/crates/aleph/aleph-0.0.1.crate'
*   Trying 151.101.37.91:443...
* Connected to static.crates.io (151.101.37.91) port 443 (#1)
...
< content-type: application/x-tar
< server: AmazonS3
< content-length: 312
```
Yup, the tarballs are on AWS S3.
```
$ dig static.crates.io
;static.crates.io.              IN      A
static.crates.io.       214     IN      CNAME   fastly-static.crates.io.
fastly-static.crates.io. 5      IN      CNAME   n.sni.global.fastly.net.
n.sni.global.fastly.net. 5      IN      A       151.101.37.91
```

One thing that could help here would be to set `static.crates.io` as the Source0 in the spec files to bypass the crates.io API and directly access the archives.

**Comment by decathorpe** [comment]
> One thing that could help here would be to set `static.crates.io` as the Source0 in the spec files to bypass the crates.io API and directly access the archives.

1. The S3 URLs are probably not stable.
2. Using `%{crate_source}` macro (which expands to the crates.io API endpoint for the download) is mandatory:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_package_sources_2

In my years of doing Rust packaging, I have never hit the API rate limit for crates.io endpoints ... but rust2rpm properly sets the HTTP user agent. That packit does not set a user agent for HTTP requests seems like an oversight to me ...

**Comment by lbarcziova** [comment]
With the morning's production update, we should now be able to download the tarball. Therefore closing this.
