### ISSUE TITLE
Request new feature: Auto merge PR of dist-git once CI passed

### ISSUE THREAD

**Issue by cathay4t** [packit/packit-service#1949]
By providing a job(e.g. `auto_dist_git_pr_merge`) which automatically merge dist-git PR based on CI results, we can have a human-free auto build system:
 * `pull_from_upstream` create dist-git PR.
 * `auto_dist_git_pr_merge` merge PR after CI passed.
 * `koji_build` create rpm build on dist-git commit.
 * `bodhi_update` create bodhi on koji build finish.

**Comment by nforro** [comment]
Hi, we are already tracking this here: https://github.com/packit/packit-service/issues/1723
Feel free to comment there and let me close this issue as duplicate.
