### ISSUE TITLE
Support specifying branch in `/packit test $repo $branch`

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1968]
The syntax is to be decided.

@fernflower requested to support specifying branches in our `/packit test $repo#$pr` trigger. This RFE should extend the existing funcionality where you can specify PR, with this addition, branch can be specified as well.

**Comment by fernflower** [comment]
Thank you!

**Comment by TomasTomecek** [comment]
I am including two more comments from Ina from our recent discussion on slack (now that I re-read it again) and would like to 100% confirm this request is correct

> Now we have '/rerun' for leapp PRs, that will build leapp-pr-version and fetch leapp-repository*master; while '/rerun 4242' will build leapp-pr-version, build leapp-repository*4242*, and pass both as test artifacts to testing farm.

> So it's not about enabling leapp package installation by specifying additional repos (which is what additional_repos is about iiuc). It is about "how do I instruct packit to run tests with both leapp-from-pr-build and leapp-repository-master-or-the-version-user-specified"

Do I understand correctly that you have 3 test scenarios?

|Mode|leapp|leapp-repo|
|----|----|----|
|default|leapp from PR | latest released leapp-repo |
|on demand|leapp from PR | leapp-repo build from master |
|on demand|leapp from PR | specific build of leapp-repo |

default is run when a PR in leapp is created
on demand are triggered with a comment in a PR
