### ISSUE TITLE
Research package dependencies

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#1994]
As a first step of the #1993 epic, we need to research all the use cases:

TODO:
* [ ] Write down various use cases across the whole Packit platform where package relation is important.
* [ ] For each use case, provide an example package(s) (ideally, ask the maintainer/developer if they want to collaborate on this with us) and what are the expectations.

---
*This is a part of the #1993 epic*

**Comment by majamassarini** [comment]
Following some question I would dig further in this research:
- [ ] which kind of triggers do we need for a propose-downstream in a monorepo? Is it ok to release all the packages listed in the downstream job for a new release tag? Do we need to filter them out in some way? Using the version template? Is this already working with our code base? And if the release tag is the same for all the packages?
- [ ] Do we need dependencies between packages inside the same job?
- [ ] Do we need dependencies between different jobs and different packages in the same monorepo? Like do we need to wait for the bodhi update of one package before starting working for the propose downstream of another package?
- [ ] Do we need to group packages together inside the same Job, like do we need to do a single bodhi update for multiple packages?

**Comment by lachmanfrantisek** [comment]
The original epic got closed for being outdated and we have other cards to track this.
