### ISSUE TITLE
Packit doesn't react to `/packit build` in commit messages

### ISSUE THREAD

**Issue by nikromen** [packit/packit-service#1999]
After I did a first push into branch, packit tried to build in Copr project I specified and correctly requested builder permissions. However in the comment it tells you to choose from two options:

1) try /packit build
2) try clicking on re-run button

I tried the first option but it seems like packit completely ignores this type of comments (even :eyes: emoji is not there)

the commit with comments for reference:
https://github.com/alpa-team/test-autoupdate/commit/f58fcae33cf057ae124f9effd2c123c902ec61e6

**Comment by lbarcziova** [comment]
hi @nikromen! Sorry for ignoring this issue, do you still remember the details around it? (link no longer works)
Was this Packit reacting to a `commit` trigger? Would a clearer message (make sure it is clear that the `packit build` comments work only in PRs) here be sufficient?

**Comment by nikromen** [comment]
> link no longer works

ah... yep it was a reaction to `commit` trigger. It happened in the first push to the branch (from the packit's view) when packit requests permissions to the copr repo and gives a comment about it. In the comment, packit gives user options to retrigger build - via comment or via button - but the comment is ignored.

> Would a clearer message (make sure it is clear that the packit build comments work only in PRs) here be sufficient?

deletion the part that is telling user to comment `/packit build` would solve this :beer:

**Comment by nikromen** [comment]
I have currently a project with copr repo but without correct packit permissions so I can provide the link to the example again https://github.com/nikromen/pyvem/commit/e5e85275a035754a38f78c07cec1faa3a9ec0634

**Comment by lbarcziova** [comment]
sure, thanks @nikromen for the details! You are right, we should definitely improve the UX here.
