### ISSUE TITLE
aarch64 Testing Farm composes does not need to be suffixed

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2028]
The `aarch64` composes used to be named differently because of what we have to behave specifically for those:

TBD

This is no longer true and we can use the same compose names for `aarch64` as well. Both names are possible for now but will be deprecated.

TODO:
* [ ] Remove the specific handling for `aarch64`.
* [ ] Enhance tests to cover that change.
* [ ] Let @thrix know we're done

Here is an example provided by @thrix :

```
❯ testing-farm-public request --git-url https://gitlab.com/testing-farm/tests --plan /testing-farm/sanity --compose CentOS-Stream-9 --arch aarch64
📦 repository https://gitlab.com/testing-farm/tests ref main test-type fmf
💻 CentOS-Stream-9 on aarch64 
🔎 api https://api.dev.testing-farm.io/v0.1/requests/a3dc8251-7a2d-40b6-984d-289c9a6ef79f
💡 waiting for request to finish, use ctrl+c to skip
👷 request is queued
🚀 request is running
🚢 artifacts https://artifacts.dev.testing-farm.io/a3dc8251-7a2d-40b6-984d-289c9a6ef79f
✅ tests passed
```

**Comment by thrix** [comment]
This is now a bug, see https://redhat-internal.slack.com/archives/C03BRN71JAF/p1697035020889869
