### ISSUE TITLE
Research workflow engines

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2033]
To improve the state of the service and to consider work on packit/private#25 epic, we might want to research various workflow engines if there is anything we can reuse.

Related:
* https://github.com/argoproj/argo-workflows
* packit/research#183
* https://github.com/selinon/selinon
* investigate if DAG systems would help here, e.g. https://airflow.apache.org/

Consider the current architecture of the service and the state needed for the packit/private#25 (=for Packit to act as a CI management service).

**Comment by majamassarini** [comment]
The outcome should answer this questions:

1. How are job dependencies managed in other services? Is there an existing framework solution for running the jobs?
2. Compare our solution with others on how using Celery.
3. Is anyone using the Flower frontend for Celery? (we just use flower for the metrics not its UI)
