### ISSUE TITLE
Add endpoint response data to Swagger API endpoint

### ISSUE THREAD

**Issue by SpyTec** [packit/packit-service#2062]
### Description

Currently all API endpoints in the Swagger doc show what endpoints exist, but not much apart from that. To find out what the endpoints return we have to go visit them and make assumptions if we wish to use them. This creates a bad situation as some variables can be null but is set most of the time -- that happened for me over on the dashboard side as I didn't know url could be `null` https://github.com/packit/dashboard/issues/254

There is a marshal feature within Flask RESTx that might be usable, but I have not checked myself it this is doable or if it will generate the API response data types for us, though I assume it will
https://flask-restx.readthedocs.io/en/latest/api.html#flask_restx.marshal_with

### Benefit

This will help us develop the service and dashboard more separately as the API will be better documented, and also help with newcomers who want to improve something to the dashboard or make use of something from Packit service itself	

### Importance

Not super important, but would be a very nice to have for the DevConf workshop 

### What is the impacted category (job)?

General

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by majamassarini** [comment]
Hi @SpyTec,

I am working on this card (you can give a look to PR #2089) but I am not sure my work will solve the problem you had with our API.
I am not able to specify, through `flask_restx`, that a field could be `null/None` or at least I did not find a way for it.
I can say whether the field is `required` or not, but this is something different I think, in our case most of the fields are always exported (that for me means they are `required`) even though they are `null/None`.

The only way I see to export this information is to drop the field in the response when it is `None` with the `flask_restx` option `skip_none`, in this way all the fields which can be None will automatically be not `required` anymore. But, in doing so, I will change our API.

I don't know if you have suggestions/opinions to give me and I don't know if I got the problem properly.

Thanks!

Maja

**Comment by SpyTec** [comment]
Weird 🤔 

How does the Swagger look like with the changes when it comes to fields that could be null?

Otherwise, I found this -- which is weird given that the projects have existed for a while
https://stackoverflow.com/a/63500834

**Comment by majamassarini** [comment]
Hi, sorry for the delay!
I don't think I need to customize the class, the `null` values are already going through the marshaling, you can see them here.
![Screenshot from 2023-06-13 09-48-43](https://github.com/packit/packit-service/assets/2678400/c513d96e-6c98-4f6d-ab92-c84477d90fa1)

But I don't have a good way to expose them in the examples, here for example you can see I set the `branch_name` to `null` and it appears like a string:
![Screenshot from 2023-06-13 09-49-05](https://github.com/packit/packit-service/assets/2678400/adbee0b6-39d9-4661-9be1-8a89eab55e96)

However I can write in all the examples if the string could be also `null` even though it will not appear that good.

**Comment by SpyTec** [comment]
It could be possible that the custom class allows the examples to show null as well

**Comment by majamassarini** [comment]
Finally I have tested this and I don't think the class above is doing much.

The `web_url`, `ref` and `branch_name` are `NullableString` but in the example you can't understand it.

![Screenshot from 2023-06-22 10-34-21](https://github.com/packit/packit-service/assets/2678400/35c15764-1bba-408e-985f-c03a27cd41fc)

If you inspect the model you can see that they can be both `string` and `null` but this is shown in a weird way and I think it is not so visible.

![Screenshot from 2023-06-22 10-34-07](https://github.com/packit/packit-service/assets/2678400/a833b11a-c5b0-4051-907c-df10c979b7f5)

Another fear I have is that using this `marshaling` feature I am not only decorating responses with docs but I am also changing the way I serialize them. I had to remove `json.dumps` from our code and now is the `flask_restx` code that serialize the content I am decorating.  If I misspelled or forgot a field this will not show up in the response.

I think this is a nice tool if we want to make our API more consistent, we can use the renaming functionality in `flask_restx` to rename fields that should appear with the same name even though in our code base they have different ones. But still I don't like that we should replicate all the field names and our serialization is based on that.

 @SpyTec what do you think?

Thanks!

Maja

**Comment by majamassarini** [comment]
We agreed with @SpyTec  to close this.
