### ISSUE TITLE
Allow explicit compose name, bypass compose validation

### ISSUE THREAD

**Issue by danmyway** [packit/packit-service#2072]
### Description

* Introduce a new bool configuration option `tf_allow_explicit_compose_name` / `tf_explicit_compose` / ... (default=False)
* Bypass the [compose validation](https://github.com/packit/packit-service/blob/05569322d21c5c71e4ea55604f398473bc30ec22/packit_service/worker/helpers/testing_farm.py#L652) and [here for internal tf](https://github.com/packit/packit-service/blob/05569322d21c5c71e4ea55604f398473bc30ec22/packit_service/worker/helpers/testing_farm.py#L626)
* set `compose = compose` if explicit name option set to True

Context:
With the effort to test conversion cloud images in convert2rhel, we have proceeded with making the mapping in Testing Farm configuration more generic (maps through regex).
This matches to an explicit official AMI name.
These images unfortunately won't land in any of the compose lists, so the effort to dispatch jobs through packit fails on the [compose validation](https://github.com/packit/packit-service/blob/05569322d21c5c71e4ea55604f398473bc30ec22/packit_service/worker/helpers/testing_farm.py#L652) in the testing_farm helper.
The current workaround suggested by @lachmanfrantisek is overriding the `compose` in `tf_extra_params`.
This solution works, but would yield unsatisfactory results in the future, when we introduce support for conversions to RHEL 9.
We still need to set the `distros` to some known value to satisfy the compose validation against available_composes.
This would get confusing with target distro set to oraclelinux-8 (which would appear in the packig job check name) and overriding the compose value to the desired OL9.x

### Benefit

* Allow testing official cloud images
* Upstream transparency in the cloud testing efforts (official image name to be seen in the packit job check instead of ambiguous alias)
* Possibly get rid of some workarounds to satisfy the TF compose mapping
  * for convert2rhel that would be
```
elif compose == "Oracle-Linux-7":
    compose = "Oracle-Linux-7.9"
elif compose == "Oracle-Linux-8":
    compose = "Oracle-Linux-8.6"
```

### Importance

medium

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [X] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [X] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
Hello!

Thanks for the issue! Since there is currently an easy workaround (actually, that's what `tf_extra_params` is for), we will not prioritise this but let us know once this starts to be an issue.

**Comment by lachmanfrantisek** [comment]
@thrix hello, are you ok with promoting this use-case (=using custom APIs)? Is this something you "support" or it just works?

**Comment by danmyway** [comment]
Hi @lachmanfrantisek, we are slowly leaning towards supporting conversions to RHEL9.
That is when we hit the issue hard.
We need to bypass the compose validation somehow, which is currently done by "lying" to packit and pointing the distro key to some, that is known by Packit, e.g. oracle-linux-8, which translates to Oracle-Linux-8.6.
Then we overwrite the compose key in tf_extra_params to get the desired OS provisioned by Artemis.
With 9 major release in the equation, the check name would be pretty much nonsensical.
We would again need to "lie" to Packit with requesting some compose that is recognizable by the service, and overwriting the compose key, the check would look like a RHEL8 conversion is tested, however the compose value would request RHEL9-like OS.
This value is not public facing at all, which might cause confusion.
CCing @bocekm

**Comment by danmyway** [comment]
Testing Farm is now exposing the regexes in the available composes list.
This makes the possible config option unnecessary, on the other hand, the code should be able to handle matching the requested target to the regexes on the available composes list better.

**Comment by lbarcziova** [comment]
hi @danmyway ! As you mentioned, with the support of regexes, I would say this issue is no longer necessary. The support on our side was implemented in https://github.com/packit/packit-service/pull/2168 and should be in production next Tuesday. Do you think this could be closed or would you be still interested in implementing something from the initial proposal?

**Comment by danmyway** [comment]
Awesome, I think we can close this one.
I can open another issue if something pops up.
Thank you, @lbarcziova !
