### ISSUE TITLE
pull-from-upstream: link downstream PR to dashboard's view

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#2128]
### Description

Since we provide user interface for pull-from-upstream jobs, we should link to them from the downstream PRs.

Even propose-downstream makes sense while you are at it :)

```
Upstream tag: [6.1.3](https://github.com/...)
Upstream commit: [78439ebb](https://github.com/...)
Logs: [Packit dashboard](https://dashboard.packit.dev/...)

If you need to do any change in this pull request, you need to locally fetch the source branch of it and push it (with a fix) to your fork (as it is not possible to push to the branch created in the Packit’s fork):
\```
git fetch https://src.fedoraproject.org/forks/packit/rpms/python-docker.git refs/heads/*:refs/remotes/packit/*
git checkout packit/6.1.3-rawhide-update-pull_from_upstream
\```
```

### What is the impacted category (job)?

Fedora release automation

**Comment by lbarcziova** [comment]
Agreed that people often do not know about the dashboard and this could help. One thing regarding the implementation is what would happen if the PR is updated (e.g. retriggered run, in this scenario the PR is just updated). Should the description be updated with the new link? Or I was thinking maybe always posting a comment with link to the Packit dashboard would make sense as well. WDYT?

**Comment by lbarcziova** [comment]
During the refinement, we agreed on posting comments. (We have also discussed using commit statuses/reusing one comment)

**Comment by TomasTomecek** [comment]
> Agreed that people often do not know about the dashboard and this could help. One thing regarding the implementation is what would happen if the PR is updated (e.g. retriggered run, in this scenario the PR is just updated). Should the description be updated with the new link? Or I was thinking maybe always posting a comment with link to the Packit dashboard would make sense as well. WDYT?

Sorry for a late reply, yes the comment makes sense.
