### ISSUE TITLE
Verify `sync-release` on stage on MP+

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#2130]
After the migration to the MP+ we need to be explicit about the firewall rules. We have already hit an issue with the TF API that's been fixed already.

`sync-release` is mostly affected by this, since it allows user actions and downloads source archives from hostings, such as crates.io or PyPI

TODO:
- [x] Extend the staging allowlist with the namespaces from prod (to allow painless bootstrap)
- [x] Make a blog post and urge users to try enabling stage and enable `rawhide` or latest Fedora release to run `propose-downstream` or `pull-from-upstream` on staging too
  It's just one more PR and it should catch the firewall issues. (packit/packit.dev#724)
- [ ] (optionally) go through the recent _sync releases_ and configs to see if there are any good candidates[^1] for trying it out on stage

[^1]: ### What to consider a good candidate
      * different archive hosting
        we will definitely test the PyPI, so I'd look out for any other package managers provided by languages, e.g. Cargo (crates.io hosting) for Rust, Go, Gems for Ruby, npm for JS/TS
      * actions
        though I am definitely against allowing fetching scripts/specs/etc. from self-hosted destinations

**Comment by lbarcziova** [comment]
We have decided to create a separate card for scraping the configs and trying out the potential problematic actions, therefore closing this as done.
