### ISSUE TITLE
[RFE] Do not show queued jobs

### ISSUE THREAD

**Issue by danmyway** [packit/packit-service#2147]
### Description

Please do not show queued jobs as checks, when `manual_trigger: true` is in place.
Context:
When using the `manual_trigger:true` option in the Packit config, all jobs defined for the stage (pull_request) get triggered and show up in the checks overview.

In our scenario, we now have multiple tiers defined for the pull request stage, with just some subset of tests being recognized as essential for the PR to be merged.
We plan to introduce even more granularity to the job configuration and with that the check overview would be cluttered by the amount of jobs queued with a possibility to not ever be dispatched to the Testing Farm.

Related to #1754 

### Benefit

For more complex and multiple job definitions, the check overview might be overwhelming with many queued entries.
The pull request will get a :heavy_check_mark: when the submitted (and completed) jobs are green. :)))

### Importance

low

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by mfocko** [comment]
Could you please give a link of PR where this happened?

**Comment by danmyway** [comment]
@mfocko for example oamg/convert2rhel#845
Just to be clear, by the jobs being triggered I mean the checks are triggered, but with the `manual_trigger: true` in place, all of these stay in Queued state waiting for the comment trigger.

**Comment by lbarcziova** [comment]
@danmyway thanks for the details (I could see it e.g. in [this commit](https://github.com/oamg/convert2rhel/runs/16511578416) in the PR). If I get it correctly, this is about the situation of dependent build->test jobs where tests mirror the build statuses and once builds are finished, the test statuses are stuck as `queued` with status `RPMs were built successfully.`.

I can see 2 options of improving the UX here:
1. still mirror the statuses, but once RPMs are built, the status could be neutral (cannot be done in GitLab, successful could work but would not really be the best option since the tests were not run)
2. don't show the test statuses at all - this is what you are proposing, right?

**Comment by danmyway** [comment]
> @danmyway thanks for the details (I could see it e.g. in [this commit](https://github.com/oamg/convert2rhel/runs/16511578416) in the PR). If I get it correctly, this is about the situation of dependent build->test jobs where tests mirror the build statuses and once builds are finished, the test statuses are stuck as `queued` with status `RPMs were built successfully.`.
> 
> I can see 2 options of improving the UX here:
> 
>     1. still mirror the statuses, but once RPMs are built, the status could be neutral (cannot be done in GitLab, successful could work but would not really be the best option since the tests were not run)
> 
>     2. don't show the test statuses at all - this is what you are proposing, right?

@lbarcziova hi!
Thank you for looking into this! 
I think the second option would be much nicer if implemented.

**Comment by lachmanfrantisek** [comment]
> 2. don't show the test statuses at all - this is what you are proposing, right?

@lbarcziova @danmyway  you mean, don't show them until they are manually triggered by a comment, right?

**Comment by danmyway** [comment]
> > 2. don't show the test statuses at all - this is what you are proposing, right?
> 
> @lbarcziova @danmyway you mean, don't show them until they are manually triggered by a comment, right?

That is exactly what I mean, @lachmanfrantisek

**Comment by psss** [comment]
Agreed, hiding the manual trigger runs before they were scheduled makes sense to me as well.

**Comment by bookwar** [comment]
With this issue present, we currently have no way to differentiate between jobs which are waiting for manual trigger and jobs which were manually triggered but are just honestly queued by the testing farm. This makes it impossible to know whether PR has passed testing or still waits for it.

It is quite critical as with the current state to make a decision to merge a PR we basically have to ask one "knowledgeable person" on the team whether these test results are enough according to his knowledge. Which is a bottleneck and not very reliable.

We do not necessarily need the shiny UI for this, but we need a way to know that "all manually triggered jobs on this PR are successful".

If we can get this information from Packit dashboard, cli or API call it probably would be enough.

--

Some additional details which may or may not help:

Our workflow looks as follows:

* Someone creates a PR and ensures that unit tests are passing correctly (not via Packit)
* When we think that PR is ready for integration testing we add a label, for example `test-tier0` or `test-sanity`.
* When label is set, the bot comes and writes a comment `/packit test --labels tier0` or `/packit test --labels sanity` respectively to the PR.
* Packit reads the comment and triggers the tests according to the labels

So we have manual trigger for a specific label.

Usually there is just one label per PR (so there is no both `test-sanity` and `test-tier0` labels on one PR)

What we need is to know when the tests associated with that label have passed.

Therefore both variants will work:
1) Get test results for all jobs which were *manually triggered* in the PR
2) Get test results for all jobs *with this label* for this PR

**Comment by psss** [comment]
Perhaps a bit off-topic, just think this might possibly be useful for your use case:

> * When we think that PR is ready for integration testing we add a label, for example `test-tier0` or `test-sanity`.
> * When label is set, the bot comes and writes a comment `/packit test --labels tier0` or `/packit test --labels sanity` respectively to the PR.

Note that these two steps can now be simplified using the [require](https://packit.dev/docs/configuration#require) key. Just apply the github label and all subsequent updates of the pull request would be tested with selected additional jobs.
