### ISSUE TITLE
manual_trigger key doesn't seem to work at all for us

### ISSUE THREAD

**Issue by mulkieran** [packit/packit-service#2158]
### What happened? What is the problem?

Recently added ```manual_trigger``` to packit configuration[1]. Subsequently, assembled a PR[2] but invoking tests by comment[3] did not seem to result in the tests actually being run. I searched high and low on the Packit dashboard, but the tests did not seem to show up. I ran into a crash while looking, and filed a separate issue for that[4]. I noticed that other jobs were coming in very regularly, so outage was not the problem.

[1] https://github.com/stratis-storage/stratis-cli/pull/1011
[2] https://github.com/stratis-storage/stratis-cli/pull/1012
[3] https://github.com/stratis-storage/stratis-cli/pull/1011#issuecomment-1688583439
[4] https://github.com/packit/dashboard/issues/322

### What did you expect to happen?

I wanted to see some proof that the tests were being run after I inserted the comment in the PR.

### Example URL(s)

URLs provided above.

### Steps to reproduce

```bash
See above.
```

### What is the impacted category (job)?

Copr builds

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
hi @mulkieran ! I checked your Packit configuration and I can see you have only a `copr_build` job configured. For that one, the right comment to trigger the builds manually is `/packit build` comment command (see details in [docs](https://packit.dev/docs/guide#how-to-re-trigger-packit-actions-in-your-pull-request)). Let us know if you bump into any more troubles with the setup!

**Comment by lbarcziova** [comment]
@mulkieran please let me know whether this worked for you, in that case I would close this issue :)

**Comment by mulkieran** [comment]
> @mulkieran please let me know whether this worked for you, in that case I would close this issue :)

Plz close. It works: https://github.com/stratis-storage/stratis-cli/pull/948 .
