### ISSUE TITLE
Simple way to constraint the order of Copr builds

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#2169]
### Description

Before we have [something more fancy and generic](https://github.com/packit/packit-service/issues/2105), it would be nice to have a way to constraint the order in which the packages are built just in Copr.

Copr builds have the ["batching" feature](https://pavel.raiskup.cz/blog/build-ordering-by-batches-in-copr.html).  For us it would be as simple as specifying that `copr-backend` is built after `python-copr-common`, and alike.

Proposed configuration format:

```
copr_build_order_simple:
    copr-backend: python-copr-common
    copr-frontend: python-copr-common
    copr-frontend: python-copr-common
    ....
```

The monorepo configuration gives us idea what packages were fixed.  So we could simply:

```python

modified_packages = packit_knows_this()
submitted = {}
has_dep = config["copr_build_order_simple"]

todo = set(modified_packages.keys())

something_submitted = True

def submit_package(pkg_name, after=None):
    global  something_submitted
    something_submitted = True
    todo.remove(pkg_name)
    modified_packages[pkg_name].build_id = copr.build(pkg_name, build_after=after)


while todo and something_submitted:
    something_submitted = False
    try_submit = copy(todo)
    for package_name in try_submit:
        if package_name not in has_dep:
            submit_package(pkg_name)
            continue

        dep = has_dep[package_name]
        if dep not in modified_packages:
            # no need to wait for the dep
            submit_package(package_name)
            continue

        if modified_packages[dep].build_id:
            submit_package(pkg_name, after=modified_packages[dep].build_id)
            continue
```

### Benefit

We can easily fix CI Copr build issues for monorepos with intradependencies.

### Importance

Medium to High.  Waiting for something much better is tiring and inconvenient.

### What is the impacted category (job)?

Copr builds

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by praiskup** [comment]
Would it help if Copr provided `build.comment` text metadata which would be set e.g. by `copr build --build-comment COMMENT`?

This would allow the Packit Service to set there anything, even "YAML" data like:

```yaml
packit:
    job_id: ...
```

Then `wait-for-copr` could (a) list all the builds in the project, (b) filter builds related only to the same GitHub event/job_id (c) and from that identify the build_id the particular worker needs to `--build-after-id` (if at all)?

At least assuming that each particular per-package worker **knows how the list of modified packages looks**, this should be pretty easy?

**Comment by lachmanfrantisek** [comment]
@praiskup That's an interesting idea. Being able to set some metadata to the build itself might be handy and could allow us to implement something more quickly.

But I am not sure if this is worth your time and we shouldn't spend our time on the #2105 right away.

**Comment by lachmanfrantisek** [comment]
Closing this one since we have a short-term workaround (https://github.com/packit/wait-for-copr) before we finish the #2105
