### ISSUE TITLE
Build Logs URL not clickable for srpm builds

### ISSUE THREAD

**Issue by psss** [packit/packit-service#2192]
### What happened? What is the problem?

Clicking on the `Build Logs URL` link has no effect.

### What did you expect to happen?

Get to the build log.

### Example URL(s)

https://dashboard.packit.dev/results/copr-builds/1021135

### Steps to reproduce

```bash
1. Visit: https://dashboard.packit.dev/results/copr-builds/1021135 
2. Click on the `Build Logs URL` link
3. Nothing happens
```

### What is the impacted category (job)?

Copr builds

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
@psss hi, thanks for the issue! Yes, we have noticed this and described the problem in #2195, it happens when the SRPM itself fails and ideally we should not show the Copr builds at all. If you are not against, I would therefore close this as a duplicate of #2195.

**Comment by psss** [comment]
Yeap, sure, thanks for the pointer.
