### ISSUE TITLE
Support for linking copr builds in github comment notifications

### ISSUE THREAD

**Issue by lsm5** [packit/packit-service#2196]
### Description

Following up on https://github.com/packit/packit-service/pull/2182 . This is especially for the `trigger: commit` case.

Using https://github.com/containers/aardvark-dns/commit/fed1474f4d6458be675c106cda30e4165fa3e6d6#commitcomment-128070716 as an example, allow a URL variable pointing to the failed build task. 

### Benefit

When a copr build fails, it would be ideal to get a clickable link to the failed copr build in the failure notification comment. 

This would also be useful to other maintainers who usually don't deal with copr and may not be familiar with how to navigate to the failed copr tasks.

### Importance

Not blocking. Just nice to have.

### What is the impacted category (job)?

Copr builds

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

Workaround is to just manually navigate to the copr task.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
HI @lsm5 !

Definitely a good suggestion. Would you be interested in the link to the GitHub status, Packit's page with all the links, Copr URL, or Copr logs?

Maybe, we can provide all we know (=the Packit's page, Copr web/logs or TMT URL). The GitHub status might be harder to get.

**Comment by lsm5** [comment]
> HI @lsm5 !
> 
> Definitely a good suggestion. Would you be interested in the link to the GitHub status, Packit's page with all the links, Copr URL, or Copr logs?
> 
> Maybe, we can provide all we know (=the Packit's page, Copr web/logs or TMT URL). The GitHub status might be harder to get.

`All we know` is certainly fine by me. At a minimum, specifically for the `job: copr_build + trigger: commit` case, a link to the failed copr main task for example: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6493345/ would suffice.

**Comment by lachmanfrantisek** [comment]
@lsm5 OK, thanks for your response, we'll try to take a look at that.
