### ISSUE TITLE
"manual_trigger: true" is not working for us quite as expected

### ISSUE THREAD

**Issue by mulkieran** [packit/packit-service#2197]
### What happened? What is the problem?

We recently discovered the ```manual_trigger``` key and started using it in our ```copr_build``` job so that we did not build a package with every push to a PR. We were pleased w/ that.

But now, for stratisd, we are running some TMT tests via Packit. This is working well for us except that it looks like there is no way to get them to run unless we remove ```manual_trigger``` attribute from both the ```copr_build``` job configuration and the ```tests``` job configuration.

If we have ```manual_build: true``` in both, then the COPR build gets kicked off fine when I put "\packit build" in a comment, but the tests don't run. If I remove ```manual_build: true``` just from the tests job configuration, then it looks like the tests do start, but can not get a build to run from so they wait forever (I think). If I remove "manual_build: true" from both job configurations then the tests run fine from the build, but we're back to where we were before, which is running the build and tests every time we push, which is excessive.

We would like the "manual_build: true" flag to be respected in both the "tests" job and the "copr_build" job so that we could run tests and builds on demand.

Here is a post[1] about the introduction of the ```manual_trigger```  key. The reason this works so nicely for these users is that their use case does not require the package to be built, and so they are able to set the ```skip_build``` attribute to ```true```. That won't work for us.

[1] https://packit.dev/posts/manual-triggering

### What did you expect to happen?

I expected to be able to run the tests on demand and to have the copr build made on demand to support the tests.

### Example URL(s)

https://github.com/stratis-storage/stratisd/pull/3447 shows me removing ```manual_trigger: true``` in order to get tests to build.

### Steps to reproduce

```bash
1. Set ```manual_trigger: true``` for your tests job.
2. Watch copr build, which is also ```manual_trigger: true``` kick off fine.
3. Wait forever for tests to kick off.

There is no actual workaround for this problem at this time that I'm aware of. But we are willing to accept the tradeoff and proceed with running the tests on every pull for a while if not longer.
```

### What is the impacted category (job)?

General

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
hi! Thanks for the report. I will have a closer look into this.

But as for having `manual_trigger` True for both jobs, this is a "known" inconvenience/UX issue, if you have this setup, you need to put both `/packit build` and after builds are successful `/packit test` comment in order for the tests to be executed. Let me know if it worked for you!

**Comment by mulkieran** [comment]
We will try that, and I think it will be the best way for us.

**Comment by lbarcziova** [comment]
@mulkieran I can see it worked for you! Can we close this or do you propose some improvements here?

**Comment by mulkieran** [comment]
@lbarcziova I think you could close it, yes. I think the problem was not knowing how the copr build configuration and the test configuration interact implicitly, and thus not understanding how the ```manual_trigger``` flag affects their interaction. So, not an obvious code solution.

**Comment by lbarcziova** [comment]
thanks @mulkieran. I also adjusted the docs to mention this scenario, see packit/packit.dev#753.
