### ISSUE TITLE
Find easy way to record location of TMT results and COPR builds

### ISSUE THREAD

**Issue by mulkieran** [packit/packit-service#2205]
### Description

Sometimes I want to refer to the results of a TMT job that ran a while ago, for example, if it has a distinctive error behavior.  I can go to my project website[1] and look at Packit actions taken. But there's no way that I can find to click on anything that will take me to the records of the testing.

I can go to the jobs listing[2] and things are definitely better. If my job has been run recently, I can spot it, and follow the links to the test or the COPR build as I require. But if my job was run, e.g., just a day ago, there is no search facility that I can use that will allow me to go to the entry for that job. I can try paging down, using the button on the bottom of the screen and my browser's Find faciity, but that is slow and tedious, because the jobs page lists many jobs, chronologically. Just recently, I wanted to go back a whole day, and that was too many screens.

The best thing I can think of to do right now is that every time I actually run a test, I should copy and paste the resulting TMT link into a GitHub comment, to keep the record. Assuming this is the best thing available, I can start doing it immediately.

But I would like some automatic way to have access to this record instead. One way would be for Packit to add some sort of notes in the GitHub PR, with a link to the test. Another way would be to make there be an easy way to find the previously run test via Packit dashboard. Another way would be to include it in the GitHub results under something similar to the Actions tab, so that the historical links were actually available from the GitHub project page.

The very same holds true of COPR builds, for much the same reasons. They are owned by the Packit project, not by me. If they were owned by me, they would be easier to find.

[1] https://dashboard.packit.dev/projects/github.com/stratis-storage/stratisd
[2] https://dashboard.packit.dev/jobs/testing-farm-runs

### Benefit

Historical understanding of failures. This is similar to what the Actions tab on GitHub provides already.

### Importance

This is a pretty big deal, we intend to work around it by saving links for now.

### Workaround

- [X] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by danmyway** [comment]
Hello, to be completely honest, I have tried to pave my own way.
I have found, that querying [Packit's API](https://prod.packit.dev/api/) (if consistently working), would suffice.
Getting the pipeline_id and/or web_url for the latest run is fairly easy.
You can even query for previous runs, if you can get your hands on the commit SHA of which the desired test run is based.

**Comment by mulkieran** [comment]
> hi! This sounds very similar as #2139. Would that proposal by @danmyway in there work for you as well?
> 
Definitely, yes, that would help.

**Comment by lbarcziova** [comment]
@mulkieran sorry for a late reply...so in that case I would close this in favour of #2139 if you are not against.

**Comment by mulkieran** [comment]
> @mulkieran sorry for a late reply...so in that case I would close this in favour of #2139 if you are not against.

Please do.
