### ISSUE TITLE
pull-from-upstream cannot fetch tar file from PyPI

### ISSUE THREAD

**Issue by xsuchy** [packit/packit-service#2210]
### What happened? What is the problem?

In this pull-from-upstream
  https://dashboard.packit.dev/results/pull-from-upstream/4106

packit tries to fetch tar file from
https://files.pythonhosted.org/packages/source/i/ibm-cloud-sdk-core/ibm-cloud-sdk-core-v3.17.0.tar.gz
but that does not exists. Correct link seems to be:
https://files.pythonhosted.org/packages/c1/00/e674372280b8759d682ed2522014b3914811c5cb7b5c5e236ac334160e0e/ibm-cloud-sdk-core-3.17.0.tar.gz

### What did you expect to happen?

Download the correct tar ball.

### Example URL(s)

https://dashboard.packit.dev/results/pull-from-upstream/4106

### Steps to reproduce

```bash
1. trigger job in https://src.fedoraproject.org/rpms/python-ibm-cloud-sdk-core/pull-request/1
```

### What is the impacted category (job)?

Fedora release automation

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
We have discussed this over chat, the problem was missing `upstream_tag_template` in the configuration (upstream Git repo uses different versioning schema).

**Comment by xsuchy** [comment]
Yes. Thanks for the help. Closing.
