### ISSUE TITLE
React with a comment when rerunning releases from dist-git PR

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2214]
When people rerun release syncing from a dist-git PR, we don't provide feedback that Packit is doing something and also where to check the progress.

So:
* [ ] When reacting to a dist-git PR comment and we know sync-release will run,  add a new comment to the PR (current implementation can be used to avoid duplicates).
* [ ] In the comment, link the dashboard (can be also https://dashboard.packit.dev/jobs/pull-from-upstreams / https://dashboard.packit.dev/jobs/propose-downstreams )
* [ ] (optionally) link the specific dashboard result page(s)

**Comment by lbarcziova** [comment]
Related: #1989
