### ISSUE TITLE
/packit test to trigger build when the last build is unsuccessful

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2219]
@psss brought this up on Slack: the builds are currently triggered only if there were no previous attempts to create builds. If the build failed, nothing happens. Better UX would be that the builds would be triggered in that case as well.

[Here](https://github.com/packit/packit-service/blob/2010a5c3cf4e99ac4b81aecf0afed85d241a6165/packit_service/worker/handlers/testing_farm.py#L255) is the related code.

**Comment by psss** [comment]
Thanks for the quick fix!
