### ISSUE TITLE
Get a list of maintainers to suggest onboarding 

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2227]
Let's gather some data to provide a list of good candidates to contact directly with the onboarding.

Suggestions of the characteristics of such a candidate:
* A lot of packages.
* Packages are simple
  * no patching or just a few long-term ones
  * specfile is not complicates
  * ...
* Frequent releases.

TODO:
* [ ] Prepare a script that outputs a list of maintainers to contact (ideally, with additional info so we understand the packages when contacting the person).
* [ ] Share the list within a team.
* [ ] Prepare the follow-up cards for the first N (let's say 5) maintainers to contact and add the card to the #2204 epic.

ping @xsuchy

**Comment by nforro** [comment]
I would suggest to also try to do a sync_release run on those packages to identify any potential issues in advance.

**Comment by nforro** [comment]
To be honest I meant trying it only locally and without a PR, I do that myself sometimes, of course it requires one to stop the execution before push.

**Comment by lachmanfrantisek** [comment]
> To be honest I meant trying it only locally and without a PR, I do that myself sometimes, of course it requires one to stop the execution before push.

We should make a CLI option for that..;)

**Comment by xsuchy** [comment]
Quick'n'dirty script to check if a user uses Packit:

First save list of his packages to file `/tmp/r` and then:

```
for i in $(cat /tmp/r); do
  fedpkg clone --depth 1 $i 
  ls $i/packit || echo "User use packit"; 
done
```
