### ISSUE TITLE
When releasing, check that spec file is up to date

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#223]
I just did a new ogr upstream release and forgot to bump the spec file -_-

Luckily Franta introduced the `--local-content` option which makes it easy to resolve, but still, we should have something, ideally in packit, which would fail the PR with a new upstream release if the spec is not up to date.

No idea how to do this or what would the best workflow be. Or maybe have this in release-bot. But since packit has the req on spec in upstream, I feel like this check should live in packit.

**Comment by jpopelka** [comment]
Sad to see this go since I can confirm it's still a problem for some (especially those hasty ones who merge their PR's without waiting for review) - https://github.com/packit-service/packit/pull/674

On the other hand, we haven't figured out how/where to solve it.

**Comment by lachmanfrantisek** [comment]
During the propose-downstream, check the correctness of the spec-file version and stop the process in case of any error and ask user to perform update manually with `--local-content`.
