### ISSUE TITLE
Try to onboard package(s) of FAS user music for Fedora downstream automation

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2237]
Followup of #2227 
- [ ] check whether the maintainer already uses Packit, if yes, contact them and ask about the feedback, offer help with setting up Packit for their other packages

If no:
- [x] contact the maintainer, introduce Packit downstream automation and ask if you could create a PR with Packit config for one of their packages (you can ask whether they have access to the upstream repos or would be interested in having the config only in dist-git)
  - use the [mail template](https://docs.google.com/document/d/1a8kRBhj-xATc65qUGrMsRpzyLLNvqbbJkdL-sgQPUdE/edit?usp=sharing) (adjust it if needed)
  
After an agreement:
- [ ] check [this spreadsheet](https://docs.google.com/spreadsheets/d/1MVHZ869S2z0rGDIcM7zkv5HAlgZqihcUN3VgCFhDuF4/edit?usp=sharing) for the list of packages and choose one (ideally with pending release to rebase, having Git upstream, easy to configure), 
   -  the spreadsheet should be updated accordingly, make sure that the package was not onboarded already (there is overlap of the packages since they can have multiple maintainers)
- [ ] create a Packit configuration setting up the Fedora downstream automation (for syncing start with one branch to not spam)
- [ ] optionally test the syncing locally (see [comment](https://github.com/packit/packit-service/issues/2227#issuecomment-1759635608))
- [ ] create a PR, try to do a test run (`/packit pull-from-upstream --with-pr-config`) and communicate further with the maintainer the follow-up steps (e.g. create issues if some functionality is missing, setup on more of their packages) 
---
_Part of #2204 epic_

**Comment by lachmanfrantisek** [comment]
I've created a user card to track blockers: https://github.com/packit/user/issues/17

@majamassarini , can you please send the user response with the state of their issues:

* https://github.com/packit/packit-service/issues/2343
* Linking of the upstream release from dist-git PR is done.
* Link source diff (e.g. https://github.com/mozman/ezdxf/compare/v1.1.2...v1.1.3). -> Ask for creating a new issue (and link it to https://github.com/packit/user/issues/17)
