### ISSUE TITLE
Try to onboard package(s) of FAS user rdieter for Fedora downstream automation

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2238]
Followup of #2227 
- [x] check whether the maintainer already uses Packit, if yes, contact them and ask about the feedback, offer help with setting up Packit for their other packages

If no:
- [x] contact the maintainer (Matrix/Slack/email), introduce Packit downstream automation and ask if you could create a PR with Packit config for one of their packages (you can ask whether they have access to the upstream repos or would be interested in having the config only in dist-git)
  - use the [mail template](https://docs.google.com/document/d/1a8kRBhj-xATc65qUGrMsRpzyLLNvqbbJkdL-sgQPUdE/edit?usp=sharing) (adjust it if needed)
  
After an agreement:
- [ ] check [this spreadsheet](https://docs.google.com/spreadsheets/d/1MVHZ869S2z0rGDIcM7zkv5HAlgZqihcUN3VgCFhDuF4/edit?usp=sharing) for the list of packages and choose one (ideally with pending release to rebase, having Git upstream, easy to configure), 
   -  the spreadsheet should be updated accordingly, make sure that the package was not onboarded already (there is overlap of the packages since they can have multiple maintainers)
- [ ] create a Packit configuration setting up the Fedora downstream automation (for syncing start with one branch to not spam)
- [ ] optionally test the syncing locally (see [comment](https://github.com/packit/packit-service/issues/2227#issuecomment-1759635608))
- [ ] create a PR, try to do a test run (`/packit pull-from-upstream --with-pr-config`) and communicate further with the maintainer the follow-up steps (e.g. create issues if some functionality is missing, setup on more of their packages) 
---
_Part of #2204 epic_

**Comment by xsuchy** [comment]
Email sent.

**Comment by xsuchy** [comment]
I wrote Rex several times. No response. Closing as he is likely not interested in.
