### ISSUE TITLE
Please build `wait-for-copr` in the `packit-stable` F39 chroot

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#2251]
### What happened? What is the problem?

The custom method used by Packit SRPM task is now done in Fedora 39, and while trying to install build dependencies, it fails:

```
...
 'repos': [{'baseurl': 'https://download.copr.fedorainfracloud.org/results/packit/packit-stable/fedora-39-x86_64/',
...
 'source_json': {'builddeps': 'packit wait-for-copr tito git',
                 'chroot': 'fedora-39-x86_64',
...
No match for argument: wait-for-copr
Error: Unable to find a match: wait-for-copr
```

https://download.copr.fedorainfracloud.org/results/packit/copr/srpm-builds/06615963/builder-live.log.gz

### What did you expect to happen?

Build success.

### Steps to reproduce

```bash
Build anything which depends on `wait-for-copr`.
```

### What is the impacted category (job)?

Copr builds

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by mfocko** [comment]
Should be done with this build: https://copr.fedorainfracloud.org/coprs/packit/packit-stable/build/6628508/
