### ISSUE TITLE
Merge conflict on fedora downstream version update for `qm` rpm

### ISSUE THREAD

**Issue by lsm5** [packit/packit-service#2257]
### What happened? What is the problem?

 i see a strange issue with packit updates on the [qm](https://src.fedoraproject.org/rpms/qm/pull-requests) package . The PRs in there are having a merge conflict with trying to bump versions from `0.5.7 to 0.6.0` when packit had already done a prior PR bump from [0.5.7 to 0.5.8](https://src.fedoraproject.org/rpms/qm/c/79cafca2841d23d235014d8dc69d224618629b41?branch=rawhide)

### What did you expect to happen?

should not have had merge conflicts and should have correctly bumped from `0.5.8` to `0.6.0`.

### What is the impacted category (job)?

Fedora release automation

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lsm5** [comment]
cc @dougsland

**Comment by lbarcziova** [comment]
hi @lsm5 ! Thanks for reporting, from the first look this really doesn't look right. We need to investigate this more, I will have a look into our logs.

**Comment by lbarcziova** [comment]
We will try to prioritise this issue since this should definitely not happen. From looking into the logs and the code, this is really strange as we always fetch the latest changes from the dist-git repo.

**Comment by majamassarini** [comment]
I have analyzed the open/merge branch history and found out that the 0.5.8 related branch was merged after the creation of the 0.6.0 related branch.
After we create a branch we do not automatically update/rebase it and for this reason it went out of sync
I think this [work](https://github.com/packit/packit/issues/2182) already scheduled could probably prevent this to happen again, what do you think @lbarcziova and @lachmanfrantisek?

| branch | for release | action | time |
| - | - | - | - |
|f38 | 0.5.8 | opened | 2023-11-01 13:40:52 |
|       |           | merged | **2023-11-05 13:06:35** |
|       | 0.5.9 | opened | 2023-11-03 20:01:47 |    
|       | 0.6.0 | opened | **2023-11-05 13:02:08** |
|f39 |0.5.8 | opened | 2023-11-01 13:40:27 |
|       |          |merged | **2023-11-05 13:06:11** |
|       |0.5.9 | opened | 2023-11-03 20:00:40 |
|       | 0.6.0 | opened | **2023-11-05 13:01:47** |
|rawhide  |0.5.8 | opened | 2023-11-01 13:40:04 |
|       |          | merged | **2023-11-05 13:04:01** |
|       |0.5.9 | opened | 2023-11-03 20:00:01 |
|       | 0.6.0 | opened | **2023-11-05 13:01:28** |

**Comment by lbarcziova** [comment]
@majamassarini good catch! Yes, I think packit/packit#2182 should prevent this from happening.

**Comment by majamassarini** [comment]
I close this one and start to work on https://github.com/packit/packit/issues/2182
