### ISSUE TITLE
Support a shorter version of the `--identifier` option

### ISSUE THREAD

**Issue by psss** [packit/packit-service#2259]
### Description

Scheduling a `manual_trigger` job is quite frequent action. Would you be willing to provide a shorter version of the identifier option to save a bunch of keystrokes?

Instead of:

    /packit test --identifier full

It could look like this:

    /packit test --id full

Or even this?

    /packit test -i full

What do you say?

### Benefit

Hundreds of keystrokes saved...
More pull requests merged...
Lower energy consumption...
Higher productivity... ;-)

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [X] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by kkaarreell** [comment]
or `/packit test full` or `/packit test/full`. IMHO `id` seems to be so important attribute, that we could accept extra approach of specifying it.

**Comment by psss** [comment]
> or `/packit test full`

That would be even better!

> IMHO `id` seems to be so important attribute, that we could accept extra approach of specifying it.

Agreed.

**Comment by lbarcziova** [comment]
hi @psss @kkaarreell ! I understand, implementing the  `-i` or `--id` aliases would be probably really easy and makes sense. I am afraid that accepting it as a standalone argument would collide with the current argument for build from another PR, see [the docs](https://packit.dev/docs/configuration/upstream/tests#running-tests-with-builds-from-another-pull-request). On the other hand, in #2200 we discussed the parsing of arguments and additionally starting utilising `argparse`, which would probably make this easier to happen.

**Comment by psss** [comment]
> I am afraid that accepting it as a standalone argument would collide with the current argument for build from another PR, see [the docs](https://packit.dev/docs/configuration/upstream/tests#running-tests-with-builds-from-another-pull-request).

I see, understood. On the other hand, in the documentation I see:

> This is a new feature, so the behaviour may be adjusted in the future.

So... perhaps, we could give precedence to the `identifier` use case as that will probably be much more frequent use case? At least that's what I expect from my point of view, but yeah, others might feel it differently...

**Comment by lbarcziova** [comment]
>  will probably be much more frequent use case

yes, I agree with that! Putting here `discuss` label to discuss with the team.
