### ISSUE TITLE
does not create new chroots when packit config changes after a PR rebase

### ISSUE THREAD

**Issue by evgeni** [packit/packit-service#2262]
### What happened? What is the problem?

In Foreman, we recently [switched from building against `centos-stream-8` to `rhel-8`](https://github.com/theforeman/foreman/commit/69ae05cff0667948e9720199969c43fdad5061d3), however, it seems that PRs that have been opened *before* this change do not get their respective copr projects updated and thus fail to build with "Chroot name rhel-8-x86_64 does not exist in Copr packit/theforeman-foreman-9837."

Example: https://github.com/theforeman/foreman/pull/9837/checks?check_run_id=19147230758

### What did you expect to happen?

The copr project is updated to reflect the changes in `packit.yml` and thus succeeds to build

### Example URL(s)

https://github.com/theforeman/foreman/pull/9837/checks?check_run_id=19147230758

### Steps to reproduce

```bash
1. open a PR
2. change packit config in base branch
3. rebase PR
```

### What is the impacted category (job)?

Copr builds

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
Closing in favour of https://github.com/packit/packit-service/issues/1854 which should fix it.

**Comment by lbarcziova** [comment]
I am not sure #1854 is the same :thinking:  

This one should be about wrong handling of chroot-specific configuration when the chroots are updated and #1854 is about multiple copr_build jobs building in the same Copr project where each job has different targets.

**Comment by nforro** [comment]
I agree with @lbarcziova, this is a different issue.
