### ISSUE TITLE
The manual triggered jobs should show up as `not started` not queued

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#2268]
### Description

Currently, the manually trigger-able tests show up as queued. That is confusing, as they are not really queued, more like not started. Would be nice to mark it that way (maybe with a message they are expecting a manual trigger).

![packit-queued-manual](https://github.com/packit/packit-service/assets/633969/9f53b986-004e-491f-b617-cadc7ce96fad)

### Benefit

Less confusion to the users.

### Importance

For now nice to have, not sure how hard is to change it

### What is the impacted category (job)?

Testing Farm tests

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [X] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
hi @thrix ! We have a similar issue #2147 in which we concluded the test jobs should be not shown until they are triggered via comment (and [here](https://github.com/packit/packit-service/issues/2147#issuecomment-1746253715) the first point is something similar to what you are proposing). What do you think about that?

**Comment by psss** [comment]
Yeah, I think not showing the queued jobs at all could work as well. On the other hand, we have the `full` jobs included in the required GitHub checks, so I guess that would still appear in the list but, I guess, the wording would not be confusing as those empty check would not show `queued`, right? @thrix?

**Comment by lbarcziova** [comment]
#2147 is now resolved, so I will close this one as well.
