### ISSUE TITLE
 Try to onboard package(s) of FAS user jplesnik for Fedora downstream automation

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2280]
Followup of #2227 
- [x] check whether the maintainer already uses Packit, if yes, contact them and ask about the feedback, offer help with setting up Packit for their other packages

If no:
- [x] contact the maintainer (Matrix/Slack/email), introduce Packit downstream automation and ask if you could create a PR with Packit config for one of their packages (you can ask whether they have access to the upstream repos or would be interested in having the config only in dist-git)
  - use the [mail template](https://docs.google.com/document/d/1a8kRBhj-xATc65qUGrMsRpzyLLNvqbbJkdL-sgQPUdE/edit?usp=sharing) (adjust it if needed)
  
After an agreement:
- [ ] check [this spreadsheet](https://docs.google.com/spreadsheets/d/1MVHZ869S2z0rGDIcM7zkv5HAlgZqihcUN3VgCFhDuF4/edit?usp=sharing) for the list of packages and choose one (ideally with pending release to rebase, having Git upstream, easy to configure), 
   -  the spreadsheet should be updated accordingly, make sure that the package was not onboarded already (there is overlap of the packages since they can have multiple maintainers)
- [x] create a Packit configuration setting up the Fedora downstream automation (for syncing start with one branch to not spam)
- [ ] optionally test the syncing locally (see [comment](https://github.com/packit/packit-service/issues/2227#issuecomment-1759635608))
- [ ] create a PR, try to do a test run (`/packit pull-from-upstream --with-pr-config`) and communicate further with the maintainer the follow-up steps (e.g. create issues if some functionality is missing, setup on more of their packages) 
---
_Part of #2204 epic_

**Comment by xsuchy** [comment]
Jitka is using a packit for a package she inherited https://src.fedoraproject.org/rpms/perl-Date-Manip and claims that it likely did not get filed PR despite recent release. Going to check.
I explained packit configs and pull-from upstream, provided two templates. And after a discussion opened two RFEs:
 https://github.com/packit/packit/issues/2196
 https://github.com/packit/packit/issues/2195

**Comment by xsuchy** [comment]
Hmm seems Anitya config is correct https://release-monitoring.org/project/2785/ 
New upstream release happened a week ago https://github.com/SBECK-github/Date-Manip/tags
But no PR in https://src.fedoraproject.org/rpms/perl-Date-Manip

**Comment by xsuchy** [comment]
Ouch it failed to download tarball from https://cpan.metacpan.org/authors/id/S/SB/SBECK/Date-Manip-6.94.tar.gz
It exists now. I guess the timeflow was:
1. create a release on GitHub
2. Anitya noticed that, Packit was triggered, download failed
3. upstream uploaded tarball to cpan

this whole may happened in 5 minutes :(

**Comment by xsuchy** [comment]
I opened https://github.com/packit/packit/issues/2197

**Comment by xsuchy** [comment]
I am moving this to backlog. Until the https://github.com/packit/packit/issues/1954 is resolved I really cannot continue with onboarding of Jitka as all her packages are perl-* and will likely hit the same bug again and again.

**Comment by lbarcziova** [comment]
The blocking issue is resolved now, we retry the downloading up to 1 hour.

**Comment by lbarcziova** [comment]
This should be done.
