### ISSUE TITLE
copr-build/commit trigger builds wrong version numbers with non-main branch releases

### ISSUE THREAD

**Issue by martinpitt** [packit/packit-service#2294]
### What happened? What is the problem?

On Dec 17 2023 we created a [cockpit 300.4](https://github.com/cockpit-project/cockpit/releases/tag/300.4) point release on our [rhel-9.3](https://github.com/cockpit-project/cockpit/tree/rhel-9.3) branch. Chronologically this was more recent than the latest [release 307](https://github.com/cockpit-project/cockpit/releases/tag/307) from our main branch, but both conceptually and also formally in GitHub, 307 was still the "latest" release (I was very careful to *not* move the "latest" pointer to 300.4!). At that time, https://github.com/cockpit-project/cockpit/releases looked like this:

![cockpit-releases-branch](https://github.com/packit/packit-service/assets/200109/d3798cb0-ec32-462f-a2f2-659775291283)

We have a [cockpit main-builds COPR](https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds) which gets fed by [packit.yaml](https://github.com/cockpit-project/cockpit/blob/main/packit.yaml#L62) by this rule:

```yaml
  # for cross-project testing
  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@cockpit"
    project: "main-builds"
    preserve_project: True
```

Since the 300.4 release, the [builds](https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/builds/) in this COPR got wrong version numbers:

![cockpit-copr-builds](https://github.com/packit/packit-service/assets/200109/0ec0a2c1-7aef-4acc-99da-60474a22339e)

E.g. the topmost one: 300.4-1.20240103081125350442.main.33.gea9a84d8a  . The date and the git SHA are correct for main, but "300.4" is wrong -- it's the chronologically latest tag/release, but it doesn't belong to the "main" branch at all, and isn't even marked as "latest" in github.

The effect of this was that the latest "visible" release for dnf from the COPR is stuck at 307-1.20231215095548475620.main.1.gd577313ea.fc40, i.e. that's the version that `dnf` installs. This led to test failures like [this run](https://artifacts.dev.testing-farm.io/5b409635-7181-4794-b2e3-961af8dd9ac7/) where it tries to run current main tests against a totally outdated COPR build from > 2 weeks ago.

Today we released 308, so the releases page looks different again. This also fixes/papers over the imminent problem, but it will come back as soon as we'll do another point release from some stable rhel branch.

### What did you expect to happen?

It *seems* packit determines the latest version number by looking at https://github.com/cockpit-project/cockpit/releases and taking the most recent one, which is wrong. This contains releases from all branches.

packit should compute the version based on `git describe` on the checked out branch, which has always been correct. E.g.
```
❱❱❱ git describe
307-33-gea9a84d8a
```
If that's not possible for some reason, and you have to use the GitHub API, then please at least query the release with the "latest" flag.

### What is the impacted category (job)?

Copr builds

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
hi @martinpitt ! I think this is mostly the same as packit/packit#2184, mainly the first point and we will prioritise fixing that. 

We get the `300.4` as it is the latest tag in the repository (from logs `Command: git tag --list --sort=-creatordate`)  but you are right in this case Packit should only consider tags in the "working" branch.  In the meantime, while we fix the linked issue, you could as a workaround use the [`get-current-version` action](https://packit.dev/docs/configuration/actions#creating-srpm).

**Comment by martinpitt** [comment]
Thanks @lbarcziova ! So I suppose packit could default to `git describe --abbrev=0` if it wants to build the other parts of the version number by itself? (although it looks fairly close to normal `git describe` already).

Nice idea with the `get-current-version` action workaround, thanks!

**Comment by lbarcziova** [comment]
Yes, for SRPMs that should probably be the case, the problem is we use this code for multiple use cases and it used to be like that (we used `git describe --abbrev=0 --tags`) but that caused problems e.g. for syncing the release downstream and that's why it was changed. So we need to revisit it and differentiate these use cases properly.

**Comment by lbarcziova** [comment]
H @martinpitt i! Since packit/packit#2184 is now fixed, could we close this as well?

**Comment by martinpitt** [comment]
Thanks @lbarcziova ! https://github.com/packit/packit-service/commit/5257ccd706ee88e4d46b30ae1f9f73ee236ca148 indeed looks plausible. We'll see it the next time we do a point release. :grin:
