### ISSUE TITLE
Onboard 1/3 of the number of packages “suitable for onboarding” for Fedora and collect the feedback

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#2298]
This is an epic to cover the work to get a significant part of onboardable packages for Fedora automation to Packit.

GOAL of the epic:
The number of "onboarded" (= at least one sync release merged or one Koji build created by Packit or one Bodhi update created)  packages is at least 415 (=number of packages "suitable for onboarding"[1]).

[1] : So, far, covered by [this check](https://github.com/packit/research/commit/832038c3c56a2cdab1d88e07e3b853c53de6d1d4#diff-df9bcdcf95f29741c2508e82329621b32103786c9f23ae1fb51f67677cba5cf5R78).

- [x] #2304
- [x] #2301

**Comment by lbarcziova** [comment]
@lachmanfrantisek I would say this is done and we can close this now?
