### ISSUE TITLE
Packit 2024 downstream automation workshop

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#2327]
Let's do the first online workshop about downstream automation using Packit in 2024.

* [ ] Pick the date at least a month ahead. **We agreed upon 2024/03/06**, **time?**
* [ ] Create a calendar invite and book the resources (e.g. a room) if needed.
* [ ] ~~Prepare a sign-up sheet.~~ Create a google sign-up form (for non red hatters) and do not require a google account for signing up (people already complained about that). Potentially ask if they can write down both the email address and the nickname they will use when joining the workshop  (limit the number of people to something manageable like 20, promise repetition if full).
* [ ] Send the essential information to the relevant channels. (Try both global and local.)
* [ ] Clone and update the workspace from the previous run.
* [ ] Prepare the environment. Create a *welcoming and effective workflow for people that will join later the workshop* and pay attention that splitting people in groups does not work well when they arrive scattered.
* [ ] Send a calendar invite to the attendees (ideally, once they sign up).
* [ ] Send reminder a week ago
    * [ ] To the attendees with the instructions on how to prepare.
    * [ ] To the channels with the announcement if we have a free capacity.
* [ ] Agree about the responsibilities within a team. Not all the team should be present if not necessary, part of the team can just be called if needed.
* [ ] Run the workshop:
    * [ ] Provide a welcoming space for people to ask for help.
* [ ] Try to collect feedback during the meeting.

**Comment by lbarcziova** [comment]
Is this still relevant? We did the workshop in June around DevConf, so I guess we could close this.
