### ISSUE TITLE
obsolete propose_downstream volunteer call?

### ISSUE THREAD

**Issue by martinpitt** [packit/packit-service#2337]
### What happened? What is the problem?

On some [random packit TF run](https://github.com/cockpit-project/cockpit-machines/pull/1416/checks?check_run_id=21371277406) I spotted this:

![image](https://github.com/packit/packit-service/assets/200109/c5da8c2d-a0b2-4c06-873b-0e0fcee0b4c4)

It leads to https://packit.dev/posts/verify-sync-release-volunteers which was done half a year ago (Sep 2023).

Is it still actually up to date? I thought these changes landed long ago.

### Example URL(s)

https://github.com/cockpit-project/cockpit-machines/pull/1416/checks?check_run_id=21371277406

### What is the impacted category (job)?

General

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
thanks @martinpitt for pointing this out! Yes you are completely right, we are on the new cluster already.
