### ISSUE TITLE
Scrape all the specfiles from Fedora for source URLs

### ISSUE THREAD

**Issue by mfocko** [packit/packit-service#2390]
To be able to adjust the firewall rules »beforehand« on the MP+, we need to know the domains/forges from which users are using sources for the `sync-release` actions.

Scraping the specfiles and configs of current users didn't provide enough benefit, since it can be still a pain point during an onboarding of new users

- [x] scrape all the specfiles
- [x] pinpoint forges/URLs that we do not support as of now
  - [ ] (optionally) ask the packagers if they'd be interested in onboarding
  - [ ] also check for activity within the packages
- [x] edit comment with the “waiting list” in packit/deployment#575
- [x] (optionally) open a ticket to adjust the firewall rules
  - [ ]  (“optional”) ticket per URL :)
- [ ] (optionally) verify that the sources can be obtained

**Comment by xsuchy** [comment]
I am running:
```
for i in *spec; do
spectool $i |grep Source
done >/tmp/output.txt
```

**Comment by nforro** [comment]
> * scrape all the specfiles

Maybe we should go also through Packit configs, because (at least in theory) `upstream_project_url` can be blocked while `Source0` URL is fine.
