### ISSUE TITLE
Failed Koji build and Bodhi update jobs with no relevant error message

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#2426]
When a Koji build fails to be triggered, user is not really informed about the cause of the failure:
- dashboard [example](https://dashboard.stg.packit.dev/results/koji-builds/463)
- issue [example](https://github.com/packit/ogr/issues/851)

**Comment by majamassarini** [comment]
For the context, I had triggered the Packit exception with this PR https://github.com/packit/ogr/pull/852
I have created the PR to play with the command line and `build in-koji` a scratch build (this was successful). I was testing scratch builds as a way to "trigger" Koschei and I have broken the `ogr` code on purpose to get a `reverse dependency build failure on Koschei`.

**Comment by lbarcziova** [comment]
I didn't mean to close this yet, the service part is done, and I will create followup PR for dashboard.
