### ISSUE TITLE
Previously built Copr PR packages used for buildroot initialization

### ISSUE THREAD

**Issue by jan-kolarik** [packit/packit-service#2432]
In dnf5, we use Packit to run CI tests on pull requests in GitHub.

Once the dnf5 package is successfully built, it becomes part of the Copr repository associated with the GitHub pull request. Any subsequent changes to the pull request retrigger the CI tests and the RPM package build in the same Copr repository containing previously built packages.

Since dnf5 is used to build packages, including itself, it is installed during buildroot initialization using the previously built version from the Copr repository. If this version has a runtime issue, it can affect the buildability of subsequent packages in the pull request.

The only workaround is to create a new pull request, which generates a new Copr repository.

**Comment by hroncok** [comment]
Copr chroots can be configured to use mock bootstrap images. That should prevent this issue.

**Comment by lachmanfrantisek** [comment]
Thanks @hroncok for suggesting this! Looks like this is [also configurable via API](https://python-copr.readthedocs.io/en/latest/client_v3/proxies.html#copr.v3.proxies.project.ProjectProxy.edit). This would be really handy!

In the meantime, I've discussed this with the Copr team and they've suggested taking a look at "Copr project directories" (~subproject). It's not documented much and could change a bit but still worth considering -- the directories should not influence each other.

**Comment by jamacku** [comment]
We have hit the same issue in chkconfig/alternatives:
- https://github.com/fedora-sysv/chkconfig/pull/128

The initial PR caused alternatives to segfault. Alternatives are in minimal buildroot so any follow-up commits ended with the Packit copr build failing.

We went the same route as @jan-kolarik, and Packit passed since it installed the package from Fedora instead of from copr.

- https://github.com/fedora-sysv/chkconfig/pull/132

But for some reason, it also rewrote the status checks on the original PR. :confused: So PR 128 has status checks from PR 132.

**Comment by jamacku** [comment]
@lachmanfrantisek, Do you have any updates regarding this issue? It's very inconvenient to have to open new PRs every time we encounter this problem.

Thank you

e.g. https://github.com/fedora-sysv/chkconfig/pull/135

**Comment by lachmanfrantisek** [comment]
@jamacku thanks for the ping. Will prioritise this one -- adding a config option to set a mock bootstrap image sounds like being more easier to do compared to swapping to Copr directories. So, if this works, we will go that way.

**Comment by nforro** [comment]
@jan-kolarik @jamacku The change has been deployed, could you please try the new [bootstrap](https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters) option and verify that it can be used to solve your issue(s)? If not, we will prioritize and implement [this](https://github.com/packit/packit-service/issues/2539) instead.

**Comment by jan-kolarik** [comment]
> @jan-kolarik @jamacku The change has been deployed, could you please try the new [bootstrap](https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters) option and verify that it can be used to solve your issue(s)? If not, we will prioritize and implement [this](https://github.com/packit/packit-service/issues/2539) instead.

Great, thanks for fixing this! I’ll make a note to test it, but it generally can’t be easily verified by just intercepting the existing pull requests, since a runtime error needs to occur in the initial build that was pushed within the PR.
