### ISSUE TITLE
Confusing PackitCoprProjectException 

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#2459]
@lsm5 reported several times having received the following message the last few days. One example is [here](https://github.com/containers/podman/pull/23212)

```
Cannot create a new Copr project (owner=packit project=containers-podman-23212 chroots=['centos-stream-10-aarch64', 'centos-stream-9-x86_64', 'centos-stream-10-x86_64', 'centos-stream-9-aarch64']): Response is not in JSON format, there is probably a bug in the API code.
```

This is caused by a PackitCoprProjectException; the error is misleading, probably we are receiving a `500` error from Copr Service, there was instability on the Copr side recently, and we should give a meaningful feedback to the users. If we get a 500 error we should suggest the users to take a look on the Copr service side.

This exception is handled [here](https://github.com/fedora-copr/copr/blob/d8013c4fe8753069d90bfb8cb18d1ee2c7b6d4fe/python/copr/v3/requests.py#L150-L151) and [here](https://github.com/packit/packit/blob/6ce83fcc2b6efd24db9b30e6ca1ae3196bad3bdf/packit/copr_helper.py#L232-L239).

- [ ] if it is a `500` status code then suggest to the user to check the Copr Service
- [ ] for other status code always report them in the final exception to be able to debug them properly.

**Comment by nforro** [comment]
This seems to be happening quite often lately, we should probably check with the Copr team.
