### ISSUE TITLE
'NoneType' object has no attribute 'projects_cloned_using_cache'

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#2460]
Since July the 2nd the following error is raised after a downstream sync release:

```
'NoneType' object has no attribute 'projects_cloned_using_cache'
```

After merging [this PR](https://github.com/packit/packit/pull/2341) there were no more errors like the above in production.

Even though the same code is in staging the error is still happening in the staging instance.

**Comment by mfocko** [comment]
Linked PR merges with https://github.com/packit/packit/commit/1954e49a822f8c5a4a6c8d789d8995798f0ec7f0

The latest Sentry event on stage has:
| package          | version                       |
| ---------------: | ----------------------------- |
| `ogr`            | `0.49.2.post1.dev2+gdb653b8`  |
| `specfile`       | `0.30.0`                      |
| `packit`         | `0.97.3.post1.dev5+g9f475280` |
| `packit-service` | `0.1.dev1+g7fb8d36.d20240702` |

Which matches this commit https://github.com/packit/packit/commit/9f47528040e3ee9bfc68d51f030b74d38bb82207 (one merge before the linked PR with a fix)

**Comment by lbarcziova** [comment]
@mfocko thanks for providing the details, then I would say it should be safe to close this.
