### ISSUE TITLE
Use official epel9 builds for the `osh-cli` package

### ISSUE THREAD

**Issue by siteshwar** [packit/packit-service#2476]
This is a follow up on https://github.com/packit/packit-service/pull/2474#discussion_r1692102435

I have submitted an official build for osh package for epel9 through https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-697de2e48a. Once that is in stable, `osh-cli` package should be installed from there.

**Comment by mfocko** [comment]
Do you think it would make sense to enable the release builds in Copr, like we have [here](https://github.com/packit/packit/blob/2e75e6ff4c0cadb55da1c8daf9315e4b0a69e4a8/.packit.yaml#L94-L101)? Right now they cannot be triggered manually for releases, but it sounds like a reasonable solution in the meantime
