### ISSUE TITLE
Add gitlab support

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#249]
People are looking for this, I do not see an issue for it but I know it is planned.

**Comment by lachmanfrantisek** [comment]
- [x] packit-as-a-tool is ready
- [ ] we need to investigate, what is needed to have a "gitlab-app" (or what is the workflow there).
  - Are just webhooks enough?
  - Is it worth it? / Is it a priority for us? / How many projects will use it?
  - How much time it will take to us? How much code we can share with github?

**Comment by TomasTomecek** [comment]
>     * [x]  packit-as-a-tool is ready

Even the code which parses origin remote url?

>       * Are just webhooks enough?
>       * Is it worth it? / Is it a priority for us? / How many projects will use it?
>       * How much time it will take to us? How much code we can share with github?

+1

will add more to your list

**Comment by lachmanfrantisek** [comment]
> Even the code which parses origin remote url?

It 'should' work as well.

**Comment by Conan-Kudo** [comment]
GitLab has an equivalent concept of Integrations, but those need to be added to the GitLab codebase itself. There's no extensible "app" model.

**Comment by lachmanfrantisek** [comment]
> GitLab has an equivalent concept of Integrations, but those need to be added to the GitLab codebase itself. There's no extensible "app" model.

Thanks for the info. I need to take a look at how hard is to add it and how it can work with custom instances. It looks like a long-term wish. We have to work on the GitHub app at first.

**Comment by grapheo12** [comment]
Hello. I saw this issue posted as a Project Idea for GSoC 2020. I am interested to work on it. Can I get some resources regarding the CI methods of Gitlab (like Github webhooks) and how to test the implementation? 
Is there any reference implementation (some other packaging service in Gitlab) which is a benchmark for this?
Also is there a need to integrate testing with this feature?
@lachmanfrantisek

**Comment by lachmanfrantisek** [comment]
@grapheo12 thank you for your interested!

> I am interested to work on it.

Currently, it's to soon to start working on it -- now, you have time to get familiar with the project and solve some basic issues..;)

> Can I get some resources regarding the CI methods of Gitlab (like Github webhooks) and how to test the implementation?

The "research" of this is a part of the GSOC task, but if you want some info now, the gitlab docs is a good place to start with:

- https://docs.gitlab.com/ee/user/project/integrations/webhooks.html
- https://docs.gitlab.com/ee/integration/README.html
- https://docs.gitlab.com/ee/user/project/integrations/project_services.html

> Is there any reference implementation (some other packaging service in Gitlab) which is a benchmark for this?

Some examples are mentioned in the docs:
- https://docs.gitlab.com/ee/integration/README.html
- https://about.gitlab.com/handbook/marketing/product-marketing/demo/integrations/

> Also is there a need to integrate testing with this feature?

- If you mean tests for our code, then yes:
  - We are using [flexmock](https://github.com/bkabrda/flexmock/) for unit and some integration tests.
  - We are using [our own library called requre](https://github.com/packit-service/requre) for real integration tests.
- If you mean the testing part of the workflow (the *Testing Farm*), then yes.
  - We want to have the same functionality for GitHub as well as for GitLab.

**Comment by nmav** [comment]
I can potentially help with testing in one or all of:
 - https://gitlab.com/ipcalc/ipcalc/
 - https://gitlab.com/gnutls/gnutls/
 - https://gitlab.com/openconnect/ocserv
 - https://gitlab.com/openconnect/openconnect

**Comment by lachmanfrantisek** [comment]
@nmav thanks!

It will probably take some time to make something useful but would be nice to have some real packages to test it.

**Comment by tyll** [comment]
> > GitLab has an equivalent concept of Integrations, but those need to be added to the GitLab codebase itself. There's no extensible "app" model.
> 
> Thanks for the info. I need to take a look at how hard is to add it and how it can work with custom instances. It looks like a long-term wish. We have to work on the GitHub app at first.

It would be nice to be able to use packit for https://gitlab.freedesktop.org/NetworkManager/NetworkManager to build a Copr for each merge request.

**Comment by anirudhnarayanan** [comment]
Hi,
I am really fascinated by this project. I just had a clarification regarding something you said.
"Currently, it's to soon to start working on it -- now, you have time to get familiar with the project and solve some basic issues"

By basic issues do you mean issues issues part of the packit service repository which we are to fix and send pull requests for?

**Comment by lachmanfrantisek** [comment]
> By basic issues do you mean issues issues part of the packit service repository which we are to fix and send pull requests for?

Look around the projects in the [packit service organisation](https://github.com/packit-service), how they are coupled and you can try fixing issues in any of them. (The most important ones are [ogr](https://github.com/packit-service/ogr), [packit](https://github.com/packit-service/packit), [packit-service](https://github.com/packit-service/packit-service), [sandcastle](https://github.com/packit-service/sandcastle), and [dashboard](https://github.com/packit-service/dashboard).)

**Comment by lachmanfrantisek** [comment]
:rocket: The implementation is there for some time, so let's close this EPIC and create smaller, more specific issues if needed.

Just to summarize:
* To enable the project, you need to setup webhook in your project settings.
* We need to have a user on the instance (gitlab.com only by now, let us know if you need some other instance)
* There are two options how we can verify your webhooks:
  * We agree on some static token that we add to our configuration.
  * You don't set any token when configuring the webhook and we will send you a project-specific token on the first run as a confidential issue. (You will add it to the webhook settings after that.)
* We have some information [here](https://packit.dev/docs/faq/#can-we-use-packit-with-gitlab).

Note that we don't use it much ourselves and there are probably still some problems, so please, try it and let us know.

Here is an example of how it works:
* https://gitlab.com/packit-service/hello-world/-/merge_requests/9
