### ISSUE TITLE
improve `/packit propose-update` behaviour

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#252]
Tried to investigate
https://sentry.io/organizations/red-hat-0p/issues/1345950807
which had been triggered by `/packit propose-update` comment in
https://github.com/ansible-community/ansible-bender/pull/190

but have more questions than answers:
- the event was parsed as `PullRequestCommentEvent` even there's no `"pull_request"` in `event["issue"]`
- handler was `GitHubIssueCommentProposeUpdateHandler` even this is a PR comment

We've changed the parsing code a lot recently so let's redeploy the changes to `prod` and try to reproduce this again.

**Comment by jpopelka** [comment]
The problem is probably that we expect the `/packit propose-update` to be used in issues only.

How do we want to fix this?
- enable `/packit propose-update` to be used also in PRs?
- comment in a PR that `/packit propose-update` can be used only in an issue?

**Comment by jpopelka** [comment]
Reproduced in `stg` with latest-greatest:
https://sentry.io/organizations/red-hat-0p/issues/1350697700/

**Comment by lachmanfrantisek** [comment]
For me, it's weird that `/packit propose-update` can only be used in the comments, but  not in issue-title and issue-description.

What about these triggers:
- the issue with the title containing `/packit propose-update`
- comment in the Issue with the title containing `/packit propose-update` (to retriger that)
- comment in the PR, but trigger the process after the merge (?)

**Comment by TomasTomecek** [comment]
AI:
* if the PR is open, refuse to do it - since the code is not merged yet
* enable processing the comment from a merged PR

**Comment by lachmanfrantisek** [comment]
The task here is clear. Not a high-prio but nice to have.

**Comment by lachmanfrantisek** [comment]
We (=I) have changed the related code in the last sprint. I am going to close this. We can open a new issue if the problem preserves.
