### ISSUE TITLE
ACTION REQUIRED: Sentry Project Transactions/Errors Sample Rates

### ISSUE THREAD

**Issue by majamassarini** [packit/packit-service#2526]
As stated in the email received on date September 11th.

We are in `the top 6 projects that are impacting the Transactions quota significantly and these project should take quick action to reduce their Transactions consumption`

Packit transactions in 30 day: 248k
Packit errors in 30 days: 37k

Red Hat overall quota for transactions: 2 million transactions
Red Hat overall quota for errors: 8 million errors

Recommended Actions:
  - [x] Reduce Transaction Sample Rate (traceSampleRate):
         Lowering the transaction sample rate can significantly reduce the volume of data being sent to Sentry.
         [We should already have a low transaction sample rate](https://github.com/packit/packit-service/blob/8e545435bee15d60da6be2c7d9bda851d31715c1/packit_service/sentry_integration.py#L17-L31)

  - [ ] Reduce Error Sample Rate (sampleRate):
         Similar to transaction rates, reducing the error sample rate will help decrease data volume.
         
  - [x] Filter Out Non-Essential Errors and Transactions:
         Utilize Sentry’s ignoreErrors and beforeSend features to filter out less critical data before it’s sent. This ensures that only the most relevant issues are tracked, helping to manage our quota.
         Suppress errors that aren't application errors (e.g linting, typing, etc)
         [We are sending to sentry not just errors but also debug data, but I am not sure this will help with the transaction data](https://github.com/packit/packit-service/blob/8e545435bee15d60da6be2c7d9bda851d31715c1/packit_service/sentry_integration.py#L76-L79)

[According to this overview, now that I check it, there were 7 transactions collected in the last minute](https://red-hat-it.sentry.io/performance/?environment=prod&project=1767823&statsPeriod=24h). This data can cope with the ~250K transactions in a month. Now that I am looking at it, we have:
- 5 transactions/minute for [api.webhooks_github_webhook](https://red-hat-it.sentry.io/performance/summary/?environment=prod&project=1767823&query=http.method%3APOST&referrer=performance-transaction-summary&statsPeriod=24h&transaction=api.webhooks_github_webhook&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
- 0.7 transactions/minute for [task.steve_jobs.process_message](https://red-hat-it.sentry.io/performance/summary/?environment=prod&project=1767823&query=&referrer=performance-transaction-summary&statsPeriod=24h&transaction=task.steve_jobs.process_message&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
- 0.2 transactions/minute for [task.run_copr_build_start_handler](https://red-hat-it.sentry.io/performance/summary/?environment=prod&project=1767823&query=&referrer=performance-transaction-summary&statsPeriod=24h&transaction=task.run_copr_build_start_handler&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

**Comment by lbarcziova** [comment]
The numbers from stats look better now, from the followup email it looks ok as well. In case of additional improvements needed, we can still reduce the error sample rate. Therefore, for now I am closing this.
