### ISSUE TITLE
Configuration for specifiying external copr://owner/project repositories 

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#2530]
### Description

For packages that are released togehter - like "mock" and "python-templated-dictionary" - we often need to build one of those packages first, and make the updated (newer version) version available when CI-building the second one (and sometimes vice-versa).

For Mock, we have https://copr.fedorainfracloud.org/coprs/g/mock/mock-deps/ project where we (sometimes) host pre-release versions of some tools to fixup CI.

It would be nice to say, e.g.:

```
copr_build_external_repositories:
    - copr://@mock/mock-deps
```
    
  

### What is the impacted category (job)?

Copr builds

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
hi @praiskup , just to clarify, is this something else than [`additional_repos`](https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters)?

**Comment by praiskup** [comment]
tps://github.com/rpm-software-management/mock/pull/1461
