### ISSUE TITLE
Not possible to waive test results on Bodhi updates created from sidetags

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2546]
It's possible for users to waive failed tests on regular Bodhi updates created by Packit, but it's not possible to do that on updates created from sidetags, only the owner (creator) of a sidetag can do it. Clearly the waiving permissions are set up differently for these two cases, though I haven't been able to find any info on this.
This is a blocker for podman releases.

We need to either convince the responsible people/teams to change the permissions, or implement some mechanism that would allow users to ask Packit to waive the results while not allowing misuse.

**Comment by mfocko** [comment]
Maybe mention the waiving in the role rotation card for the Community Shepherd, also reach out to the Bodhi maintainers.

**Comment by nforro** [comment]
Waiving permissions are handled in waiverdb, however this gets blocked in [Bodhi](https://github.com/fedora-infra/bodhi/blob/f08e85dd37a60c7aa68a495668dad04e8ca71a44/bodhi-server/bodhi/server/validators.py#L521-L551), apparently waiving is considered editing an update. It could be possible to waive the tests directly using `waiverdb-cli` and overcome this Bodhi obstruction, however it's undocumented and I haven't been able to test it.

**Comment by nforro** [comment]
I spent so much time on this already that I might just take it :slightly_smiling_face:

**Comment by nforro** [comment]
It looks like https://github.com/fedora-infra/bodhi/issues/4014 is the reason why it was implemented in this way - previously, only maintainters of all builds in the sidetag were able to edit the update. But now only sidetag creator can edit it and not the maintainers, so I would say it's a bug. I'll try to propose a PR to fix it.

**Comment by nforro** [comment]
Here is Bodhi PR: https://github.com/fedora-infra/bodhi/pull/5764

**Comment by nforro** [comment]
The PR has been merged, now we need to wait for the next Bodhi release.
