### ISSUE TITLE
File Fedora Change Proposal for automated onboarding

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2548]
The process is documented [here](https://docs.fedoraproject.org/en-US/program_management/changes_guide). Changes are tied to Fedora version, we should be targeting Fedora 42, [here](https://fedorapeople.org/groups/schedule/f-42/f-42-key-tasks.html) is the schedule.
The important dates are:
- 2024-12-24 - Proposal submission deadline for System Wide Changes
- 2025-01-14 - Proposal submission deadline for Self Contained Changes
- 2025-02-04 - Change completion deadline (testable)
- 2025-02-18 - 100% code complete deadline

**Comment by lbarcziova** [comment]
Proposal submitted: https://fedoraproject.org/wiki/Changes/AutomatedPackitOnboarding

**Comment by lbarcziova** [comment]
Published:  https://discussion.fedoraproject.org/t/f42-change-proposal-automated-onboarding-to-packit-release-automation-for-new-packages-system-wide/139530
