### ISSUE TITLE
Retriggering propose-downstream seems to ignore configured `fast_forward_merge_into` branches

### ISSUE THREAD

**Issue by nforro** [packit/packit-service#2551]
I have retriggered a failed propose-downstream job of specfile using the Re-Run button on GitHub and the new job finished successfully, however it only updated the already existing (from previous run) `rawhide` PR and didn't create/update PRs for `fast_forward_merge_into` branches.
That being said, I have also triggered pull-from-upstream (that for some reason hadn't been triggered automatically) using a comment in an open `rawhide` PR and the job finished successfully and opened PRs for `rawhide` and also all configured `fast_forward_merge_into` branches.

**Comment by majamassarini** [comment]
Probably, [this is the wrong code](https://github.com/packit/packit-service/blob/b58b3b71db4ed46f78da465978348fa58c68a631/packit_service/worker/helpers/sync_release/sync_release.py#L54-L64)
In case of fast forward branches we should not skip them.
