### ISSUE TITLE
The `epel-all-x86_64` target doesn't build for epel-10-x86_64 in Copr

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#2654]
### What happened? What is the problem?

SSIA, the fedora-distro-aliases (probably correctly?) reports epel-all as:

```
[Distro({'name': 'EPEL-8', 'long_name': 'Fedora EPEL 8', 'version': '8', 'state': 'current', 'branch': 'epel8', 'id_prefix': 'FEDORA-EPEL', 'version_number': '8'}),
 Distro({'name': 'EPEL-9', 'long_name': 'Fedora EPEL 9', 'version': '9', 'state': 'current', 'branch': 'epel9', 'id_prefix': 'FEDORA-EPEL', 'version_number': '9'}),
 Distro({'name': 'EPEL-10.0', 'long_name': 'Fedora EPEL 10.0', 'version': '10', 'state': 'current', 'branch': 'epel10', 'id_prefix': 'FEDORA-EPEL', 'version_number': '10'})]
```

Copr provides epel-10 build target, and it would be nice if `epel-all` triggered builds there.

Work-around: Specify epel-10-x86_64 build target manually.

CC @frostyx, @carlwgeorge.

### Steps to reproduce

```bash
1.
2.
3.
```

### What is the impacted category (job)?

Copr builds

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lbarcziova** [comment]
hi! The alias gets expanded to include `epel-10.0` (and in packit/packit#2470 we also just switched to using `fedora-distro-aliases`, which should be in prod tomorrow), but the problem is then in the mapping to the build/test targets. This is tracked in packit/packit#2438.

**Comment by praiskup** [comment]
Ah, I thought distro-aliases is already in use :-) this is a duplicate then, closing in favor of #2438.
