### ISSUE TITLE
Use-case: continuous builds into a Koji tag

### ISSUE THREAD

**Issue by jlebon** [packit/packit-service#372]
Hi,

Project looks very interesting!

One use-case here I don't see explicitly listed (though I think can reasonably fall under Packit's scope) is doing continuous builds from an upstream repo. In Fedora CoreOS, we'd like [our build tools to be rebuilt continuously](https://github.com/coreos/fedora-coreos-tracker/issues/84). We've recently acquired a [Koji tag](https://pagure.io/releng/issue/8165) to do this, which works well, but we really want to automate this process.

IOW, would be nice if Packit-a-a-S supported the following:

- watch for every git push in an upstream repo
- on push events, create an SRPM and submit Koji build targeting specific tag

At least Packit knows [how to build SRPMs](https://github.com/packit-service/packit/blob/master/docs/srpm.md) from upstream content, so the first part seems covered. What would be nice is if that feature was kept separate from the `propose-update` workflow. I.e. we want to be able to have *both* continuous builds, as well as regular "release" builds which follow the usual dist-git -> Koji -> Bodhi flow.

(To confirm, there's no Packit-a-a-S deployed anywhere yet, right?)

---

Written by @TomasTomecek 
The work which needs to be done to make this work:
* [ ] Packit service can send a build to koji as a reaction to a specific event
* [ ] Job definition is implemented ([with a handler and the specific event type](https://github.com/packit-service/packit-service/blob/master/CONTRIBUTING.md#how-to-add-a-new-job))
* [ ] People can configure if the builds are meant to be scratch or pick a koji target

**Comment by dustymabe** [comment]
hey @TomasTomecek - if we could enumerate some of the work to be done it might make it easy for a new team member or an external contributor to help. Do you think you could describe the work that needs to be done?

**Comment by TomasTomecek** [comment]
@dustymabe I added a brief task list to Jonathan's first post.

The good thing is that we've already done the plumbing code in packit itself, now we just need to define the job in packit-service and implement a handler for it. I hope that next sprint (in one week) we should start adding such code in packit-service since we need it for the centos stream work anyway.

**Comment by TomasTomecek** [comment]
Franta is working on koji builds this sprint, unassigning myself

**Comment by jlebon** [comment]
Any updates on this? Or something you'd like us to take for a spin to test?

**Comment by lachmanfrantisek** [comment]
@jlebon Sorry, still too many other things around. But the sending part is in review: #547 

When it's merged, it will be available on our staging app. The missing pieces after that are showing the response and document everything.

**Comment by lachmanfrantisek** [comment]
You will be able to have builds (or scratch ones) for release, branch or PR commits.

**Comment by TomasTomecek** [comment]
@lachmanfrantisek this is relevant, correct? https://github.com/packit-service/packit-service/pull/657

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek this is relevant, correct? #657

Yes, this should bring the last part, reporting back the results. (Only commit status for now. No retriggering possible yet.)

**Comment by TomasTomecek** [comment]
> > @lachmanfrantisek this is relevant, correct? #657
> 
> Yes, this should bring the last part -- reporting back the results. (Only commit status for now. No retriggering possible yet.)

nice, shall we close this then?

we can also provide guidance who's interested in setting this up for their projects

**Comment by LorbusChris** [comment]
:+1: Documentation or example configs for this feature would be highly appreciated! :)

**Comment by lachmanfrantisek** [comment]
> +1 Documentation or example configs for this feature would be highly appreciated! :)

It's already in our docs page:
https://packit.dev/docs/configuration/#supported-jobs -> production_build

**Comment by lachmanfrantisek** [comment]
> nice, shall we close this then?

I am not sure if the original issue is covered but all of your bullet points are done.

> on push events, create an SRPM and submit Koji build targeting specific tag

We don't support setting tags yet.

**Comment by TomasTomecek** [comment]
let's close this then

> We don't support setting tags yet.

seems like we do :)

    targets – a (list of) targets we want to build for, list of supported targets can be listed using with koji list-targets

@LorbusChris please let us know if the documentation is sufficient, and if not, we can work with you to set this up

**Comment by LorbusChris** [comment]
Thanks, it looks pretty straight forward, I'll set something up soon :)

I do have one question though:
What user does the builds in Koji?
Is it my own user, or a `packit` user? If it's the latter, do I need to add it to the list of maintainers for the given RPM?

**Comment by lachmanfrantisek** [comment]
> What user does the builds in Koji?

It's same for everything we do:
- If you use packit CLI, it will use your own user/authentication.
- If you use packit-service (the GitHub app), it will use our user -- so yes, you will probably need to give us(=our user) the permissions.

**Comment by lachmanfrantisek** [comment]
> seems like we do :)

Yes, my bad. I was confused about `tags`/`targets` difference...  (Funny that it was me who implement that..;)

**Comment by lachmanfrantisek** [comment]
> let's close this then

OK, closing the issue since the koji-builds are supported.

Please, create a new, specific, issue if you want a new trigger or miss some feature. Thanks!
