### ISSUE TITLE
upstream_tag_template - tag_name is not version

### ISSUE THREAD

**Issue by dhodovsk** [packit/packit-service#392]
for `upstream_tag_template` in packit config there is only the following info:
```
packit by default expects git tags to match versions (e.g. when doing the propose-update command) - if you are using a different tagging scheme, let’s say v1.2.3 you can then set this parameter to v{version} and packit will fill in the version argument
```
But right now in packit-service code, the version == tag-name. So when someone wants to release with the tag v1.2.3, and has `upstream_tag_template: v{version}` in config, packit attempts to checkout `vv1.2.3`, which does not exist.

We need to either correct the doc or the behavior.

Related code:
https://github.com/packit-service/packit-service/blob/14777bb683b5cd6021103501d274952f5ba785ab/packit_service/worker/github_handlers.py#L199-L201

https://github.com/packit-service/packit/blob/022bff82d16ebe2d533daa8ca26ddc24be2a2dc7/packit/api.py#L194

https://github.com/packit-service/packit/blob/022bff82d16ebe2d533daa8ca26ddc24be2a2dc7/packit/api.py#L202-L204

**Comment by sgallagher** [comment]
If I leave off the `upstream_tag_template`, I end up with packages built with

```
Name: libmodulemd
Version: libmodulemd-2.9.0.git<blah>
```
which results in RPMs named `libmodulemd-libmodulemd-2.9.0.git<blah>...`

**Comment by TomasTomecek** [comment]
I'd say this is a bug in our code: we should only use the tag_template when doing `packit srpm` - that's when packit doesn't know anything about the tagging scheme and needs help.

In packit service when doing a Fedora update, our trigger is the GitHub release - we know the name of the tag and we ~~don't need to~~ shouldn't use the tag_template.

Does this make sense?

**Comment by sgallagher** [comment]
We still need some sort of a mechanism to tell packit to produce the `Version:` field using a substring of the tag. If my tag is `libmodulemd-2.9.0`, I need Packit to understand that it should only use the `2.9.0` portion.

**Comment by TomasTomecek** [comment]
> We still need some sort of a mechanism to tell packit to produce the `Version:` field using a substring of the tag. If my tag is `libmodulemd-2.9.0`, I need Packit to understand that it should only use the `2.9.0` portion.

hmmm, that's interesting, so we were only thinking about one side (version -> tag) and not the other (tag -> version)

@sgallagher we are getting a ton of metadata from GitHub, would there be something which contains the proper version string? Nevertheless, your upstream spec file should have an up to date version in the ref associated with the release - would that be a solution?

**Comment by sgallagher** [comment]
So, the `Version:` and `Release:` fields in my case were my own fault. I wasn't using `current_version_command` and it was defaulting to `git describe`.

However, the release ultimately still failed due to this bug in https://github.com/fedora-modularity/libmodulemd/issues/451

**Comment by sgallagher** [comment]
For the record, I'll cast my vote for fixing the behavior such that it uses `version` here rather than `tag_name`.

**Comment by ernestask** [comment]
I think @sgallagher has a point here. At least in my mind, tag templates will necessarily include a version token, so we could do string matching.

**Comment by lbarcziova** [comment]
> I'd say this is a bug in our code: we should only use the tag_template when doing packit srpm - that's when packit doesn't know anything about the tagging scheme and needs help.
In packit service when doing a Fedora update, our trigger is the GitHub release - we know the name of the tag and we don't need to shouldn't use the tag_template.
Does this make sense?

I would say that the documentation is meant to describe the behaviour in packit CLI. There during the `propose-update` we get the `version` of the latest release (we could possibly change it to also get `tag` using ogr ), so when the tag is different from the version, `upstream_tag_template` should be used.
On the other hand, in service we know the tag name directly, as you said, so the template should not be used.

**Comment by TomasTomecek** [comment]
So what's the expected work to be done here? Is the solution proposed by @lbarcziova sufficient?

**Comment by lachmanfrantisek** [comment]
We've changed this in recent history. @sakalosj haven't you fix this as well?

**Comment by sakalosj** [comment]
yes, this is fixed in 
https://github.com/packit/packit/pull/959
https://github.com/packit/packit/pull/1013

**Comment by lachmanfrantisek** [comment]
Thanks @sakalosj
