### ISSUE TITLE
Better logs

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#419]
Since we are publishing the debug logs in the packit-service (e.g. https://stg.packit.dev/copr-build/19/logs), we need to think about them more now.

- format of the log output
- content of the logs (consistency, what/when to log, what is debug/info/warning/...)

Related to https://github.com/packit-service/packit/issues/719

**Comment by lachmanfrantisek** [comment]
Can we somehow turn off these type of messages in worker? It's very messy because of them.

```

[2020-03-11 12:52:09,770: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
```
```
[2020-03-11 12:52:40,459: DEBUG/MainProcess] pidbox received method ping() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '6cb53494-3364-3f98-a2dc-eeb5bf039860'} ticket:3436c9ac-44ef-4c94-b44b-9a8094e7838a]
```

**Comment by jpopelka** [comment]
Hmm, they should have already been turned off.

Something's wrong with
https://github.com/packit-service/packit-service/blob/master/files/run_worker.sh#L10

**Comment by lachmanfrantisek** [comment]
> Hmm, they should have already been turned off.

OK, it's from stage... Do we need them on stage?

**Comment by lachmanfrantisek** [comment]
@lbarcziova Can we consider this as fixed or is your PR just a part of it?

**Comment by lbarcziova** [comment]
@lachmanfrantisek my PR was mainly focusing on the format, so it is just the first point.

**Comment by lachmanfrantisek** [comment]
Anything more specific we can do here?

**Comment by TomasTomecek** [comment]
I'd say the best solution here is to start utilizing the dashboard (and ideally get rid of the build result page); I propose to close it
