### ISSUE TITLE
separate packit-service api from packit service

### ISSUE THREAD

**Issue by sakalosj** [packit/packit-service#430]
TODO:
- [ ] Separate the API code from the packit-service repo.
- [ ] New pod for the API.
- [ ] ???

*Original issue description:*
> I think, web api and packit-service should be separated, as fedmsg.
>
> In packit-service can run event loop in which we can perform various actions e.g.
>
> * check if long running tasks are still running and update state based on accordingly
> * perform checks of dependent services and act based on result - postpone tasks, re-trigger failed > tasks, ...

**Comment by lachmanfrantisek** [comment]
- I definitely agree with the code restructure. (As we discussed on the arch-meeting.)
- Not sure about the loop -- @dhodovsk understand the celery better, but we can probably use the celery built-in solutions instead of reinventing our custom solution. (e.g. If I remember it right, retriggering is just about some setup and returning specific results/errors.)

**Comment by dhodovsk** [comment]
Using celery, you can set soft or hard timeouts on workers or tasks -https://docs.celeryproject.org/en/stable/userguide/tasks.html

For retrying the tasks, celery's autoretry might be of help - https://docs.celeryproject.org/en/stable/userguide/tasks.html#automatic-retry-for-known-exceptions
There is a possibility to set exponential backoff so the retry can happen at reasonable intervals.

**Comment by dhodovsk** [comment]
Related issues:
 - https://github.com/packit-service/packit-service/issues/25
 - https://github.com/packit-service/packit-service/issues/225

**Comment by TomasTomecek** [comment]
@sakalosj I don't understand what does the rest api have to do with tasks - they are completely different things. It also seems like you're trying to reimplement celery functionality. Please provide more details.

**Comment by sakalosj** [comment]
@lachmanfrantisek @TomasTomecek 

* from time to time we are not receiving some messages from fedmsg (e.g. copr_build_finished).
 Because of we are using fedmsg as primary communication source, polling should be fallback behavior. In my opinion, creating and executing delayed task to check something just in case,  is not clean design.
* it will give us more flexibility in other features implementation.
* we can store state of dependent services (for usage in dashboard). 

I know everything can be done in different places of existing code, but want to make it easier to understand and maintain, by following Single responsibility principle.

**Comment by sakalosj** [comment]
> Using celery, you can set soft or hard timeouts on workers or tasks -https://docs.celeryproject.org/en/stable/userguide/tasks.html
> 
> For retrying the tasks, celery's autoretry might be of help - https://docs.celeryproject.org/en/stable/userguide/tasks.html#automatic-retry-for-known-exceptions
> There is a possibility to set exponential backoff so the retry can happen at reasonable intervals.

thanks for links

**Comment by lachmanfrantisek** [comment]
> Single responsibility principle.

That's why I want to outsource it to Celery..;)

**Comment by TomasTomecek** [comment]
> @lachmanfrantisek @TomasTomecek
> 
>     * from time to time we are not receiving some messages from fedmsg (e.g. copr_build_finished).
>       Because of we are using fedmsg as primary communication source, polling should be fallback behavior. In my opinion, creating and executing delayed task to check something just in case,  is not clean design.
> 
>     * it will give us more flexibility in other features implementation.
> 
>     * we can store state of dependent services (for usage in dashboard).
> 
> 
> I know everything can be done in different places of existing code, but want to make it easier to understand and maintain, by following Single responsibility principle.

nice explanation but I still don't understand what this issue is about :D

it would be lovely if you could clearly write down what needs to be done in order to complete this work

**Comment by sakalosj** [comment]
* create separate pod packit-web-api (as fedmsg)
* in packit-service create event loop to check old tasks waiting for end notification  
* launch  celery task to poll for current status with random delay and update log

is this enough or do you want more details?

**Comment by thrix** [comment]
Just putting out it as an idea, if you would have come to a state where you need to manage a workflow of tasks, look at https://github.com/selinon/selinon, we are starting to use it for our stuff and looks quite promising (and it was built in RH too \o/). It is built on top of Celery.

**Comment by sakalosj** [comment]
@TomasTomecek 

on stand-up we discussed, with following output:
* we will need separate worker for celery.cron -> separate pod
* create celery.cron job to query db for build tasks  in more than x mins
* run celery tasks based on previous query output
