### ISSUE TITLE
Be able to set required copr repos in the testing farm

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#437]
Idea by tyll: https://github.com/nmstate/nmstate/pull/856#discussion_r384606910

- Be able to specify copr-repos, that needs to be installed in the testing-farm farm to be able to install the actual package.
- What needs to be done on the testing-farm side? (@thrix @psss )
- How we can specify that on our side?
- What about making it more general and running a custom script before the installation?

- [ ] at least, document it

**Comment by psss** [comment]
I think this is just a question of configuration of the prepare step. Here's an example plan:

    prepare:
        script: dnf copr enable -y psss/tmt

We could (and I think there was somewhere already a proposal for that) add a special key for copr so that the config is even more shorter:

    prepare:
        copr: psss/tmt

What do you think?

**Comment by thrix** [comment]
Yes, I believe this will work, and it will enable the copr repo before the artifact installation in the current version of testing farm ...

Note that for the shortcut, we can have it but I do not think it is a priority ...

**Comment by thrix** [comment]
@psss and it will need to be something like:

```
      script:
        - dnf -y install dnf-plugins-core
        - dnf -y copr enable psss/tmt
```

Copr dnf plugin is not installed by default ...

Working on getting this working .,,,

**Comment by thrix** [comment]
The above should now work with Testing Farm.

**Comment by lachmanfrantisek** [comment]
OK, so to conclude: It's the "advanced" setup and user needs to setup fmf. Is that right?

We need to only document that example. (Can I move this to the `packit.dev` repo?)

**Comment by thrix** [comment]
@lachmanfrantisek writing the patch, no need to move issues in my POW

**Comment by lachmanfrantisek** [comment]
We still need to document that.

**Comment by lachmanfrantisek** [comment]
This will be easier with the new testing-farm API. (We already support `additional_repos` for copr builds (#694), we can forward that info to the new testing-farm API as another artifact(s).)
