### ISSUE TITLE
commit status is not updated when requesting a copr-build and PR is not from an admin/writer

### ISSUE THREAD

**Issue by tyll** [packit/packit-service#446]
In
https://github.com/nmstate/nmstate/pull/576

packit as a service did not build the copr package because the PR submitter is not an admin/writer to the repo. I requested a build in https://github.com/nmstate/nmstate/pull/576#issuecomment-593306511 and it seems that packit actually built it. But the status in the checks section still says `Only collaborators can trigger Packit-as-a-Service`

IMHO it should change to "in progress" after a permitted person requested a build and change back to this message when a new commit was pushed (if it wont't build it).

**Comment by lachmanfrantisek** [comment]
@tyll thanks for letting us know.

It "should" do it as you described. The PR status is actually the status of the last commit, but it looks good:
![Screenshot from 2020-03-02 12-51-03](https://user-images.githubusercontent.com/20214043/75674071-9ac10180-5c84-11ea-8d92-f010cca7bd75.png)
![Screenshot from 2020-03-02 12-51-12](https://user-images.githubusercontent.com/20214043/75674068-9a286b00-5c84-11ea-91de-d26a187b3a1e.png)

Maybe some GitHub caching?

**Comment by tyll** [comment]
Interesting, I see the different status in the commit list but at the bottom of the conversation tab it only shows the failed status for each packit job:

![Conversation status](https://user-images.githubusercontent.com/197720/75678908-f0021080-5c8e-11ea-9dae-e56aafd145a5.png)

Usually this is updated right away. Not sure if this is now a GitHub problem or a packit problem.

**Comment by lachmanfrantisek** [comment]
Yes, I can see this as well.

Github does not have anything like PR status, they have only commit status and it's set correctly. Looks like a GitHub problem but I'll leave this open for a while for a case it will repeat.

**Comment by TomasTomecek** [comment]
@lachmanfrantisek There actually is PR status as well. Look at a pull request and there is a tab - checks.

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek There actually is PR status as well. Look at a pull request and there is a tab - checks.

It's only a dedicated view. Those checks are the checks of the HEAD commit of the PR.

**Comment by tyll** [comment]
> > @lachmanfrantisek There actually is PR status as well. Look at a pull request and there is a tab - checks.
> 
> It's only a dedicated view. Those checks are the checks of the HEAD commit of the PR.

The "checks tabs" is used by a different/newer API AFAIU. Not all checks that are visible for a commit appear in the "Checks" tab.

**Comment by lachmanfrantisek** [comment]
> The "checks tabs" is used by a different/newer API AFAIU. Not all checks that are visible for a commit appear in the "Checks" tab.

Thanks, good to know. (We are still using the "old" API.)

**Comment by TomasTomecek** [comment]
what's the status here? should we revisit this once we redeploy prod? or is there something on p-s' side which we should fix?

**Comment by lachmanfrantisek** [comment]
> what's the status here?

see my comment:
*> Looks like a GitHub problem but I'll leave this open for a while for a case it will repeat.*

> should we revisit this once we redeploy prod? or is there something on p-s' side which we should fix?

I can check it after redeploy but, I still believe that the problem is not on our side.

**Comment by TomasTomecek** [comment]
I am going to close this one since I presume this is already fixed - we didn't have related issues for this recently and also the code for this changed significantly for the past 9 months. Thank you for taking time opening the issue and trying packit!
