### ISSUE TITLE
Some projects do not have issues enabled

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#457]
* We traceback when we want to create an issue on repository that has no issue tracker (e.g. https://github.com/dhodovsk/packit)
* we need to add this functionality to the [ogr](https://github.com/packit-service/ogr):
  Requires: packit/ogr#664

**Comment by TomasTomecek** [comment]
what's the expected workflow here? how do we let the user know that something's wrong?

**Comment by lachmanfrantisek** [comment]
> what's the expected workflow here? how do we let the user know that something's wrong?

- We probably cannot do anything. We can set the status for commits but that's all we can do.
- Do we have some real example? (That one was only a fork created by Dominika.)
- It looks like the solution for us is to not fail in this case.

**Comment by TomasTomecek** [comment]
+ let's just fix the traceback

**Comment by lachmanfrantisek** [comment]
Still valid.

**Comment by lachmanfrantisek** [comment]
It's really a good-first-issue. Let's leave it open for some newcomers...

**Comment by lachmanfrantisek** [comment]
After some time we do have some real examples, e.g. all distgit repositories (e.g. https://src.fedoraproject.org/rpms/packit/) that use Bugzilla instead of the Pagure issues.
