### ISSUE TITLE
p-s to react to new commits in a d-g branch and be able to do builds

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#46]
TODO

* [ ] react to push events on dist-git
* [ ] be able to submit koji builds if a new push comes
* [ ] also implement service's side of https://github.com/packit/packit/issues/264

**Comment by TomasTomecek** [comment]
I recall we got a request for this in jira, so let's keep this open.

**Comment by TomasTomecek** [comment]
hello @lachmanfrantisek :)

**Comment by lachmanfrantisek** [comment]
Still relevant. Will be possible after we finish the koji jobs from upstream.

**Comment by lachmanfrantisek** [comment]
I would really like to see this.

**Comment by TomasTomecek** [comment]
I wish we could make this into next GSoC

**Comment by lachmanfrantisek** [comment]
This will be a really nice feature to have but we have a lot of work with higher priority to do -- dashboard, quicker responses, bugs, UX...

New features like this are sadly on the bottom of our backlog. But as I wrote above, I would still like to see this implemented.

**Comment by lachmanfrantisek** [comment]
Closing in favour of #55
