### ISSUE TITLE
It seems like Packit isn't triggering on PRs from contributors?

### ISSUE THREAD

**Issue by puiterwijk** [packit/packit-service#481]
In https://github.com/fedora-iot/zezere/pull/37, a contributor submitted a new PR and Packit never seems to have started, nor did it supply a comment with why not.

**Comment by jpopelka** [comment]
IMHO the same cause as in #482

**Comment by puiterwijk** [comment]
@jpopelka Except that this issue was 4 days ago, and not today. And it seems like Packit never even set the Pending status with links, which it did on the issues affected by #482?

**Comment by TomasTomecek** [comment]
So the use case is that a contributor submitted a PR and packit did not set any statuses on the PR. As far as I could tell while looking at the PR, the contributor did not have commit rights in repo.

@lachmanfrantisek could this be related to your giant refactor work?

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek could this be related to your giant refactor work?

Anything can be related...;) It's possible that I've removed the setting of the error status.

In the meantime, there were some changes related to this. Some rewording of messages and also the code changes (@csomh sent those changes if I remember correctly).

**Comment by csomh** [comment]
Was #445

**Comment by puiterwijk** [comment]
@TomasTomecek Yeah, at the time he submitted the PR (and Packit did not take action), the contributor did indeed not have write access to the repository.
After I ran "/packit build", it did get triggered, so I guess the issue comes down to that it didn't tell me I needed to run that :).

**Comment by lachmanfrantisek** [comment]
OK

So what can we do to improve that?

- Mention the `/packit build` in the comment if someone triggered the build via comment.
- On push, we show only a status:
  - Can we easily show that info there? (The length is very limited.)
  - Can we add a static URL (to docs?) with the instructions?
  - Creating comments also for this would be too spammy I think.

**Comment by TomasTomecek** [comment]
>       * Can we add a static URL (to docs?) with the instructions?

Sounds good, I'd do that.

**Comment by lachmanfrantisek** [comment]
Still needs a documentation update.

**Comment by lachmanfrantisek** [comment]
> > ```
> >   * Can we add a static URL (to docs?) with the instructions?
> > ```
> 
> Sounds good, I'd do that.

@TomasTomecek Have you done that?

I see that we are using `FAQ_URL = "https://packit.dev/packit-as-a-service/#faq"` for whitelisting problems and no url for user permissions:

https://github.com/packit-service/packit-service/blob/aba85da2b1cd879d7df6c3b83ee57caf1f09490d/packit_service/worker/whitelist.py#L256-L259

https://github.com/packit-service/packit-service/blob/211fcb2333a58a718df5764d24c233e1429a7867/packit_service/worker/handlers/github_handlers.py#L270-L276

**Comment by TomasTomecek** [comment]
> > > ```
> > >   * Can we add a static URL (to docs?) with the instructions?
> > > ```
> > 
> > 
> > Sounds good, I'd do that.
> 
> @TomasTomecek Have you done that?

I haven't :D

In this context, "I'd do that" meant that "I share your opinion and agree with it", not that "I'm going to do that". Will try to write more clearly next time.

Anyway, I'm going to send a PR right now.

**Comment by lachmanfrantisek** [comment]
> In this context, "I'd do that" meant that "I share your opinion and agree with it", not that "I'm going to do that". Will try to write more clearly next time.

@TomasTomecek thanks. I did read that as `I'll` not `I'd`...;) Probably I wanted to see that.;)

**Comment by lachmanfrantisek** [comment]
Since the response has been improved by Tomáš and the code changed a lot since March, I am going to close this issue.

Please, create a new issue if you hit that problem again.

Thanks for letting us know about the issue!
