### ISSUE TITLE
"/packit test" does not trigger builds if there were none before

### ISSUE THREAD

**Issue by psss** [packit/packit-service#535]
Pull request https://github.com/psss/tmt/pull/187 has been created by @FrNecas who is not a contributor of `tmt`, so tests were not scheduled. I manually asked packit to run tests using `/packit test` but tests [failed](https://console-testing-farm.apps.ci.centos.org/pipeline/2a8f5dfd-c28f-472b-ba32-4f849d963e1f) because the copr build has not been created.

**Comment by psss** [comment]
Using both `/packit build` and `/packit test` helped but I believe `/packit test` should be just enough ;-)

**Comment by lachmanfrantisek** [comment]
@psss thanks. The `/packit test` now only retrigger the test (send a new request to the TF).

We should:
- [ ] Try to load the info about build from the database. (Search builds for the PR model.)
- [ ] Act as `\packit build` if there is no build.
  - => We probably need to do the search during the parsing to call correct job.

**Comment by psss** [comment]
It seems this is not fixed. Just ran into the same issue with the https://github.com/psss/tmt/pull/457 where `/packit test` had no effect and I had to use both `/packit build` and `/packit test` to run the tests.

**Comment by TomasTomecek** [comment]
dang, @psss sorry about that, we'll take a look

**Comment by lachmanfrantisek** [comment]
@psss You don't need to use both `/packit build` and `/packit test`. The build itself will trigger the tests.

I am moving to our upstream project so we can take a look into that.

**Comment by psss** [comment]
Does that mean that `/packit test` will also trigger both build and test?

**Comment by lachmanfrantisek** [comment]
@psss No, no. That part needs to be fixed.

But for now, when you want to trigger tests when no builds are there, use `/packit build` (only) instead -- it will run both build and test. (That was just a note that using `/packit test` together with `/packit build` is not necessary.)

**Comment by psss** [comment]
I see, thanks for clarification.

**Comment by lachmanfrantisek** [comment]
@psss Sorry for the confusion, but we removed the check for the PR-author in the meantime (=external contributors are allowed automatically). So, this situation should not happen anymore.

I am going to close the issue but let us know if you found some problem in the future -- I really hope we haven't missed any corner-case.
