### ISSUE TITLE
Add support to build again only failed builds

### ISSUE THREAD

**Issue by StykMartin** [packit/packit-service#540]
It may happen that build will fail in COPR for many reasons e.g. network issue, chroot misconfiguration, mirror repo issue.

In this case, it would be better to try to rebuild failed one instead of running all builds again.
This is a great example [click here please](https://copr.fedorainfracloud.org/coprs/packit/beaker-project-restraint-7/build/1329323/) :crying_cat_face:

**Comment by lachmanfrantisek** [comment]
Yes, that would make sense.

So to make it clear, we want to have support for `\packit rebuild-failed` comment that will retrigger the failed builds.

From the code perspective:
- [ ] new comment command
- [ ] new handler for this job, make sure that:
  - whitelisting works well
  - testing-farm is correctly triggered after the build
  - PR checks are set correctly (the failed updated and the successful not touched)
- Can we reuse the SRPM that was already created?
- Can we have sem for tests? (`\packit retest-failed`)

**Comment by TomasTomecek** [comment]
>     * Can we reuse the SRPM that was already created?

We have to, because then it's not a rebuild any more.

>     * Can we have same for tests? (`\packit retest-failed`)

+1

**Comment by lachmanfrantisek** [comment]
Related to #970.

**Comment by lachmanfrantisek** [comment]
Let's take a look on the Copr's API if we can re-trigger the build without a need to do the SRPM build again or storing it.

**Comment by lachmanfrantisek** [comment]
Since #1213 is implemented, we can now start working on this.

We'll start with #1204 and can take a look into this later. Here, we can either implement a new command (like `/packit rebuild-failed`) or support chroots explicitly. In the second case, we can provide a `failed` alias you could use instead of a chroot.
