### ISSUE TITLE
Project admin cannot use `/packit copr-build`

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#543]
@StykMartin is admin on beaker-project/restraint, and Packit Service builds okay when he submits a PR (see beaker-project/restraint#13), but then ignores his `/packit copr-build` commands, like on beaker-project/restraint#7.

**Comment by TomasTomecek** [comment]
@csomh you're uber admin, p-s will always listen to you :>

how do we check for the collaborator status? since he's on multiple teams, maybe ogr doesn't check all memberships

**Comment by StykMartin** [comment]
@csomh there is `or` were you checking for explicitly whitelisted users. Therefore you can always fall to this part.

**Comment by csomh** [comment]
@StykMartin you mean [this](https://github.com/packit-service/packit-service/blob/f52d1ca6cfc6841efbd99b82059674355fb0d49d/packit_service/worker/handlers/github_handlers.py#L648) line?

@TomasTomecek when getting collaborators through the `github.Repository` object, groups are resolved into users and when users have multiple roles, the one with the broadest permissions is returned. I've check this with several Packit repositories.

**Comment by csomh** [comment]
@StykMartin please let us know here if this happens again to you.

Frankly we have no clue what this could, so we need more info.
