### ISSUE TITLE
RFE: Excluded paths

### ISSUE THREAD

**Issue by StykMartin** [packit/packit-service#545]
For people who are running monorepos it would be helpful if we can define excluded paths. Basically Packit wouldn't be running on top of PRs where changes are happening only in excluded paths.

This is what you can define with GitHub Actions.
```
on:
  pull_request:
    paths-ignore:
    - 'docs/**'
```  

You don't want to waste computation and waiting for RPMs which you don't need at all.
Later on, this may be extended even to branches.

You can find more how GitHub handles this in [GitHub Actions docs](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths)

**Comment by lachmanfrantisek** [comment]
We already groomed this issue but to be honest, there are other tasks with higher priority so it will probably take some time to do.

**Comment by TomasTomecek** [comment]
Reopening as this just popped up: Copr team needs this functionality if they ever migrate to GitHub in their main development repo (which contains ~9 SRPM packages :)
CC @praiskup

**Comment by praiskup** [comment]
Thank you, yes - 10 packages from one repo (those with automatic build configured):
https://copr.fedorainfracloud.org/coprs/g/copr/copr-dev/packages/

Some of those are built less frequently than others, so we don't want to rebuild everything with each PR.
Also, each package is built for a different set of chroots (but that's already doable now with packit.yaml, I believe).

**Comment by praiskup** [comment]
That being said ... I agree that the `paths-ignore` might be very useful, though we would rather
prefer to have `paths-include` option first (otherwise, the configuration with `paths-ignore` will be
rather big, and multiplied for each package).

**Comment by csomh** [comment]
@praiskup How is your use case different from monorepo support (packit/packit#1505)?

**Comment by praiskup** [comment]
This is not about source git at all, or?  I'm not sure I understand what you are asking, can you elaborate? :-)

**Comment by TomasTomecek** [comment]
I believe the general monorepo approach would help here a lot. Our monorepo implementation doesn't need to be exclusively used with source-git repos, right?

**Comment by csomh** [comment]
> I believe the general monorepo approach would help here a lot. Our monorepo implementation doesn't need to be exclusively used with source-git repos, right?

Exactly. This is what I meant. The monorepo [plan](https://github.com/packit/research/tree/main/source-git-monorepos) is to allow to define multiple packages in `packit.yaml` (or whatever the configuration is called in the repo), including what paths within the repository should be considered for those packages. I had the impression that the discussion above was about a similar issue.

**Comment by praiskup** [comment]
> @praiskup How is your use case different from monorepo support?

I think..? that I understand now...  It is a bit confusing to recognize that the source-git research is actually related to a normal non-source git Packit work-flows.

What we need is to somehow "limit" [the configuration](https://github.com/rpm-software-management/mock/pull/876/files) so code changes are precisely mapped to packages.  And only workflows for really "related" (changed) packages are submitted if the code is changed.

From the [plan](https://github.com/packit/research/tree/main/source-git-monorepos) we really need something like:

```
package_paths:
  - llvm/utils/lit
```

This is basically what we have implemented in Copr's webhook support:
https://pagure.io/copr/copr/blob/c273ca5cd5b1a474827bc7864ee7c8be8c3a219f/f/frontend/coprs_frontend/coprs/logic/packages_logic.py#_157-158
https://pagure.io/copr/copr/blob/c273ca5cd5b1a474827bc7864ee7c8be8c3a219f/f/frontend/coprs_frontend/coprs/logic/packages_logic.py#_176

And this is an absolute must.  From the previous Copr report related to tweaks to this, and even from what I see here in this report I think we want some form of excludes, too.  So more concrete proposal:

```
package_paths:
  - mock
  # equivalent to the above
  - include: mock
  - exclude: mock/ignored-subdir
  - include: mock/ignored-subdir/but-this-path-still-included
```

Pseudo-code:
```python
def rule_from_yaml(yaml_rule):
    if isinstance(yaml_rule, dict):
        for type in ["include", "exclude"]:
             path = yaml_rule.get(type)
             if path:
                 return {"type": type, "path": path}
        assert False  # may not happen
    return {"type": "include", "path": yaml_rule}

def is_code_change_modifying_package(change, yaml_rules):
    if not yaml_rules:
        # no rules => every code change is related
        return True
    if rule_from_yaml(rules[0])["type"] != "include":
        # if rules start with excludes, we imply everything is included by default
        rules = ["*"] + rules
    for modified_file in change.files_changed():
        included = False
        for yaml_rule in yaml_rules:
            rule = rule_from_yaml(yaml_rule)
            include_match = rule["type"] == "include"
            if include_match == included:
                # file already included/excluded
                continue
            if not fnmatch(modified_file, rule["path"]):
                # no match, no change
                continue
            included = include_match
```
