### ISSUE TITLE
"Congratulations!" comment is made two times

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#581]
@MartinBasti reached out that "Congratulations!" comments appear [two times](https://github.com/containerbuildsystem/dockerfile-parse/pull/100#issuecomment-617156863) after `/packit copr-build` commands.

And this made me remember that I've seen this when opening a PR, [last Friday](https://github.com/packit-service/packit/pull/809#issuecomment-615105018).

Related to #539.

**Comment by lachmanfrantisek** [comment]
Race condition?

**Comment by csomh** [comment]
> Race condition?

Might make sense, Fedora 32 and Rawhide builds finished first, 1 second apart:

```
2020-04-21 14:45:59 fedora-32-x86_64
2020-04-21 14:46:00 fedora-rawhide-x86_64
2020-04-21 14:46:11 fedora-31-x86_64
2020-04-21 14:46:26 fedora-30-x86_64
2020-04-21 14:46:31 epel-7-x86_64
2020-04-21 14:46:41 epel-8-x86_64
```

**Comment by TomasTomecek** [comment]
this has happened to me recently as well; we should have a DB field for this so we can avoid the race

**Comment by MartinBasti** [comment]
in this case, it commented only once: https://github.com/containerbuildsystem/koji-containerbuild/pull/182

**Comment by lachmanfrantisek** [comment]
We have a plan to turn-off the comments. We will probably don't need to fix it.

Let's keep this open until #539 is not fixed.

**Comment by MartinBasti** [comment]
Still happening

**Comment by lachmanfrantisek** [comment]
We discussed this today and agreed that we will:
- [ ] add the instructions to the result page
- [ ] add a note about removal to the "Congratulations!" comment
- [ ] remove the commenting after two weeks

**Comment by lachmanfrantisek** [comment]
I've updated the other issue (#539) and will close this one in favour of it. Let us know if you don't like our idea and plan for removal.
