### ISSUE TITLE
Failed to download file from URL – Wrong version number in URL

### ISSUE THREAD

**Issue by tantale** [packit/packit-service#625]
Issue related to https://github.com/tantale/deprecated/issues/27

On "Propose update", PackIt use a wrong URL: https://files.pythonhosted.org/packages/source/D/Deprecated/Deprecated-v1.2.10.tar.gz

The right version number should be "1.2.10" without "v", not "v1.2.10".

At the time of the release, the spec file was:

```
%global srcname Deprecated
%global pkgname deprecated

Name:           python-%{pkgname}
Version:        1.2.10
Release:        2%{?dist}
Summary:        Python decorator to deprecate old python classes, functions or methods
License:        MIT
URL:            https://github.com/tantale/%{pkgname}
Source0:        https://files.pythonhosted.org/packages/source/D/%{srcname}/%{srcname}-%{version}.tar.gz
BuildArch:      noarch
[...]
```

The `Source0` URL pattern seems good.

How can I fix that?

**Comment by lachmanfrantisek** [comment]
Sorry for the late response.

Please, try adding `upstream_tag_template` (https://packit.dev/docs/configuration/#upstream_tag_template) to the config file.

> (string) Packit by default expects git tags to match versions (e.g. when doing the propose-update command) - if you are using a different tagging scheme, let’s say v1.2.3 you can then set this parameter to v{version} and packit will fill in the version argument.

**Comment by tantale** [comment]
Thank you. Change is committed, see: https://github.com/tantale/deprecated/blob/master/.packit.yml

Then I added a new comment with `/packit propose-update`: https://github.com/tantale/deprecated/issues/27#issuecomment-636321108

But I don't know if it is OK. Can you clarify: “You can re-trigger the update by adding /packit propose-update to the issue comment”. because I don't really understand what to do at this point.

**Comment by lachmanfrantisek** [comment]
OK, this is tricky.

We are using config-file from the git-tag for the release => you need to create a new release to retrigger the workflow with the correct config file.

Or, you can use our CLI (`packit` package`) with the `--local-content` option (allows local changes to the config) to make it manually. (It will use your authentication.)

---

@packit-service/the-packit-team Since it's not the first time someone needs to change the config for the already-existing release, what about being able to specify `git-ref` for the config.

Something like this:

```
/packit propose-update master
```

**Comment by lachmanfrantisek** [comment]
I hope the original issue was solved by adding `upstream_tag_template`. (We also fixed a few problems with this few weeks ago.)

So the missing part is being able to rerun propose-downstream from a different ref. I am a bit worried that it's not worth spending a non-trivial time on this.

I am closing this issue but let us know if you still have some problems.
