### ISSUE TITLE
[testing-farm] Select packages to be installed from the copr repo

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#642]
AC:
- [ ] Get the info about packages that were built.
- [ ] Send the list of packages with the testing-farm payload.
- [ ] Since we may use this info in service's API in dashboard (and maybe even in other places), we may need to store this in the DB

**Comment by TomasTomecek** [comment]
Sounds good, is this also aligned with the new API and how tmt works?

**Comment by lachmanfrantisek** [comment]
> Sounds good, is this also aligned with the new API and how tmt works?

- See [Miro's comment](https://github.com/packit-service/packit-service/issues/628#issuecomment-635854313) for the context.
- Yes, it will be in the new API.
- Miro wants to fix that also in the cruncher. (Old API.)
- Regarding the TMT in the new API, we can use STI, TMT or command(s) for running tests.
- You can see the API structure [here](https://testing-farm.gitlab.io/api/#/paths/~1requests/post).
   - Specifically, we are speaking about `environments` -> `artifacts` -> `packages`. ([relevant code](https://gitlab.com/testing-farm/api/-/blob/master/testing-farm.yaml#L326))

**Comment by thrix** [comment]
@lachmanfrantisek until the new api is available, can you expose that information also in the current API, so I can pick it up in cruncher pls? List of RPMs which I should install is fine.

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek until the new api is available, can you expose that information also in the current API, so I can pick it up in cruncher pls? List of RPMs which I should install is fine.

I'll try to look at it next week.

**Comment by lachmanfrantisek** [comment]
I've created [an issue](https://pagure.io/copr/copr/issue/1411) in copr-repo since I could not find that info in the API/client trying both v2 and v3.

**Comment by lachmanfrantisek** [comment]
The issue on the Copr side should be solved -- now it's our turn.

**Comment by thrix** [comment]
@lachmanfrantisek oh cool! let me know if that is available via API, so I can try to consume it with cruncher

**Comment by lbarcziova** [comment]
[The issue](https://pagure.io/copr/copr/issue/1411) in copr-repo was reopened since the functionality we need was not provided.

**Comment by lachmanfrantisek** [comment]
We are still blocked..;(

**Comment by TomasTomecek** [comment]
The issue is still open.

**Comment by TomasTomecek** [comment]
is the information we need available in copr API already?

**Comment by lachmanfrantisek** [comment]
The Copr folks are currently working on it :tada: , we can start working on this soon.

**Comment by TomasTomecek** [comment]
I can confirm that a list of built packages is now available via copr api:
```python
In [4]: response = client.build_chroot_proxy.get_built_packages(2315944, "fedora-rawhide-x86_64")                                                                                             
                                                                                                                         
In [7]: pprint.pprint(response)                                                                
{'__proxy__': <copr.v3.proxies.build_chroot.BuildChrootProxy object at 0x7f96e5514730>,
 '__response__': <Response [200]>,                                                             
 'packages': [{'arch': 'noarch',            
               'epoch': 0,                                                                     
               'name': 'python3-ogr',                                                          
               'release': '1.20210707103104019498.pr611.10.gd39fa2d.fc35',
               'version': '0.26.1.dev10+gd39fa2d'},
```
