### ISSUE TITLE
Copr project improvements

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#645]
Since we [now](https://github.com/packit-service/packit-service/issues/239#issuecomment-636915157) supports builds for branches, we might want to improve some copr project settings.

- [ ] You can specify custom project name.
  - If you don't set `owner`, packit will create that project for you in our namespace. Can this be a problem? (They can pick any name.) (#990)
- [x] The projects are created as `temporary` and are removed in `60` days. 
  - Are those projects remove `60` days after creation or after the most recent build?
  - Don't we want to have `temporary` projects only for PRs?
  - Or, be able to overwrite that behaviour in the config?
- [x] he projects are created with `unlisted_on_hp=True`:
  - Do we want to use that for branches as well?
  - Or, same as above, some configuration for that?
- [ ] Since those projects will be long-term, people might want to edit also other things like description, instructions,..
  - Use custom user+project in that case?

**Comment by TomasTomecek** [comment]
>       * If you don't set `owner`, packit will create that project for you in our namespace. Can this be a problem? (They can pick any name.)

This is definitely a security problem and we should address it. Is it possible for multiple projects to configure the same copr repo and basically start jamming builds into it?

>     * The projects are created as `temporary` and are removed in `60` days.
>       
>       * Are those projects remove `60` days after creation or after the most recent build?
>       * Don't we want to have `temporary` projects only for PRs?

Sounds reasonable to me.

>       * Or, be able to overwrite that behaviour in the config?

Depends on the first question.

If people use this feature to provide latest builds of their project, then:
* not temporary
* be able to configure repo name

For CI reasons, do what we do with PRs.

>     * The projects are created with `unlisted_on_hp=True`:
>       
>       * Do we want to use that for branches as well?
>       * Or, same as above, some configuration for that?
> 
>     * Since those projects will be long-term, people might want to edit also other things like description, instructions,..
>       
>       * Use custom user+project in that case?

Yup, sounds like the best solution to me.

Do we wanna talk about this on arch?

**Comment by jpopelka** [comment]
>     * Are those projects remove `60` days after creation or after the most recent build?

For example [this build](https://copr.fedorainfracloud.org/coprs/packit/packit-service-packit-836/build/1421503) was done today and the project says: _'will be deleted after 49 days'_

**Comment by lachmanfrantisek** [comment]
> This is definitely a security problem and we should address it. Is it possible for multiple projects to configure the same copr repo and basically start jamming builds into it?

Yes. It works now:
- https://github.com/packit-service/hello-world/commits/the-build-branch
- https://copr.fedorainfracloud.org/coprs/packit/the-build-branch-test/

But that's also a good "feature"..;)

- Do we want to require project existence if user redefines this?
  - Does not solve the security problem.
- Require configuring both?
  - Neither this one solves the security problem.
- Require both but don't allow `packit` as owner.
  - Solves the problem for projects owned by packit, but users can reuse foreign custom copr repo.
- Only one upstream for one copr repo.
  - Someone may want to use one copr-repo for multiple packages. (E.g. have `packit` and `ogr` in one.)
  - We can add others manually. => Is it scalable?
  - The project with access can configure other allow projects. (Not so clean solution.)

> Do we wanna talk about this on arch?

:+1:

**Comment by lachmanfrantisek** [comment]
I will probably create new more-specific issues for the missing parts.

**Comment by lachmanfrantisek** [comment]
Only two tasks of four are missing:

* For the first one, there is a new issue: #990
* For the last one, we can wait until it's requested. (We can work on the issues that were requested by our users instead.)
