### ISSUE TITLE
Split `service.events` into forge-specific sub-modules

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#672]
Classes in `service.events` have a repetitive naming (`*GitlabEvent`, `*GithubEvent`). This might be a good indication to split the module into multiple, forge-specific sub-modules, for example: `service.events.github` and `service.events.gitlab`.

This was discussed many times (for example #671).

**Comment by lachmanfrantisek** [comment]
We need to find some time for refactoring.

**Comment by lachmanfrantisek** [comment]
I am reopening, this is really easy to do and would improve the code.
