### ISSUE TITLE
test_get_merged_chroots() sometimes fails randomly

### ISSUE THREAD

**Issue by IceWreck** [packit/packit-service#695]
In #683 @lachmanfrantisek said that this was failing locally when he tried it but worked in CI

```
 def test_get_merged_chroots(clean_before_and_after, too_many_copr_builds):
        # fetch 10 merged groups of builds
        builds_list = list(CoprBuildModel.get_merged_chroots(10, 20))
        assert len(builds_list) == 10
        # two merged chroots so two statuses
        assert len(builds_list[0].status) == 2
        assert len(builds_list[0].target) == 2
        assert builds_list[1].status[0][0] == "success"
>       assert builds_list[2].target[0][0] == "fedora-42-x86_64"
E       AssertionError: assert 'fedora-43-x86_64' == 'fedora-42-x86_64'

```
@shreyaspapi told me he tried it again and again and it was working but it failed randomly on the 17th try

I've noticed this behaviour too. The actual get_merged_chroots function seems to be working as intended but and the test works for the most part but fails seemingly randomly sometimes

The test itself seems okay but there may be an issue with the _too_many_copr_builds_ fixture
Instead of yield (or return)  CoprBuildModel.get_or_create(parms) Ive executed it directly.

Could this be the cause of the randomness?

**Comment by lachmanfrantisek** [comment]
> Could this be the cause of the randomness?

Good point. The fixtures execution order can differ in that case.
