### ISSUE TITLE
Run jobs for a PR if the sender of the event can trigger Packit

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#697]
Currently when deciding if the jobs for a PR should be run, we check the permissions for the person who opened the PR. But in some cases multiple people might collaborate on a PR, so a PR might be opened by someone who is not allowed to trigger Packit, but then some other collaborator might jump in and update the same PR.

In these cases it would make sense to check who updated the PR when figuring out permissions.

This seems to be possible by looking at `sender` in the [webhook payload](https://developer.github.com/webhooks/event-payloads/#webhook-payload-object-30).

**Comment by csomh** [comment]
still needed

**Comment by lachmanfrantisek** [comment]
@mfocko isn't this already covered by the change you've implemented?

By now, we always allow builds for the author of the PR without a need to be in the allowlist (e.g. external contributor). (The project has to be in the allowlist.) And if someone is able to push to that PR branch, the build is triggered. So, we don't explicitly check this but the result is the same I think.

**Comment by mfocko** [comment]
appears to be:
```
approved namespace AND (write permissions OR author)
```
