### ISSUE TITLE
create bodhi update for successful Koji build

### ISSUE THREAD

**Issue by msehnout** [packit/packit-service#74]
The documentation says, that packit can build RPM in koji and propose updates in bodhi. Can packit-as-a-service do this automatically for us?
https://packit.dev/docs/cli/create-bodhi-update/

My idea is like this:

- I push a new tag
- New release on github is created
- koji build is triggered
- if successful, bodhi update is proposed

WDYT?

**Comment by msehnout** [comment]
wontfix? If anything I would prefer postpone :)

**Comment by jpopelka** [comment]
> wontfix?

renamed to `stale` and added `pinned` so that stale bot doesn't bother you in future

**Comment by dhodovsk** [comment]
We plan to implement it in the future, however it is not a priority for us in the next weeks.

Somewhere in the process, there will have to be propose-update to include the changes from github release.

**Comment by lachmanfrantisek** [comment]
TODO:

* [ ] create a new job type for updates
* [ ] create a new handler that will listen to the successful Koji build
    * get the correct state of the dist-git
    * trigger the bodhi update using the Packit's Python API
