### ISSUE TITLE
Gitlab commit status cannot transition via "enqueue"

### ISSUE THREAD

**Issue by shreyaspapi** [packit/packit-service#741]
This is a known issue of while working on GitLab API - [issue](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/25807)
```
[2020-07-16 07:01:59,138: ERROR/ForkPoolWorker-1] Task TaskName.pr_comment_copr_build[8e2e7cd3-9757-4637-b0bd-c97f12d56ad2] raised unexpected: GitlabCreateError('Cannot transition status via :enqueue from :pending (Reason(s): Status cannot transition via "enqueue")')
worker              | Traceback (most recent call last):
worker              |   File "/usr/lib/python3.7/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
worker              |     return f(*args, **kwargs)
worker              |   File "/usr/lib/python3.7/site-packages/gitlab/mixins.py", line 204, in create
worker              |     **kwargs)
worker              |   File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 604, in http_post
worker              |     post_data=post_data, files=files, **kwargs)
worker              |   File "/usr/lib/python3.7/site-packages/gitlab/__init__.py", line 510, in http_request
worker              |     response_body=result.content)
worker              | gitlab.exceptions.GitlabHttpError: 400: Cannot transition status via :enqueue from :pending (Reason(s): Status cannot transition via "enqueue")
```

We can easily catch specific GitlabExceptionAPI and ignore the error while reporting the commit status, which would solve it (But rather it's like a workaround solution). Another way would be to check the current commit status and act accordingly (Would take a lot of time to get the current commit status.).

**Comment by TomasTomecek** [comment]
could you please clarify what the exact problem is? shall we bypass enqueue then?

**Comment by shreyaspapi** [comment]
@TomasTomecek Sorry if this was not clear.

The exact issue is in Gitlab where we cannot overwrite the status of a pending build -> pending build again. We can bypass the enqueue but ignoring the error [here](https://github.com/packit-service/packit-service/pull/740/files#diff-07d9119e7f750e40e651ae3072ea0979R99-R108) should also work fine.

**Comment by TomasTomecek** [comment]
anything else we can do here?

**Comment by shreyaspapi** [comment]
@TomasTomecek Yes, we can have unique status for each step of the workflow? e.g. packit-service/copr-build-srpm, packit-service/copr-build-fedora-31-rpm. I will make a pr for this.

**Comment by lachmanfrantisek** [comment]
We need to solve this if we want to support GitLab properly.

**Comment by lachmanfrantisek** [comment]
The current state looks good to me. Let's close this issue and create a new one (more specific) if needed.

![Screenshot from 2021-01-25 14-40-06](https://user-images.githubusercontent.com/20214043/105713287-3dc4de80-5f1b-11eb-8000-c51680cc7ed0.png)
![Screenshot from 2021-01-25 14-39-59](https://user-images.githubusercontent.com/20214043/105713291-3ef60b80-5f1b-11eb-9337-6bd21abf47b9.png)

**Comment by mfocko** [comment]
Related to #1821
