### ISSUE TITLE
/packit propose-update failing with kinit issue

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#743]
`/packit propose-update` is currently failing on prod with a somewhat not informative `Failed to init kerberos ticket:`.

Credentials seem to be okay and available, so no clue what's going on here.

**Comment by csomh** [comment]
@TomasTomecek started looking into this with packit-service/packit#906

**Comment by TomasTomecek** [comment]
an example error I am getting for klist:
```
bash-5.0# klist                                                                                                                                                              
klist: Invalid UID in persistent keyring name while resolving ccache 
```

**Comment by csomh** [comment]
Wondering if this is still valid...

**Comment by lachmanfrantisek** [comment]
I think it's not relevant for prod now.

**Comment by lachmanfrantisek** [comment]
Closing since we have new downstream PRs created until then.
