### ISSUE TITLE
Fix the workaround in `IssueCommentEvent.commit_sha`

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#744]
```python
    @property
        if not self._tag_name:
            releases = self.project.get_releases()
            self._tag_name = releases[0].git_tag.commit_sha if releases else ""
        return self._tag_name
```

Or some optimisation to not need to search for releases twice.

_Originally posted by @lachmanfrantisek in https://github.com/packit-service/packit-service/pull/736#discussion_r455706081_

**Comment by lachmanfrantisek** [comment]
Looks like an easy, good first issue.
