### ISSUE TITLE
Test results get blocked in "Submitting the tests ..." state

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#752]
Happened on https://github.com/psss/tmt/pull/314, 3 out of 4 of the testing flags were not set with any result, they were showing "Pending — Build succeeded. Submitting the tests ...".

The Dashboard showed the one test that passed for this PR, but no other test was visible.

Logs did not have a trace of handling this PR at the time of checking.

**Comment by csomh** [comment]
None of the missing 3 test runs had a record in the `tft_test_runs` table for the relevant `job_trigger_id` (5305).

**Comment by psss** [comment]
I've rescheduled psss/tmt/pull/314 and all jobs seem to be stuck in `Submitting tests...`

**Comment by csomh** [comment]
All tests finished successfully after resubmitting them today. :man_shrugging: :confused:

**Comment by TomasTomecek** [comment]
so we good here?

**Comment by csomh** [comment]
I think yes, we are good with this particular occurrence, though I have some concerns that this might happen in the future.

The issue here was that the thing Packit communicated (the status set on the flags) was out of sync whit what it did (triggering the test) and what it remembered that it did (the thing saved in the DB).

Reading through [the relevant code path](https://github.com/packit-service/packit-service/blob/8f0c479ee43300cc471cce8dd15ed3244a7155af/packit_service/worker/testing_farm.py#L120) the order right now is:

1. Tell the user that [the tests are being submitted](https://github.com/packit-service/packit-service/blob/8f0c479ee43300cc471cce8dd15ed3244a7155af/packit_service/worker/testing_farm.py#L139).
2. ["Remember"](https://github.com/packit-service/packit-service/blob/8f0c479ee43300cc471cce8dd15ed3244a7155af/packit_service/worker/testing_farm.py#L148) that the tests are submitted.
3. Actually [submit the tests](https://github.com/packit-service/packit-service/blob/8f0c479ee43300cc471cce8dd15ed3244a7155af/packit_service/worker/testing_farm.py#L161).

Each of the above is a separate action and each of these actions reaches to some other system/application: GitHub API, PostgreSQL DB, Testing Farm API.

At the end of these steps we should end up with a consistent state: we told the user that we submitted the tests, we actually submitted the tests and we remembered that we submitted the tests.

But b/c each of these steps depends on some external system, the sequence is fragile. (But that's fine.) If any of the steps fail, we and up in an inconsistent state: we told the user that we submit the tests but we didn't do it and/or we don't remember that we did it (so there is no way for us to notice and recover from the inconsistent state).

I think this could be improved by changing the order of the flow above to:

1. Submit the test.
2. Take a note ("remember") that the test was submitted.
3. Notify the user that the test was submitted.

The above would ensure that users get notified about actions which really took place and are accounted for by the service.

WDYT?

If it makes sense, I would create a new issue to check all over the service that actions are done in the order above, and close this one.

**Comment by psss** [comment]
I'd say the wording `Submitting the tests...` describes that something is in progress (has started) rather than it's done (has finished). So I guess the wording should be updated as well.

**Comment by lachmanfrantisek** [comment]
@psss  you are right, the ellipsis mean that the submission will be done.

- We are not saying that anything was done.
- We should be consistent here since we have multiple occurrences of this: `Building ... ` / `Submitting ...`  (as Hunor pointed out)
- Or what about two states? `Submitting ...` and `Submitted` to make it clear?

**Comment by csomh** [comment]
@lachmanfrantisek Should we keep this open? What do you think? If it's not a must to have an improvement in this area, I'd say to close it, as the initial issue was solved.

**Comment by lachmanfrantisek** [comment]
@csomh looks like we don't have much capacity for it. I am not against closing. Any other opinion? Or any volunteer to go through the commit state messages?

**Comment by csomh** [comment]
Let's close it then. Thanks!
