### ISSUE TITLE
Merge Makefile targets worker and worker-prod

### ISSUE THREAD

**Issue by sakalosj** [packit/packit-service#759]
@csomh  raised a question:

https://github.com/packit-service/packit-service/pull/756#discussion_r462090502

I think it is a good idea because it will make worker target capable of dynamically decide to which tag should be used, but not sure if it will fit in current architecture.

**Comment by csomh** [comment]
Now that I think about it... the `worker-prod*` targets are good for convenience. Could be removed, but I see no considerable benefit in doing so. Let's close this!
