### ISSUE TITLE
Make check runs conclusion "neutral" for permission problems

### ISSUE THREAD

**Issue by StykMartin** [packit/packit-service#760]
## Current state
Check runs for all chroots are marked as "failed" when the user is not part of organization.

## Proposed state
Check runs for all chroots are marked as "neutral" therefore it will not mark the whole PR as "failed".

I expect that some users would like to see "failed" so they don't forget to run CI. So I suggest making this part of `packit` configuration per project.

For example, LGTM is using neutral conclusion.
![image](https://user-images.githubusercontent.com/188918/88800075-d9ada180-d1a7-11ea-8f66-d29f5ae479fd.png)              ![image](https://user-images.githubusercontent.com/188918/88800091-e0d4af80-d1a7-11ea-8293-c6cc5771fbf9.png)

Added by @lachmanfrantisek:

The use-case above is not relevant anymore since we've changed the permission workflow but let's use `neutral` status for all the permission problems.

- [x] implement the support for check runs in OGR (packit/ogr#592)
- [x] ask for the `Check-runs` permission for the Github apps.
- [ ] find all the places where we check the permissions and use check runs with a neutral state there.

**Comment by TomasTomecek** [comment]
+1, good suggestion and should be trivial to implement on our side

anyone wants to picks this up on Friday?

**Comment by lachmanfrantisek** [comment]
The API endpoint we are using for setting commit status [does not provide](https://docs.github.com/en/rest/reference/repos#statuses) `neutral` state, only `error`, `failure`, `pending`, or `success`.


We will need to switch to [checks API](https://docs.github.com/en/rest/reference/checks) to be able to use it.

**Comment by StykMartin** [comment]
👀

**Comment by TomasTomecek** [comment]
Given the fact we are not using the checks API and commit statuses do not support the neutral status, I believe we can close this.

**Comment by lachmanfrantisek** [comment]
But if we use check API in OGR, we can. (And it should be already implemented in the pygithub.) Not a high-prio, but I would still like to see it.

**Comment by mfocko** [comment]
Does it still matter? We require just the namespace to be allowed now.

**Comment by lachmanfrantisek** [comment]
But we still sometimes want to have some neutral state (e.g. warning during testing-farm problems).

**Comment by lachmanfrantisek** [comment]
I'll change the title and add some TODO to the description to cover all the permission errors because this specific permission problem can't occur nowadays.

**Comment by lachmanfrantisek** [comment]
Ping the sync to Jira!

**Comment by lachmanfrantisek** [comment]
Ping the sync to Jira!

**Comment by lbarcziova** [comment]
Implemented in #1167

**Comment by StykMartin** [comment]
🥳 Thank you @lbarcziova !
