### ISSUE TITLE
Give feedback if Packit command is in comment, but Packit is not configured

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#765]
See [this PR](https://github.com/avocado-framework/avocado-vt/pull/2597) as an example: `/packit copr-build` was triggered, but there is no Packit configuration in the repository (though the application seems to be enabled on the namespace).

In these cases Packit should comment telling users the configuration is missing and pointing them to the relevant documentation on how to do the configuration.

**Comment by lachmanfrantisek** [comment]
That can be a really good UX improvement.

**Comment by lachmanfrantisek** [comment]
I think it's worth spending some time on this.

**Comment by lachmanfrantisek** [comment]
Part of #1158
