### ISSUE TITLE
How do I install dependency necessary for creating the archive?

### ISSUE THREAD

**Issue by pvalena** [packit/packit-service#771]
`sudo dnf install gem`

https://stg.packit.dev/srpm-build/873/logs

**Comment by TomasTomecek** [comment]
Short answer: you can't

Long answer: we are running all commands, defined by you, in a sandbox (new openshift pod) which is locked-down. At the moment we don't have any mechanism for you to define the dependencies you need and us making them available for you.

In the mean time we are solving these requests one by one and installing the dependencies ad-hoc.

**Comment by TomasTomecek** [comment]
`gem` command should be available in sandbox in an ~hour after the image gets build and imported in our cluster

**Comment by pvalena** [comment]
Thanks a lot that'll help!

It also solves (be wary) the issue with any other (future) dependencies for me, as all can installed using `gem install ...`.

FYI: I'm running staging instance.

**Comment by TomasTomecek** [comment]
we have gem available now, closing

thank you for reaching out!
