### ISSUE TITLE
The spec file is not looked for recursively.

### ISSUE THREAD

**Issue by pvalena** [packit/packit-service#774]
https://github.com/pvalena/abrt-ruby/pull/8#issuecomment-672111803

**Comment by TomasTomecek** [comment]
We're not doing this recursively locally:
https://github.com/packit/packit/blob/master/packit/config/package_config.py#L346

Thought I'm not sure about this one https://github.com/packit/packit/blob/master/packit/config/package_config.py#L369

@lbarcziova could you clarify please?

**Comment by lbarcziova** [comment]
>Thought I'm not sure about this one https://github.com/packit/packit/blob/master/packit/config/package_config.py#L369

Looks like `get_files()` method from ogr which we use gets files only from the top-level dir [by default](https://github.com/packit/ogr/blob/fbdd87b7fdd4cc2be5fadee3a51e697025f525b1/ogr/services/github/project.py#L451).

And locally it is searched [recursively](https://github.com/packit/packit/blob/9e55e2c18ffd632935ff969bc0d7d4c1522eb053/packit/config/package_config.py#L349).

**Comment by pvalena** [comment]
FYI your FAQ (or docs, not sure atm) says it works recursively ;).

**Comment by lachmanfrantisek** [comment]
> Looks like `get_files()` method from ogr which we use gets files only from the top-level dir [by default](https://github.com/packit/ogr/blob/fbdd87b7fdd4cc2be5fadee3a51e697025f525b1/ogr/services/github/project.py#L451).

Can we switch to `recursive=True` then to match local behaviour and docs?
