### ISSUE TITLE
copr branch builds: no interface to tell user that something is wrong

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#780]
I just set up branch builds for my project: the builds was marked as failing and there was no way for me to see what's wrong - I literally had to check logs in the pod. (I had to approve packit user as admin for my project, which I didn't receive any notification from copr)

There should be a way to tell user that something is wrong.

---
AC:
- [ ] create a commit comment for non-pr commenting (we do nothing now)

**Comment by lachmanfrantisek** [comment]
> There should be a way to tell user that something is wrong.

We use issues in other cases. Would be nice to support retriggering as well.

**Comment by lachmanfrantisek** [comment]
btw, have you seen the status on commit page?

![Screenshot from 2020-08-21 08-36-53](https://user-images.githubusercontent.com/20214043/90860034-951dbc00-e389-11ea-8285-4d363d552709.png)

**Comment by lachmanfrantisek** [comment]
@TomasTomecek As you can see in the previous screenshot, there is an interface for showing status/logs.

There is no space for more details (what we put to the comments in PRs), no notification and no way to retrigger.

Can we change this issue to this:

- [ ] create an issue in case of an error
  - Issue has a consistent name (e.g. `[packit] build for branch master failed`) and can be reused/reopened.
- [ ] putting a `/packit build` comment will retrigger the build (same for tests)

**Comment by TomasTomecek** [comment]
>     * [ ]  create an issue in case of an error
>       
>       * Issue has a consistent name (e.g. `[packit] build for branch master failed`) and can be reused/reopened.
> 
>     * [ ]  putting a `/packit build` comment will retrigger the build (same for tests)

that would be nice

**Comment by lachmanfrantisek** [comment]
OK, I've updated the AC after our discussion to create a commit comment and will move my proposal (long term solution) to a new issue since it's a bit different.
