### ISSUE TITLE
copr: request build perms for custom project automatically

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#781]
...so we don't have to do it manually, which is pretty tedious

**Comment by lachmanfrantisek** [comment]
Implemented and merged a few hours ago in #776

**Comment by lachmanfrantisek** [comment]
The docs part was updated here:
https://github.com/packit/packit.dev/pull/154

**Comment by TomasTomecek** [comment]
but still not in prod, hence my confusion

**Comment by lachmanfrantisek** [comment]
> but still not in prod, hence my confusion

Looks like they have multiple error messages for that...  https://github.com/packit/packit-service/pull/783
