### ISSUE TITLE
/packit propose-update files duplicate PRs

### ISSUE THREAD

**Issue by ueno** [packit/packit-service#785]
After triggering propose-update via issue comment, packit-service filed 3 PRs for master, f32, and f31, as expected:
https://github.com/p11-glue/p11-kit/issues/314

At the same time(?) it also submitted 3 more PRs with empty content:
https://src.fedoraproject.org/rpms/p11-kit/pull-request/2
https://src.fedoraproject.org/rpms/p11-kit/pull-request/4
https://src.fedoraproject.org/rpms/p11-kit/pull-request/6

As we use a bit special [packit configuration](https://github.com/p11-glue/p11-kit/blob/master/.packit.yaml) to fetch the upstream release tarball along with GPG signature, I suspect that those are triggered by "trigger: release".

**Comment by TomasTomecek** [comment]
You're the first who had the chance to try https://github.com/packit/packit-service/pull/761 in action. That p-s PR is retrying to perform the downstream update multiple times - that's because the release archive is usually not available when the git tags are pushed upstream (a.k.a github release is created).

I assume what happened here is that one set of PRs was created by 'trigger: release' (as you point out) and the other one using the comment.

I'm wondering how can we improve the experience so this would not happen in future for others.

(maybe track the fact that p-s is still trying and `/packit propose-update` would be noop and packit would respond with a comment that update is in progress)

**Comment by ueno** [comment]
> (maybe track the fact that p-s is still trying and /packit propose-update would be noop and packit would respond with a comment that update is in progress)

I personally hope the other way around, i.e., 'trigger' can be optional/ignored in the configuration, as it would nevertheless fail in our use-case (because of missing GPG signature).

**Comment by TomasTomecek** [comment]
Interesting, we would probably then need the data where packit-service should propose the update - I guess it could default to `fedora-all` but you should be able to change this with the comment posted to an issue.

**Comment by lachmanfrantisek** [comment]
> I personally hope the other way around, i.e., 'trigger' can be optional/ignored in the configuration, as it would nevertheless fail in our use-case (because of missing GPG signature).

So some `ignore_trigger: true` or `manual_trigger: true` option in the config and react only on comments.

Will this solve this?

@TomasTomecek do we want to have some process check as well as you described? Can we have a new issue for that?

**Comment by TomasTomecek** [comment]
@lachmanfrantisek having additional options in config to handle this sounds too complicated too me

the use case is pretty clear: when you make an upstream release, p-s should propose that new release in dist-git: yes, all of this is really complicated and I'd like to hide all the complexity in p-s' codebase, ideally with the current configuration we have

I'd still suggest what I proposed originally: if update is in progress and you type `/packit propose-update`, p-s should respond that the update is in progress and will be tried for X times for the next Y minutes.

> @TomasTomecek do we want to have some process check as well as you described? Can we have a new issue for that?

I'd like this issue to cover it.

WDYT?

**Comment by lachmanfrantisek** [comment]
OK, so:

- We don't want to support scenario where people can trigger packit-service only via comments and don't react automatically. (They can use packit CLI for that usecase.)
- Comment for `/packit propose-update` when the update is in progress as you wrote.
  - What about source-not-found retrigger -- do we count that as a progress?

**Comment by TomasTomecek** [comment]
>     * We don't want to support scenario where people can trigger packit-service only via comments and don't react automatically. (They can use packit CLI for that usecase.)

+1, exactly

>     * Comment for `/packit propose-update` when the update is in progress as you wrote.
>       
>       * What about source-not-found retrigger -- do we count that as a progress?

yup, that's what I had in mind

WDYT?

**Comment by lachmanfrantisek** [comment]
Can we close this since the problem of creating multiple PRs was fixed in https://github.com/packit/packit/pull/994?

This missing part is about response for triggering of the already running job. Do we want to solve it here or create a separate issue?

**Comment by lbarcziova** [comment]
I am for closing this and creating a separate issue for that.
