### ISSUE TITLE
Packit Service stores duplicate projects

### ISSUE THREAD

**Issue by IceWreck** [packit/packit-service#797]
I've noticed this before (last month) as well and I thought it was a one off. But its happening again. Eg: stg has two entries for TomasTomecek/anaconda

One of them is okay but the other one stores the project url as https://github.com/TomasTomecek/TomasTomecek/anaconda (namespace is repeated) instead of https://github.com/TomasTomecek/anaconda

The other details like namespace, repo name, forge are correctly stored. Since `/projects/{forge}/{namespace}/{repo_name}/... ` expects these to be unique, it returns the first one it finds. It might be the correct one in some cases and incorrect one in others.

![image](https://user-images.githubusercontent.com/18102790/92351598-befd0f80-f0f9-11ea-970f-de089f04fac7.png)
![image](https://user-images.githubusercontent.com/18102790/92351610-c7554a80-f0f9-11ea-9a42-e77e83c4fa5c.png)

**Comment by lachmanfrantisek** [comment]
Thanks for finding that!

Is the problem only on stage?

**Comment by IceWreck** [comment]
No, I searched and found some on a two month old prod dump as well

![image](https://user-images.githubusercontent.com/18102790/92357819-1d2fef80-f106-11ea-8f2b-662d80042b7a.png)

**Comment by lachmanfrantisek** [comment]
We should go through that. It contains also some weird names.

**Comment by lachmanfrantisek** [comment]
Let's take a look after #954 is merged.

**Comment by lachmanfrantisek** [comment]
I think we can clear the content from some mess both on prod and stage. And it shouldn't take much time. Let's reopen.

**Comment by mfocko** [comment]
sync 2 jira?
