### ISSUE TITLE
Implement new testing-farm API

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#802]
The old testing-farm API does not work now because of the [cluster problems](https://pagure.io/centos-infra/issue/85) which can't be solved easily. Moving old API to the new cluster is not easy as well (will need some coding to make it work). We should implement the new API ASAP.

- API endpoint and documentation: https://testing-farm.gitlab.io/api
- Submitting of the test runs is done here:
https://github.com/packit/packit-service/blob/7db1556b83db89c6a9dd480c226bf1b20356be30/packit_service/worker/testing_farm.py#L120-L216
- The payload is created here:
https://github.com/packit/packit-service/blob/7db1556b83db89c6a9dd480c226bf1b20356be30/packit_service/worker/testing_farm.py#L71-L94
- Packit API endpoint for testing-farm results:
https://github.com/packit/packit-service/blob/7db1556b83db89c6a9dd480c226bf1b20356be30/packit_service/service/api/testing_farm.py#L90-L91
- API models:
https://github.com/packit/packit-service/blob/7db1556b83db89c6a9dd480c226bf1b20356be30/packit_service/service/api/testing_farm.py#L46-L87
- Processing of the received results:
https://github.com/packit/packit-service/blob/7db1556b83db89c6a9dd480c226bf1b20356be30/packit_service/worker/handlers/testing_farm_handlers.py#L89-L138
- Testing-farm model in postgres:
https://github.com/packit/packit-service/blob/7db1556b83db89c6a9dd480c226bf1b20356be30/packit_service/models.py#L1076-L1086

**Comment by lachmanfrantisek** [comment]
ping @thrix

**Comment by thrix** [comment]
Thanks for all the info @lachmanfrantisek I will try to do this!

**Comment by csomh** [comment]
sync, please

**Comment by csomh** [comment]
@thrix, we pulled this work in our sprint starting today. Do you mind if I take it over and do this? :smiley:

**Comment by thrix** [comment]
@csomh no, we talked already with @TomasTomecek about it, that somebody from your team will do it. There are some significant changes to the API, which we need to talk about @csomh, would you have time today?

**Comment by jpopelka** [comment]
this is in progress, stale bot

**Comment by jpopelka** [comment]
Fixed in #875
