### ISSUE TITLE
The tests are temporarily disabled

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#803]
### :warning: Testing-farm support is disabled. We are moving to a new test runner. :warning: 

The cluster with the old testing-farm runner has died, it will never work again and we are finalizing the support for a new one.
* [x] We have prepared (#875) implementation of the new API of the testing-farm.
* [x] Miro V. has been working hard on the new API. You can expect full tmt support so be patient, please.
* [x] Jirka is finalizing our part and making sure the connection works smoothly (#875).

We are sorry about that but give us some time, please.

More information about that can be found in #802 or in packit/packit#1078.

You will now get `Testing farm is temporarily disabled.` result until the new testing-farm is ready. We set the result status to `success` to not mark your PRs as failed. The neutral state is not possible with our current procedure how we set the status (#760).

![Screenshot from 2021-01-25 09-58-13](https://user-images.githubusercontent.com/20214043/105683432-ebbc9280-5ef3-11eb-954c-10bcbb96c32c.png)

**Comment by psss** [comment]
> Miro V. is working hard on the new API but it's not ready yet. 

I guess that part has been done, right? @thrix?

**Comment by jpopelka** [comment]
Yes, I'm working on implementing it on our side.

**Comment by lachmanfrantisek** [comment]
@psss I've updated the description to be fair..;)

**Comment by psss** [comment]
Thanks for the update :)

**Comment by psss** [comment]
This seems to be already in production, right?

**Comment by jpopelka** [comment]
yes, it's been in production since this week
