### ISSUE TITLE
Retry mechanism for transient errors

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#830]
Packit Service is interacting with many other services and those services might have temporary glitches which ultimately lead to failures in Packit Service and impact our users.

In order to minimise the impact of these glitches on our users, we should implement a retry mechanism for the following errors:
- [GithubException 500](https://sentry.io/organizations/red-hat-0p/issues/1897421192/events/cb669836ca444526b51fc8fc83576dd4/) - which seems to happen when GitHub API has issues.
- [BadCredentialsException](https://sentry.io/organizations/red-hat-0p/issues/1903549983/events/33958ce425d6456da6c128f3f5149e51/) - although after introducing *tokman* (#595) this happens less often, we won't be able to completely get rid of it without retrying.

Requests failing for the above reasons should be retried 5 times, with a backoff factor of 5 seconds.

**Comment by lachmanfrantisek** [comment]
Still relevant. And hopefully fixed soon.

**Comment by lachmanfrantisek** [comment]
It's already solved by packit/ogr#537, closing. Please, reopen if we are missing some part here.
