### ISSUE TITLE
Research Quay.io

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#833]
Research and maybe also try out Quay.io in order to understand what needs to be done to start using it instead of Docker Hub to build and host all our images.

**Comment by lachmanfrantisek** [comment]
@jpopelka I think we can close this...

**Comment by jpopelka** [comment]
I just created a [repo for dis2src](https://quay.io/repository/packit/dist2src).

This issue here is about investigating Quay.io for building/hosting our packit-service images, which are a bit more difficult - I don't remember exactly, but I think `SOURCE_BRANCH` build arg is one of the things we need to be sure work on Quay.io.
@sakalosj did some initial research several months ago, but I don't remember the exact outcome.

**Comment by sakalosj** [comment]
> I just created a [repo for dis2src](https://quay.io/repository/packit/dist2src).
> 
> This issue here is about investigating Quay.io for building/hosting our [packit-service images](https://github.com/packit/packit-service/tree/master/files/docker), which are a bit more difficult - I don't remember exactly, but I think [`SOURCE_BRANCH` build arg](https://github.com/packit/packit-service/blob/master/files/docker/Dockerfile.worker#L5) is one of the things we need to be sure work on Quay.io.
> @sakalosj did some initial research several months ago, but I don't remember the exact outcome.

I don't think the `SOURCE_BRANCH`  approach will work in Quay - I don't see any hooks configuration there.
 
But if I understand correctly, currently we are using 2 different ways how to build images:
* direct DockerHub triggers - for images which OpenShift is pulling
* builds handled by ansible - for images used in tests

I think it will be good to unify it to avoid bending configs to work in both configurations. But high probably will require some "container build server".

**Comment by jpopelka** [comment]
> I think it will be good to unify it to avoid bending configs to work in both configurations.

Can you give me an example (of where we bend configs to work in both configurations)?

> Are zuul nodes able to push images to some external registry (eg. Quay?)

I can see some roles for [building](https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/build-container-image) and [uploading](https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/upload-container-image) of container images but haven't looked into them yet.

**Comment by sakalosj** [comment]
@jpopelka 
master/stable branch builds - you have to maintain Dockerhub + zuul logic

**Comment by jpopelka** [comment]
Where exactly Jan? :-)
Are we talking about `Makefile`, `Dockerfile`, `files/some.yaml` or something else?

**Comment by sakalosj** [comment]
to have Dockerhub working correctly, you need to maintain:
https://github.com/packit/packit-service/blob/master/files/docker/hooks/build

I am not aware of any alternative functionality in Quay, so if you want to migrate you will probably need to split docker files to prod/stable version at least for builds invoked directly in Quay.

**Comment by jpopelka** [comment]
Another option for building/pushing are Github Actions:
- https://www.redhat.com/en/about/press-releases/red-hat-and-github-collaborate-expand-developer-experience-red-hat-openshift-github-actions
- https://github.com/marketplace?query=redhat
- https://github.com/marketplace/actions/buildah-build
- https://github.com/marketplace/actions/push-to-registry

**Comment by sakalosj** [comment]
It looks good, but I think one CI system should be used to ensure consistency, compatibility, and keep maintenance easy. I am not against anything just prefer a unified environment.

**Comment by jpopelka** [comment]
still wanted

**Comment by jpopelka** [comment]
- https://github.com/packit/deployment/pull/182
- https://github.com/packit/packit-service/pull/1013
- https://github.com/packit/packit-service-fedmsg/pull/29
- https://github.com/packit/packit-service-centosmsg/pull/20
- https://github.com/packit/dashboard/pull/81
- https://github.com/packit/sandcastle/pull/108
- https://github.com/packit/dist-git-to-source-git/pull/186
- https://github.com/packit/packit.dev/pull/248

**Comment by lachmanfrantisek** [comment]
Thanks Jirko for all the work!
