### ISSUE TITLE
prioritize tasks when user is directly affected

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#836]
e.g. comments or pushes - that's where users want immediately see that packit-sevice picked up the event and is processing it

for others where we just react to services (srpm is done, copr build is pending, etc.) it's fine to post an update a few secs later

edit: uh, wrong repo

**Comment by lachmanfrantisek** [comment]
We still want this.

**Comment by lachmanfrantisek** [comment]
Stale bot! Why again?

(I need to check the removal of `stale` label more carefully.)

**Comment by lachmanfrantisek** [comment]
This is currently being worked on: #1059
