### ISSUE TITLE
New packit command to request copr permissions

### ISSUE THREAD

**Issue by psss** [packit/packit-service#838]
When enabling copr builds for commits from the `master` branch the first attempt always fails because Packit needs to ask Copr for permissions first. For example this pull request:

 * https://github.com/psss/python-nitrate/pull/25

It would be nice to allow an easy way to ask for the permission even before such pull request is merged. It could be something like:

    /packit copr request build permission

Or, perhaps, Packit could even detect from the pull request content that the permission will be needed and ask right away.

**Comment by lachmanfrantisek** [comment]
I am just thinking if the main problem here isn't that we can't retrigger those builds. Will that be better/ok?

**Comment by psss** [comment]
Yes, if there was an easy way to manually retrigger it would be just one additional click or comment. Works for me.

**Comment by lachmanfrantisek** [comment]
Just to make it clear, there is no retriggering for now (#780) but the implementation of those two things looks comparable in complexity to me.

**Comment by lachmanfrantisek** [comment]
I hope we will fix this by being able to retrigger the build for a branch/release as well, but we need to do some refactoring first to be able to do that. (#879 , #880 ).

**Comment by lachmanfrantisek** [comment]
We are still going through some refactorings that will allow reactions to non-PR jobs...

**Comment by lachmanfrantisek** [comment]
We need to fix the retriggering properly. I've created a new issue for that: #1062 and closing this one in favour of it.

This is not so easy to implement to work on it as a temporary solution.
