### ISSUE TITLE
[tests] HTTPSConnectionPool(host='bodhi.fedoraproject.org', port=443) [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#860]
$ rm -r tests_requre/openshift_integration/test_data/test_*
$ make check-inside-openshift PATH_TO_SECRETS=...

https://pastebin.com/6pRyc0tw

**Comment by jpopelka** [comment]
So it's something in my local deployment since I see in the worker logs:

```
+ ssh-keyscan pkgs.fedoraproject.org
getaddrinfo pkgs.fedoraproject.org: Name or service not known
```

**Comment by TomasTomecek** [comment]
yup, looks like a borked DNS (which can happen in containers easily)

the other issue with BaseExceptions is pretty nasty though
