### ISSUE TITLE
Link to SRPM file in the status page

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#862]
Requested in https://github.com/packit/packit/issues/1010 by @pcahyna 

TODO:
- [ ] Get the SRPM URL from Copr.
- [ ] Add the SRPM link to the build page (e.g. https://prod.packit.dev/copr-build/69250)

**Comment by TomasTomecek** [comment]
+1

Would it make sense to just link here? https://download.copr.fedorainfracloud.org/results/packit/packit-hello-world-107/fedora-31-x86_64/01751713-hello/

**Comment by pcahyna** [comment]
> Requested in [packit/packit#1010](https://github.com/packit/packit/issues/1010) by @pcahyna

Not entirely correct. My main problem in packit/packit#1010 was that I did not get a link to the status page at all (i suppose the citool output is not considered a status page). Of course, the link to the SRPM (maybe also to the RPM if it vcan be obtained in the same way?) would be nice to have.

**Comment by lachmanfrantisek** [comment]
> Not entirely correct.

@pcahyna I've split that to the multiple issues so sorry for the confusion:
- Show the build result by default: https://github.com/packit/packit/issues/1010
- Show the build info when only tests defined: https://github.com/packit/packit-service/issues/506
- Show the link to the SRPM from the build-result page: this issue
