### ISSUE TITLE
Build not run when test configured for trigger and build for different trigger

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#872]
Example PR: https://github.com/psss/fmf/pull/88

As @lbarcziova has proposed, we should check that we don't skip build in that case.

**Comment by lachmanfrantisek** [comment]
@psss ping

**Comment by psss** [comment]
Thanks for looking into this. Do you need any other details from me?

**Comment by lachmanfrantisek** [comment]
> Thanks for looking into this. Do you need any other details from me?

It looks clear to me. We'll let you know if there is a need for more details.
