### ISSUE TITLE
Copr build process stuck at "Pending — Starting RPM build... "

### ISSUE THREAD

**Issue by bocekm** [packit/packit-service#874]
Under https://github.com/oamg/convert2rhel/pull/122, the copr builds are not being created. The last message from packit is _"Pending — Starting RPM build... "_.
When looking at the linked copr build job (https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/build/1775484/), it says _"importing - Package sources are being imported into Copr DistGit."_

**Comment by lachmanfrantisek** [comment]
Regarding some retry mechanism, we've been discussing this a lot so I've created an upstream issue for it: #873

**Comment by TomasTomecek** [comment]
thanks for opening the issue, can we close this in favor of #873 or #830?

**Comment by bocekm** [comment]
If you're asking me, then feel free to do that :)

**Comment by lachmanfrantisek** [comment]
@TomasTomecek Yes, I think it's covered by those two.
