### ISSUE TITLE
Disable comments about successfully created Copr build

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#882]
Remove the functionality of commenting about the successfully created Copr build.

Needs to be done two weeks after #881

**Comment by lachmanfrantisek** [comment]
check sync

**Comment by TomasTomecek** [comment]
Heads up for the owner of this card:
```
notifications:
  pull_request:
    successful_build: true
```
This option is going to be no-op after deploying this. So we should make that deprecated.

**Comment by TomasTomecek** [comment]
I couldn't sleep b/c of this card - hence let's take the safer path and just change the default to not comment - people still can enable the comments if they want.

**Comment by lachmanfrantisek** [comment]
Fixed in the packit repo: https://github.com/packit/packit/pull/1057

Let's close this. Thanks @mfocko for a quick implementation.
