### ISSUE TITLE
Improve documentation for local deployments

### ISSUE THREAD

**Issue by csomh** [packit/packit-service#884]
Improve the documentation for local deployments, so that a Packit Service can be easily deployed locally by someone not familiar with the project.

For example, the current documentation is not clear about which services (GitHub, message bus, etc) a local deployment could connect to, how these connections will be configured and what secrets would be used.

The end-goal of this local deployment should be to be [used to regenerate](https://github.com/packit/packit-service/blob/master/CONTRIBUTING.md#data-regeneration) `requre` recordings.

**Comment by jpopelka** [comment]
still wanted
