### ISSUE TITLE
Downstream proposed change has strange changelog

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#890]
For example, [changelog in PR for packit-0.21.0 @ rawhide](https://src.fedoraproject.org/rpms/packit/pull-request/105#request_diff) contains list of upstream commits since previous version instead of [upstream spec changelog entry](https://github.com/packit/packit/pull/1033/commits/8b406aded6e024d98c8751abd56fad9923cfbbbf#diff-b1ede3399cc051f4d7b1ad8726131e155f6904d5c40bb5e7d4a867cc8de3a54a).

I don't remember any recent related change in packit or packit-service. Might this be a rebase-helper issue?

**Comment by lbarcziova** [comment]
This is because of [this change](https://github.com/packit/packit/pull/1004) in our code (related [docs PR](https://github.com/packit/packit.dev/pull/182)).

**Comment by TomasTomecek** [comment]
Jirko, what would you prefer more?

**Comment by jpopelka** [comment]
Ok, I'm lazy to read all the issues leading to this change so I'll consider this a fact.

But unlike [you](https://github.com/packit/packit/pull/1004#pullrequestreview-523256219) I'd rather see a nice description with markdown then a huge list of commit messages, i.e I'm proposing to use `copy_upstream_release_description=true` in our config(s). So in this particular case we'd (as I understand it) have

```
* Wed Nov 25 2020 Packit Service <user-cont-team+packit-service@redhat.com> - 0.21.0-1
- If the first `Source` tag in a spec file is not indexed, it is always returned,
  no matter the value of `source_name`.
- Sanitize potentially problematic characters in a branch name
  before creating a copr project name from it.
- Default job now includes copr build as well.
```

instead of

```
* Wed Nov 25 2020 Packit Service <user-cont-team+packit-service@redhat.com> - 0.21.0-1
- pre-commit autoupdate (Jiri Popelka)
- 0.21.0 release (Release bot)
- parsing git remote URL: inform what's happening... (Tomas Tomecek)
- Revert "Allow recursive search for specfile in repository" (Matej Focko)
- Regenerate test_data for recursive (Matej Focko)
- Allow recursive search for specfile in repository (Matej Focko)
- cli.copr-build: replace / with - (Tomas Tomecek)
- copr, log CoprException.result when creating repo fails (Tomas Tomecek)
- Delete recipe-tests.yaml (Jiri Popelka)
- Add build to default jobs (lbarcziova)
- Add test case for Upstream._fix_spec_source() (Nikola Forró)
- Fix SpecFile.get_source() (Nikola Forró)
```

in the downstream spec changelog.

**Comment by lbarcziova** [comment]
We didn't specify `copy_upstream_release_description=true` mainly because of the markdown, but if it doesn't break anything, I would go for changing it. The other thing is we have the version in the release description, so it would be there twice: 
```
* Wed Nov 25 2020 Packit Service <user-cont-team+packit-service@redhat.com> - 0.21.0-1
# 0.21.0
- If the first `Source` tag in a spec file is not indexed, it is always returned,
  no matter the value of `source_name`.
- Sanitize potentially problematic characters in a branch name
  before creating a copr project name from it.
- Default job now includes copr build as well.
``` 
But it is still better than getting all commit messages since they can describe many non-user-related changes.

Can I update our configs then?

**Comment by lbarcziova** [comment]
Closing, `copy_upstream_release_description=true` was added to the configs in Packit and Ogr, so the changelogs contain nicer descriptions now.
