### ISSUE TITLE
Add run_id or pipeline concept to the database

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#895]
For #506, we need to match test-runs to copr-builds. For one trigger (like PR, branch, release) we can have multiple copr builds and for one copr build we can have multiple test runs.

Current state:
![db-current-state](https://user-images.githubusercontent.com/20214043/100863126-5fae6180-3494-11eb-9152-497fd4d2d676.png)

As a quick solution,
![db-add-connection](https://user-images.githubusercontent.com/20214043/100864219-fe878d80-3495-11eb-90f8-2fdd431d244f.png)
 we can connect test-runs and Copr builds directly:

Here are the proposed solutions:
- Add a `run_id` to the `JobTriggerModel`.
  - This will be an identifier connecting a group of jobs (i.e. builds, test-runs).
  - When we rerun anything, a new model is created and the previous steps are connected to multiple `run_id`s.
- Add a new pipeline model matching `JobTriggerModel` to build/test models.
  -  Adding a new table connecting a group of jobs (i.e. builds, test-runs) to `JobTriggerModel`.
  - When we rerun anything, a new model is created and the previous steps are connected to multiple `run_id`s.
![db-add-pipeline](https://user-images.githubusercontent.com/20214043/100864085-cd0ec200-3495-11eb-8248-d7924492fee9.png)

**Comment by lachmanfrantisek** [comment]
@sakalosj ping

**Comment by TomasTomecek** [comment]
Please describe what the run_id is and what are the expected relations with the pipeline model. A diagram would be awesome :)

**Comment by lachmanfrantisek** [comment]
@TomasTomecek You are strict...;(

I've added a few ERD-like diagrams... (primary/foreign keys and non-important attributes are missing)

**Comment by sakalosj** [comment]
sry closed by mistake

**Comment by TomasTomecek** [comment]
> @TomasTomecek You are strict...;(
> 
> I've added a few quickly-scatched ERD-like diagrams... (primary/foreign keys and non-important attributes are missing)

am I? :D I just had no idea what you are proposing here, I'd say this is now excellent and everyone can understand what this issue is about, thank you for updating it
