### ISSUE TITLE
Date in the SRPM logs page

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#912]
Suggested by @SpyTec [here](https://github.com/packit/packit/issues/1064#issue-778056903):

> *On a sidenote, can we get datetime printed on the SRPM builds and not just time? I can't tell if these logs are old or not without looking at the commits*

We can add a new entry before logs or edit the formatting of the logs.

**Comment by TomasTomecek** [comment]
Defintely a good suggestion. Though we are using a human-friendly time descrption, e.g.:

    Copr build > Build for fedora-rawhide-x86_64 started an hour ago, status: success 

Should we add 2 more lines with absolute values for "build submitted" and "build finished"?

**Comment by csomh** [comment]
If I understand the original proposal correctly, then a datetime should be added to the [SRPM logs page](https://prod.packit.dev/srpm-build/11650/logs), not the [results](https://prod.packit.dev/copr-build/75264) page. 

As the former can be shared without the later, and as there is currently no way to get back to the results page from an SRPM logs page, I think the request makes sense :slightly_smiling_face: 

Should the title of this issue be updated to reflect the actual request?

**Comment by lachmanfrantisek** [comment]
> If I understand the original proposal correctly, then a datetime should be added to the [SRPM logs page](https://prod.packit.dev/srpm-build/11650/logs), not the [results](https://prod.packit.dev/copr-build/75264) page.

By `result` page, I mean any page we link, but yes we can change the title to be more precise.

And it looks like we need need to add a nicely formatted datetime before the logs or improved the log format.

**Comment by lachmanfrantisek** [comment]
The task of this is to:
- Add human-friendly date and time of the build before logs.
- Or, tweak the log formatter to provide the nicer date-time format.

The format should fulfil:
- Contains date and time.
- Is in UTC and/or the zone is clear.

**Comment by lachmanfrantisek** [comment]
This has been fixed by the move to the dashboard status pages (currently on stage, will be on prod on Monday).

Example:
- https://dashboard.stg.packit.dev/results/srpm-builds/4305
![Screenshot from 2021-04-22 11-53-59](https://user-images.githubusercontent.com/20214043/115694907-99a7d380-a361-11eb-9a3a-0d4a22e120b3.png)
