### ISSUE TITLE
Queue jobs until remote services available

### ISSUE THREAD

**Issue by bocekm** [packit/packit-service#927]
*(edited by @lachmanfrantisek )*

To make Packit more reliable, it should retry the jobs where possible. We can easily react to a specific exception and put the job back in the celery queue. With this, users do not need to retrigger the job in case of infra problems.

Few notes for the implementation:
* Be careful if the job is idempotent and can be safely retried.
* Set the good maximum value for retries and provide a meaningful message after the last failed try.
* Be transparent about the retries -- think about a nice way how to let users know that Packit retried the job. Don't spam, but make it somehow visible so it does not feel like nothing is happening.
* We already have auto-retry in work for all the tasks:
  https://github.com/packit/packit-service/blob/307974f7bba1f349d5b0f9d0c0d3eaa6e988d2b4/packit_service/worker/tasks.py#L60-L65

Here is a list of the specific tasks:

- [x] #1548
- [x] #1570
- [x] #1571
- [x] #1549
- [x] #1550
- [x] https://github.com/packit/packit/issues/1656
- [x] #1551
- [x] #1692

### Original description:

Upon merging to the main branch of https://github.com/oamg/convert2rhel/, a copr build job [is triggered](https://github.com/oamg/convert2rhel/blob/master/.packit.yaml#L20).

Since today, the copr build is not being created with packit reporting:
`Submit of the build failed: Unable to connect to https://copr.fedorainfracloud.org/api_3/.`

**Comment by lachmanfrantisek** [comment]
This is still on our long-term todo list.

**Comment by bocekm** [comment]
@TomasTomecek, @lachmanfrantisek, feel free to change the title of the issue to something like "Queue jobs until remote services available" and/or edit the description to include Tomas' idea _"keep jobs in queue (by job I mean the fact you pushed to a branch) and schedule them (initiate the build) once the remote service becomes available."_ 

Or close this one and create a new one. Up to you.

**Comment by lbarcziova** [comment]
All the subtasks here were implemented.
