### ISSUE TITLE
The centos-stream-x86_64 config renamed to centos-stream-8-x86_64

### ISSUE THREAD

**Issue by praiskup** [packit/packit-service#961]
This is now happening in the mock-core-config, and we'll have to adjust copr configuration as well.

Naturally Packit has to follow :-/ sorry for inconvenience.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PJT7PK2TLW7T2Z2WLXUGHUYBWR244SBB/

**Comment by praiskup** [comment]
Tracking the copr change here:
https://pagure.io/copr/copr/issue/1691

**Comment by lachmanfrantisek** [comment]
@praiskup Thanks for letting us know. I am adding that to our TODO.

**Comment by lachmanfrantisek** [comment]
The task here is to:
- [ ] update documentation
- [ ] warn in the `validate` CLI command
- [ ] do not break current users of `centos-stream` target:
    - Use `centos-stream-8` when `centos-stream` is configured until we have two streams. (We want to be explicit later because it's hard to say if `centos-stream` means `8`, `9` or both.)
    - Ideally, automatically send a PR with the fix (replace the target value)
    - or, create a sentry/notification-repo issue and send a PR with the fix manually.

**Comment by lachmanfrantisek** [comment]
@mmuzila What we are missing here? Can we close the issue?

**Comment by TomasTomecek** [comment]
+1 to close this
