### ISSUE TITLE
Allow excluding/including specific paths from PR triggers

### ISSUE THREAD

**Issue by mrc0mmand** [packit/packit-service#969]
Hello again!

After some experience with other CIs, I think Packit would benefit from ability to allow specifying a list of paths to include or exclude from PR triggers, i.e. like paths/paths-ignore in [GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths). This should help saving some resources (especially in combination with #5), since not all changes need to be tested in all CIs.

**Comment by lachmanfrantisek** [comment]
Looks like a really good proposal...

I hope it will not take a lot of work to do. Thanks for the suggestion.

**Comment by csomh** [comment]
This seems to be a duplicate of #545. Closing.
