### ISSUE TITLE
Support restarting only some test jobs

### ISSUE THREAD

**Issue by thrix** [packit/packit-service#970]
Each `tmt` rerun now spawns like 24 machines :dagger: If I want to rerun just one of the test job, i.e.  packit/testing-farm-fedora-rawhide-x86_64, I cannot do that seems.

Seems it would be handy if we could restart only one or more test jobs via

```
/packit test REGEX
```

This would restart only test jobs matching the regex.

**Comment by TomasTomecek** [comment]
Makes sense to me and should be fairly easy to implement. The only problem I see is that we couldn't update commit statuses b/c there would only be a subset of tests executed and not everything - contributors could easily cheat CI like this - hence we should figure out a new reporting mechanism (comment?)

Miro, is this already supported by TF's API?

**Comment by thrix** [comment]
@TomasTomecek sorry seems my report was unclear. Under test jobs I meant test job as packit knows them, which is one testing farm execution. Hope that is more clear now.

**Comment by lachmanfrantisek** [comment]
To me it clear, we are speaking about `targets`/`chroots`.

**Comment by lachmanfrantisek** [comment]
This will be easy once we have #1203

**Comment by lachmanfrantisek** [comment]
Since we have the `restart` button and no one seems to want this, I am going to close.

If anyone thinks we need this, please, let us know. The only scenario the `restart` button does not help with is when we have a successful state but still want to do the restart.
