### ISSUE TITLE
Add a status message to the GitLab comments

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit-service#978]
When we don't have permission to create status, we put a comment instead:

![Screenshot from 2021-02-16 14-07-23](https://user-images.githubusercontent.com/20214043/108066943-5890fb80-7060-11eb-8f0d-ddbaa5f6aa22.png)

The table in the comment does not contain a message/description of the status.

**Comment by TomasTomecek** [comment]
exactly, I was really confused what that table actually meant :D 

it would be great to guide the contributor what they actually should do
