### ISSUE TITLE
/packit propose-downstream should react to GitLab Issue/MR comments

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#983]
```
[2021-02-17 08:40:44,591: DEBUG/ForkPoolWorker-1] We did not find any handler for a following event:
<class 'packit_service.service.events.IssueCommentGitlabEvent'>
```

It would be great if we were able to `propose-downstream` after an MR is merged

**Comment by mfocko** [comment]
looking at the code, it doesn't seem GitHub specific O.o so we could just add the event to `ProposeDownstreamHandler`

---
also it seems that `github_handlers` are more likely to be `git_forge_handlers` :upside_down_face:

**Comment by TomasTomecek** [comment]
> looking at the code, it doesn't seem GitHub specific O.o so we could just add the event to `ProposeDownstreamHandler`

so let's try :D
 
> also it seems that `github_handlers` are more likely to be `git_forge_handlers` upside_down_face

would be nice to treat them like that!

**Comment by lachmanfrantisek** [comment]
> also it seems that `github_handlers` are more likely to be `git_forge_handlers` upside_down_face

Exactly. Would be nice to correct that naming...

**Comment by mfocko** [comment]
@TomasTomecek so where are we going to test it once it's deployed? :)

**Comment by TomasTomecek** [comment]
probably here: https://gitlab.com/packit-service/src/glibc/-/tree/f34

but first I'd like to make sure that we don't overwrite downstream patches
