### ISSUE TITLE
Add new COPR build target for just fedora in development

### ISSUE THREAD

**Issue by jkonecny12** [packit/packit-service#986]
Hi everyone,

Right now you have great solution how to build for Rawhide by `fedora-rawhide` and you also have a target alias `fedora-development` to build against Rawhide and Fedora in development. However, I'm looking for just Fedora in development. I know I can use `fedora-34` but from that point I had to adjust the configuration file after each branching.

Could you please add new alias to target Fedora in development but not Rawhide? Thanks!

**Comment by jkonecny12** [comment]
This is an [example](https://github.com/rhinstaller/dasbus/pull/48) why we want this feature. We have a project which is using `master` branch for Rawhide and Fedora in development. However, we have because of Anaconda which also goes to this repository two COPR projects `Anaconda` and `Anaconda-devel`. Because of the current solution I have to change the configuration each branching to follow latest Fedora.

**Comment by mfocko** [comment]
- `fedora-rawhide` = rawhide
- `fedora-development` = rawhide + next release if available
- `fedora-next` = next release or rawhide if there's no branch yet?

Ideally you'd like something like this?

Also looking at the branches and packit config, even if you had alias like that, you'd need to either adjust
- the branch name of the Fedora in development, or
- config when branching,

since you have `f34-devel` as branch name in the config [here](https://github.com/rhinstaller/anaconda/blob/923d112d6f7fa921325be5819aefdae62aee66bd/.packit.yml#L42).

**Comment by csomh** [comment]
Just heads up, that there is a period of time, when there is no `fedora-next`.

For example: Fedora 33 was released at the end of October, but Fedora 34 was branched from rawhide just last week. So there were 2+ months when there was only rawhide available. How should `fedora-next` work during this period?

**Comment by mfocko** [comment]
> Just heads up, that there is a period of time, when there is no `fedora-next`.
> 
> For example: Fedora 33 was released at the end of October, but Fedora 34 was branched from rawhide just last week. So there were 3+ months when there was only rawhide available. How should `fedora-next` work during this period?

could be resolved by the comment in parenthesis:
1. from release to branching we could still point to release
   - after release of F33: `fedora-next = fedora-33`
   - after branching of F34: `fedora-next = fedora-34`
2. or we could point to rawhide
   - after release of F33: `fedora-next = fedora-rawhide`
   - after branching of F34: `fedora-next = fedora-34`

---
1. is easy to handle, might not be very straightforward from release to next branch
2. is more problematic, but may reflect the intention better

imo the best decision would be to choose the one that is closest to the workflow during that period, can't tell which one it would be though
After release we have only `rawhide` in `fedora-development`, so it would also make sense to have it disabled? that's also bit meh

**Comment by lachmanfrantisek** [comment]
> How should fedora-next work during this period?

I would say `rawhide`. Or what about having `fedora-branched` that would lead to nothing before merging?

**Comment by csomh** [comment]
I would find an alias resolving to nothing somewhat confusing. Wouldn't that make every job configured for only that target a noop, as soon as the alias resolves to nothing? What do you think, @jkonecny12? What would be your expectation in such a case?

**Comment by jkonecny12** [comment]
The fedora-next pointing to Rawhide or Fedora before GA seems reasonable, unfortunately not great for us. As I mentioned earlier we have separate repositories in copr to separate Rawhide from Fedora before GA so it wouldn't be best solution for us.

Maybe something like `fedora-latest` which would point to the last Fedora all the time but not to Rawhide?

**Comment by csomh** [comment]
@jkonecny12 By "last Fedora" you mean the "last Fedora which has already a branch in dist-git"?

**Comment by jkonecny12** [comment]
Yes. On the other hand... I'm thinking that having latest Fedora and Rawhide won't be really a problem because the consumers will take only what is interesting for them. So if you prefer, you can go also with the solution above. Shouldn't be a problem for us at the end.

**Comment by lachmanfrantisek** [comment]
Let's conclude this:

* [ ] We need an alias that points to the latest Fedora, but not `rawhide`.
* [ ] The alias can be named `fedora-latest`.

@jkonecny12 Will this work for you?

Others, does it make sense to you? Do you have some better name in mind?

**Comment by jkonecny12** [comment]
Yes, that sounds like the best approach! Thanks!
