### ISSUE TITLE
The onboarding process

### ISSUE THREAD

**Issue by johannbg** [packit/packit-service#997]
As to the best of our knowledge both for libvarlink and dracut we have followed the documentation to the letter on the onboarding process for packit yet in dracut we are hitting "Namespace is not allowed!" which indicates the approval process has not been done and or some other permission errors or configuration on our behalf.

What do we have to do, to move things along and are you planning on incorporate something in the onboarding process which does not require some form of manual intervention on packit's teams behalf ( We should just be able to log into something and approving it ourselves using our FAS credential/permissions right? )  which seems to be the case happening here and is acting as an bottleneck in the onboarding process.

**Comment by TomasTomecek** [comment]
Hi @johannbg and welcome! I can indeed see in our logs that both namespaces are not in our allowlist.

I just approved both and can see that builds are kicking in: https://github.com/dracutdevs/dracut/pull/1126

Sorry for the trouble, I'll make sure we investigate why we haven't been notified about you requesting using packit via our notification repository.

**Comment by johannbg** [comment]
It makes most sense that the "vetting" process is just part of Fedora's vetting process for the package ownership as in you have to be part of the maintainers group owning the component in Fedora and then anyone from that team could just login and click enable packit somewhere when ready.  + you are just opening a can of worms ( security and component conflict wise ) if you intend to support use cases in which an user who does not "own" or otherwise is not part of the downstream maintainership of an component downstream, would be allowed to use packit in some shape or form for that component. 

Anyway thanks for moving this along.

**Comment by TomasTomecek** [comment]
I actually really like your proposal and will discuss it within the team.

**Comment by TomasTomecek** [comment]
If you don't mind, I'm going to reopen this issue and use it to track the work to log into Fedora FAS to automate the onboarding process.
