### ISSUE TITLE
no new notification for varlink and dracutdevs namespaces

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#998]
context: https://github.com/packit/packit-service/issues/997

I can see: https://sentry.io/organizations/red-hat-0p/issues/2233146066/activity/?environment=prod&project=1767823&referrer=alert_email

**Comment by lachmanfrantisek** [comment]
The task here is to fix a problem with not receiving a notification (in a form of [new issue in the notifications repo](https://github.com/packit/notifications/issues?q=is%3Aissue)) about namespaces that need to be approved and added to the allowlist.
